/* Run As: SYS. Protidin sokal e 10 sec: backup hoyeche kina */
SET LINES 200 PAGES 100
COL STATUS FORMAT A12
COL INPUT_TYPE FORMAT A12
SELECT TO_CHAR(START_TIME,'DD-MON HH24:MI') START_T, INPUT_TYPE, STATUS,
       ROUND(ELAPSED_SECONDS/60,1) MINS, OUTPUT_BYTES_DISPLAY SIZE_OUT
FROM V$RMAN_BACKUP_JOB_DETAILS
WHERE START_TIME > SYSDATE - 8 ORDER BY START_TIME DESC;

SELECT JOB_NAME, STATE FROM DBA_DATAPUMP_JOBS;
SELECT NAME, ROUND(SPACE_LIMIT/1024/1024/1024,1) LIMIT_GB,
       ROUND(SPACE_USED/1024/1024/1024,1) USED_GB FROM V$RECOVERY_FILE_DEST;
SELECT LOG_MODE, FLASHBACK_ON FROM V$DATABASE;
