-- START_OF_DAY.bat eta call kore: import er age purono object muche fela
WHENEVER SQLERROR EXIT FAILURE
BEGIN
    IF USER <> 'HMS_APP' THEN RAISE_APPLICATION_ERROR(-20999, 'Only HMS_APP'); END IF;
    FOR o IN (SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_OBJECTS
               WHERE OBJECT_TYPE IN ('VIEW','PACKAGE','FUNCTION','PROCEDURE','SEQUENCE','TRIGGER','TYPE')) LOOP
        BEGIN EXECUTE IMMEDIATE 'DROP ' || o.OBJECT_TYPE || ' "' || o.OBJECT_NAME || '"';
        EXCEPTION WHEN OTHERS THEN NULL; END;
    END LOOP;
    FOR t IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE "' || t.TABLE_NAME || '" CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/
EXIT
