-- APEX app (apex\f100.sql) ei PC er workspace e install
BEGIN
    APEX_APPLICATION_INSTALL.SET_WORKSPACE('HMS');
    APEX_APPLICATION_INSTALL.SET_APPLICATION_ID(100);
    APEX_APPLICATION_INSTALL.GENERATE_OFFSET;
    APEX_APPLICATION_INSTALL.SET_SCHEMA('HMS_APP');
END;
/
@..\apex\f100.sql
EXIT
