/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : create_all_sequences.sql
 Purpose   : All sequences (one per table). START WITH value = &START_VALUE (PC-1 = 1, PC-2 = 1000001 etc.)
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF
SET DEFINE ON
-- Development e 2 PC use korle ID clash na korar jonno start value alada rakhun.
-- Production e 1 use korben.
DEFINE START_VALUE = 1

PROMPT >>> Creating sequences ...

-- CORE / MASTER MODULE (Foundation)
CREATE SEQUENCE SEQ_BRANCH                         START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DEPARTMENT                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DESIGNATION                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEE                       START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEE_QUALIFICATION         START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEE_EXPERIENCE            START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DOCTOR                         START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DOCTOR_DEPT_MAP                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DOCTOR_SCHEDULE                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LOOKUP_MASTER                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_SYSTEM_CONFIG                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_NUMBER_SERIES                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_ICD_MASTER                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_SHIFT_MASTER                   START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- SECURITY MODULE (User, Role, Menu Access)
CREATE SEQUENCE SEQ_ROLE                           START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_APP_MODULE                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_ROLE_PERMISSION                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_USER                           START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_USER_ROLE                      START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LOGIN_HISTORY                  START WITH &START_VALUE INCREMENT BY 1 CACHE 1000 NOCYCLE;

-- PATIENT MANAGEMENT MODULE
CREATE SEQUENCE SEQ_PATIENT                        START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PATIENT_ALLERGY                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PATIENT_MEDICAL_HISTORY        START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PATIENT_DOCUMENT               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- SERVICE / CHARGE MASTER
CREATE SEQUENCE SEQ_SERVICE_CATEGORY               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_MASTER                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_CHARGE                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_PACKAGE_DTL            START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DOCTOR_COMMISSION              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- APPOINTMENT & SCHEDULING
CREATE SEQUENCE SEQ_APPOINTMENT                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_COMMUNICATION_LOG              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- OPD (Out Patient Department)
CREATE SEQUENCE SEQ_OPD_VISIT                      START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OPD_VITALS                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OPD_CONSULTATION               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OPD_PRESCRIPTION               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OPD_PRESCRIPTION_DTL           START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OPD_PROCEDURE                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- IPD (In Patient Department)
CREATE SEQUENCE SEQ_WARD                           START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BED                            START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IPD_ADMISSION                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BED_TRANSFER                   START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IPD_DOCTOR_VISIT               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IPD_MEDICATION                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IPD_MED_ADMINISTRATION         START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DISCHARGE_SUMMARY              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- DIAGNOSTIC & LABORATORY
CREATE SEQUENCE SEQ_INVESTIGATION_ORDER            START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_INVESTIGATION_ORDER_DTL        START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LAB_PARAMETER                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LAB_REFERENCE_RANGE            START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LAB_SAMPLE                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LAB_EQUIPMENT                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LAB_RESULT                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LAB_RESULT_AMENDMENT           START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- RADIOLOGY / IMAGING
CREATE SEQUENCE SEQ_RADIOLOGY_ORDER                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_RADIOLOGY_IMAGE                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_REPORT_TEMPLATE                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- PHARMACY
CREATE SEQUENCE SEQ_PHARMA_CATEGORY                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_GENERIC                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_MANUFACTURER            START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_ITEM                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_SUPPLIER                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_STORE                   START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_PURCHASE_ORDER          START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_PO_DTL                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_GRN                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_GRN_DTL                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_STOCK                   START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_SALE                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_SALE_DTL                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_SALE_RETURN             START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHARMA_TRANSACTION             START WITH &START_VALUE INCREMENT BY 1 CACHE 1000 NOCYCLE;

-- OPERATION THEATRE (OT)
CREATE SEQUENCE SEQ_OT_MASTER                      START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_SURGERY_MASTER                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OT_BOOKING                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OT_TEAM                        START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OT_NOTES                       START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_OT_CONSUMABLE                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- BLOOD BANK
CREATE SEQUENCE SEQ_BLOOD_DONOR                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BLOOD_COLLECTION               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BLOOD_INVENTORY                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BLOOD_REQUISITION              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BLOOD_CROSSMATCH               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BLOOD_ISSUE                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- NURSING
CREATE SEQUENCE SEQ_NURSING_ASSESSMENT             START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IPD_VITALS                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_NURSING_CARE_PLAN              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_NURSING_NOTES                  START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- DIET / KITCHEN
CREATE SEQUENCE SEQ_DIET_MASTER                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DIET_ORDER                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DIET_SERVING                   START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- INSURANCE / TPA / CORPORATE
CREATE SEQUENCE SEQ_INSURANCE_COMPANY              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_INSURANCE_PLAN                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PATIENT_INSURANCE              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_INSURANCE_PREAUTH              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- ACCOUNT & BILLING
CREATE SEQUENCE SEQ_BILLING                        START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BILLING_DTL                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PATIENT_ADVANCE                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PAYMENT_RECEIPT                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_INSURANCE_CLAIM                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_DOCTOR_EARNING                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_CHART_OF_ACCOUNTS              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_JOURNAL_VOUCHER                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_JOURNAL_VOUCHER_DTL            START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- INVENTORY & STORE (General items + Asset)
CREATE SEQUENCE SEQ_INV_STORE                      START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_INV_ITEM                       START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_INV_STOCK                      START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_INDENT                         START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_INDENT_DTL                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_ASSET                          START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- ADMIN / HR / PAYROLL
CREATE SEQUENCE SEQ_DUTY_ROSTER                    START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_ATTENDANCE                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LEAVE_TYPE                     START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LEAVE_APPLICATION              START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_SALARY_STRUCTURE               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PAYROLL                        START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- EMERGENCY & AMBULANCE
CREATE SEQUENCE SEQ_EMERGENCY_VISIT                START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_EMERGENCY_TRIAGE               START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_AMBULANCE                      START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_AMBULANCE_TRIP                 START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- MORTUARY
CREATE SEQUENCE SEQ_MORTUARY                       START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- AUDIT & SECURITY LOG
CREATE SEQUENCE SEQ_AUDIT_TRAIL                    START WITH &START_VALUE INCREMENT BY 1 CACHE 1000 NOCYCLE;
CREATE SEQUENCE SEQ_ERROR_LOG                      START WITH &START_VALUE INCREMENT BY 1 CACHE 20 NOCYCLE;

-- Document number sequence (fallback)
CREATE SEQUENCE SEQ_DOC_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

SET DEFINE OFF
