# -*- coding: utf-8 -*-
"""
HMS table definitions (single source of truth).
Each table gets automatically:
  * PK column  <PK> NUMBER DEFAULT SEQ_<TABLE>.NEXTVAL
  * IS_ACTIVE (unless active=False)
  * CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE
  * LOB storage in HMS_LOB for BLOB/CLOB columns
"""

MODULES = []   # (file_no, file_name, title, [tables])

def module(no, fname, title):
    m = (no, fname, title, [])
    MODULES.append(m)
    return m[3]

def T(lst, name, pk, cols, cons="", active=True, comment=""):
    lst.append(dict(name=name, pk=pk, cols=cols.strip(), cons=cons.strip(),
                    active=active, comment=comment))

YN = "CHAR(1) DEFAULT 'N' CHECK ({c} IN ('Y','N'))"
def yn(col, d='N'):
    return f"{col} CHAR(1) DEFAULT '{d}' NOT NULL CHECK ({col} IN ('Y','N'))"

# =====================================================================
# 01 CORE / MASTER
# =====================================================================
m = module(1, "01_core_tables.sql", "CORE / MASTER MODULE (Foundation)")

T(m, "HMS_BRANCH", "BRANCH_ID", f"""
BRANCH_CODE        VARCHAR2(20)  NOT NULL,
BRANCH_NAME        VARCHAR2(200) NOT NULL,
ADDRESS_LINE1      VARCHAR2(300),
ADDRESS_LINE2      VARCHAR2(300),
CITY               VARCHAR2(100),
DISTRICT           VARCHAR2(100),
DIVISION           VARCHAR2(100),
COUNTRY            VARCHAR2(100) DEFAULT 'Bangladesh',
POST_CODE          VARCHAR2(20),
PHONE              VARCHAR2(50),
EMAIL              VARCHAR2(150),
LICENSE_NO         VARCHAR2(100),
LOGO               BLOB,
{yn('IS_HEAD_OFFICE')}
""", "CONSTRAINT UK_BRANCH_CODE UNIQUE (BRANCH_CODE)", comment="Hospital branch / unit")

T(m, "HMS_DEPARTMENT", "DEPT_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
DEPT_CODE          VARCHAR2(20)  NOT NULL,
DEPT_NAME          VARCHAR2(200) NOT NULL,
DEPT_TYPE          VARCHAR2(30)  CHECK (DEPT_TYPE IN ('CLINICAL','NON_CLINICAL','DIAGNOSTIC','ADMIN','SUPPORT','PHARMACY','LAB')),
PARENT_DEPT_ID     NUMBER REFERENCES HMS_DEPARTMENT(DEPT_ID),
HOD_EMPLOYEE_ID    NUMBER,
FLOOR_NO           VARCHAR2(20),
ROOM_NO            VARCHAR2(20),
EXTENSION_NO       VARCHAR2(20)
""", "CONSTRAINT UK_DEPT UNIQUE (BRANCH_ID, DEPT_CODE)")

T(m, "HMS_DESIGNATION", "DESIGNATION_ID", """
DESIGNATION_CODE   VARCHAR2(20)  NOT NULL,
DESIGNATION_NAME   VARCHAR2(200) NOT NULL,
DESIGNATION_LEVEL  NUMBER
""", "CONSTRAINT UK_DESIGNATION_CODE UNIQUE (DESIGNATION_CODE)")

T(m, "HMS_EMPLOYEE", "EMPLOYEE_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
DEPT_ID            NUMBER NOT NULL REFERENCES HMS_DEPARTMENT(DEPT_ID),
DESIGNATION_ID     NUMBER NOT NULL REFERENCES HMS_DESIGNATION(DESIGNATION_ID),
EMPLOYEE_CODE      VARCHAR2(30)  NOT NULL,
FIRST_NAME         VARCHAR2(100) NOT NULL,
LAST_NAME          VARCHAR2(100),
GENDER             VARCHAR2(10) CHECK (GENDER IN ('MALE','FEMALE','OTHER')),
DATE_OF_BIRTH      DATE,
NID_NUMBER         VARCHAR2(50),
PASSPORT_NO        VARCHAR2(50),
BLOOD_GROUP        VARCHAR2(5),
MARITAL_STATUS     VARCHAR2(20),
RELIGION           VARCHAR2(30),
PHOTO              BLOB,
PHONE              VARCHAR2(50),
EMERGENCY_CONTACT  VARCHAR2(50),
EMAIL              VARCHAR2(150),
PRESENT_ADDRESS    VARCHAR2(500),
PERMANENT_ADDRESS  VARCHAR2(500),
JOINING_DATE       DATE NOT NULL,
RESIGNATION_DATE   DATE,
EMPLOYEE_TYPE      VARCHAR2(30) CHECK (EMPLOYEE_TYPE IN ('PERMANENT','CONTRACT','VISITING','INTERN','TRAINEE')),
REPORTING_TO       NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
BANK_NAME          VARCHAR2(150),
BANK_ACCOUNT_NO    VARCHAR2(50),
TIN_NO             VARCHAR2(50)
""", "CONSTRAINT UK_EMPLOYEE_CODE UNIQUE (EMPLOYEE_CODE)")

T(m, "HMS_EMPLOYEE_QUALIFICATION", "QUALIFICATION_ID", """
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
DEGREE_NAME        VARCHAR2(200) NOT NULL,
INSTITUTE          VARCHAR2(300),
BOARD_UNIVERSITY   VARCHAR2(300),
PASSING_YEAR       NUMBER(4),
RESULT_GRADE       VARCHAR2(50),
CERTIFICATE_DOC    BLOB
""")

T(m, "HMS_EMPLOYEE_EXPERIENCE", "EXPERIENCE_ID", """
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
ORGANIZATION_NAME  VARCHAR2(300) NOT NULL,
POSITION_HELD      VARCHAR2(200),
START_DATE         DATE,
END_DATE           DATE,
RESPONSIBILITIES   VARCHAR2(1000)
""")

T(m, "HMS_DOCTOR", "DOCTOR_ID", f"""
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
DOCTOR_CODE        VARCHAR2(30) NOT NULL,
SPECIALIZATION     VARCHAR2(200),
SUB_SPECIALIZATION VARCHAR2(200),
QUALIFICATION      VARCHAR2(500),
BMDC_REG_NO        VARCHAR2(50),
EXPERIENCE_YEARS   NUMBER,
CONSULTATION_FEE   NUMBER(12,2) DEFAULT 0,
FOLLOWUP_FEE       NUMBER(12,2) DEFAULT 0,
FOLLOWUP_VALID_DAYS NUMBER DEFAULT 7,
DOCTOR_TYPE        VARCHAR2(30) CHECK (DOCTOR_TYPE IN ('FULL_TIME','PART_TIME','VISITING','CONSULTANT','RESIDENT')),
MAX_PATIENT_PER_DAY NUMBER,
SIGNATURE_IMAGE    BLOB,
{yn('IS_SURGEON')}
""", "CONSTRAINT UK_DOCTOR_CODE UNIQUE (DOCTOR_CODE)")

T(m, "HMS_DOCTOR_DEPT_MAP", "MAP_ID", f"""
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
DEPT_ID            NUMBER NOT NULL REFERENCES HMS_DEPARTMENT(DEPT_ID),
{yn('IS_PRIMARY')}
""", "CONSTRAINT UK_DOC_DEPT UNIQUE (DOCTOR_ID, DEPT_ID)")

T(m, "HMS_DOCTOR_SCHEDULE", "SCHEDULE_ID", """
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
DAY_OF_WEEK        VARCHAR2(10) NOT NULL CHECK (DAY_OF_WEEK IN ('SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY')),
START_TIME         VARCHAR2(5) NOT NULL,
END_TIME           VARCHAR2(5) NOT NULL,
SLOT_DURATION_MIN  NUMBER DEFAULT 10,
MAX_SLOTS          NUMBER,
ROOM_NO            VARCHAR2(20)
""", comment="START_TIME/END_TIME format HH24:MI (e.g. 17:30)")

T(m, "HMS_LOOKUP_MASTER", "LOOKUP_ID", """
LOOKUP_TYPE        VARCHAR2(100) NOT NULL,
LOOKUP_CODE        VARCHAR2(50)  NOT NULL,
LOOKUP_VALUE       VARCHAR2(200) NOT NULL,
DISPLAY_ORDER      NUMBER
""", "CONSTRAINT UK_LOOKUP UNIQUE (LOOKUP_TYPE, LOOKUP_CODE)",
  comment="Generic dropdown values (Blood group, Religion, Relation ...)")

T(m, "HMS_SYSTEM_CONFIG", "CONFIG_ID", """
BRANCH_ID          NUMBER REFERENCES HMS_BRANCH(BRANCH_ID),
CONFIG_KEY         VARCHAR2(100) NOT NULL,
CONFIG_VALUE       VARCHAR2(1000),
CONFIG_DESC        VARCHAR2(500)
""", "CONSTRAINT UK_SYS_CONFIG UNIQUE (BRANCH_ID, CONFIG_KEY)")

T(m, "HMS_NUMBER_SERIES", "SERIES_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
SERIES_TYPE        VARCHAR2(50) NOT NULL,
PREFIX             VARCHAR2(20),
CURRENT_NO         NUMBER DEFAULT 0 NOT NULL,
PAD_LENGTH         NUMBER DEFAULT 6,
RESET_CYCLE        VARCHAR2(10) DEFAULT 'NEVER' CHECK (RESET_CYCLE IN ('NEVER','YEARLY','MONTHLY','DAILY')),
LAST_RESET_DATE    DATE
""", "CONSTRAINT UK_NUM_SERIES UNIQUE (BRANCH_ID, SERIES_TYPE)",
  comment="MRN, Bill No, Visit No, Admission No generate korar jonno")

T(m, "HMS_ICD_MASTER", "ICD_ID", """
ICD_CODE           VARCHAR2(20)  NOT NULL,
ICD_DESCRIPTION    VARCHAR2(500) NOT NULL,
ICD_CATEGORY       VARCHAR2(200),
PARENT_ICD_ID      NUMBER REFERENCES HMS_ICD_MASTER(ICD_ID)
""", "CONSTRAINT UK_ICD_CODE UNIQUE (ICD_CODE)")

T(m, "HMS_SHIFT_MASTER", "SHIFT_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
SHIFT_CODE         VARCHAR2(20) NOT NULL,
SHIFT_NAME         VARCHAR2(100) NOT NULL,
START_TIME         VARCHAR2(5) NOT NULL,
END_TIME           VARCHAR2(5) NOT NULL,
GRACE_MIN          NUMBER DEFAULT 15
""", "CONSTRAINT UK_SHIFT UNIQUE (BRANCH_ID, SHIFT_CODE)")

# =====================================================================
# 02 SECURITY (user/role) - early, other modules don't FK to it
# =====================================================================
m = module(2, "02_security_tables.sql", "SECURITY MODULE (User, Role, Menu Access)")

T(m, "HMS_ROLE", "ROLE_ID", """
ROLE_CODE          VARCHAR2(50)  NOT NULL,
ROLE_NAME          VARCHAR2(200) NOT NULL,
ROLE_DESC          VARCHAR2(500)
""", "CONSTRAINT UK_ROLE_CODE UNIQUE (ROLE_CODE)")

T(m, "HMS_APP_MODULE", "MODULE_ID", """
MODULE_CODE        VARCHAR2(50)  NOT NULL,
MODULE_NAME        VARCHAR2(200) NOT NULL,
PARENT_MODULE_ID   NUMBER REFERENCES HMS_APP_MODULE(MODULE_ID),
APEX_PAGE_NO       NUMBER,
ICON_CLASS         VARCHAR2(100),
DISPLAY_ORDER      NUMBER
""", "CONSTRAINT UK_MODULE_CODE UNIQUE (MODULE_CODE)", comment="Menu / page list")

T(m, "HMS_ROLE_PERMISSION", "PERMISSION_ID", f"""
ROLE_ID            NUMBER NOT NULL REFERENCES HMS_ROLE(ROLE_ID),
MODULE_ID          NUMBER NOT NULL REFERENCES HMS_APP_MODULE(MODULE_ID),
{yn('CAN_VIEW','Y')},
{yn('CAN_ADD')},
{yn('CAN_EDIT')},
{yn('CAN_DELETE')},
{yn('CAN_PRINT')},
{yn('CAN_APPROVE')}
""", "CONSTRAINT UK_ROLE_PERM UNIQUE (ROLE_ID, MODULE_ID)")

T(m, "HMS_USER", "USER_ID", f"""
EMPLOYEE_ID        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
USERNAME           VARCHAR2(100) NOT NULL,
PASSWORD_HASH      VARCHAR2(500) NOT NULL,
PASSWORD_SALT      VARCHAR2(200),
EMAIL              VARCHAR2(150),
MOBILE             VARCHAR2(50),
LAST_LOGIN         TIMESTAMP,
FAILED_ATTEMPTS    NUMBER DEFAULT 0,
{yn('IS_LOCKED')},
PASSWORD_CHANGED_ON DATE,
{yn('FORCE_PWD_CHANGE','Y')}
""", "CONSTRAINT UK_USERNAME UNIQUE (USERNAME)")

T(m, "HMS_USER_ROLE", "USER_ROLE_ID", """
USER_ID            NUMBER NOT NULL REFERENCES HMS_USER(USER_ID),
ROLE_ID            NUMBER NOT NULL REFERENCES HMS_ROLE(ROLE_ID)
""", "CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID)")

T(m, "HMS_LOGIN_HISTORY", "LOGIN_ID", """
USER_ID            NUMBER REFERENCES HMS_USER(USER_ID),
USERNAME           VARCHAR2(100),
LOGIN_TIME         TIMESTAMP DEFAULT SYSTIMESTAMP,
LOGOUT_TIME        TIMESTAMP,
IP_ADDRESS         VARCHAR2(50),
BROWSER_INFO       VARCHAR2(500),
LOGIN_STATUS       VARCHAR2(20) CHECK (LOGIN_STATUS IN ('SUCCESS','FAILED','LOCKED'))
""", active=False)

# =====================================================================
# 03 PATIENT
# =====================================================================
m = module(3, "03_patient_tables.sql", "PATIENT MANAGEMENT MODULE")

T(m, "HMS_PATIENT", "PATIENT_ID", f"""
MRN                VARCHAR2(30)  NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
TITLE              VARCHAR2(10),
FIRST_NAME         VARCHAR2(100) NOT NULL,
MIDDLE_NAME        VARCHAR2(100),
LAST_NAME          VARCHAR2(100),
FATHER_NAME        VARCHAR2(200),
MOTHER_NAME        VARCHAR2(200),
SPOUSE_NAME        VARCHAR2(200),
GENDER             VARCHAR2(10) NOT NULL CHECK (GENDER IN ('MALE','FEMALE','OTHER')),
DATE_OF_BIRTH      DATE,
AGE_YEARS          NUMBER,
AGE_MONTHS         NUMBER,
AGE_DAYS           NUMBER,
BLOOD_GROUP        VARCHAR2(5),
MARITAL_STATUS     VARCHAR2(20),
RELIGION           VARCHAR2(30),
NATIONALITY        VARCHAR2(50) DEFAULT 'Bangladeshi',
NID_NUMBER         VARCHAR2(50),
BIRTH_REG_NO       VARCHAR2(50),
PASSPORT_NO        VARCHAR2(50),
OCCUPATION         VARCHAR2(100),
PHONE_PRIMARY      VARCHAR2(50) NOT NULL,
PHONE_SECONDARY    VARCHAR2(50),
EMAIL              VARCHAR2(150),
PRESENT_ADDRESS    VARCHAR2(500),
PRESENT_THANA      VARCHAR2(100),
PRESENT_DISTRICT   VARCHAR2(100),
PRESENT_DIVISION   VARCHAR2(100),
PERMANENT_ADDRESS  VARCHAR2(500),
PERMANENT_DISTRICT VARCHAR2(100),
EMERGENCY_CONTACT_NAME     VARCHAR2(200),
EMERGENCY_CONTACT_PHONE    VARCHAR2(50),
EMERGENCY_CONTACT_RELATION VARCHAR2(50),
PHOTO              BLOB,
REFERRED_BY        VARCHAR2(200),
REFERRED_DOCTOR_ID NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
REGISTRATION_DATE  DATE DEFAULT SYSDATE,
{yn('IS_VIP')},
{yn('IS_MEDICO_LEGAL')},
PATIENT_CATEGORY   VARCHAR2(30) DEFAULT 'GENERAL' CHECK (PATIENT_CATEGORY IN ('GENERAL','STAFF','VIP','CORPORATE','INSURANCE','POOR_FREE')),
REMARKS            VARCHAR2(500)
""", "CONSTRAINT UK_PATIENT_MRN UNIQUE (MRN)")

T(m, "HMS_PATIENT_ALLERGY", "ALLERGY_ID", """
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
ALLERGY_TYPE       VARCHAR2(30) CHECK (ALLERGY_TYPE IN ('DRUG','FOOD','ENVIRONMENT','OTHER')),
ALLERGY_NAME       VARCHAR2(200) NOT NULL,
SEVERITY           VARCHAR2(20) CHECK (SEVERITY IN ('MILD','MODERATE','SEVERE')),
REACTION_DESC      VARCHAR2(500),
NOTED_DATE         DATE DEFAULT SYSDATE,
NOTED_BY           NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""")

T(m, "HMS_PATIENT_MEDICAL_HISTORY", "HISTORY_ID", f"""
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
DISEASE_NAME       VARCHAR2(200),
ICD_ID             NUMBER REFERENCES HMS_ICD_MASTER(ICD_ID),
DIAGNOSIS_DATE     DATE,
{yn('IS_CHRONIC')},
TREATMENT_DETAILS  VARCHAR2(4000),
{yn('IS_FAMILY_HISTORY')},
RELATION           VARCHAR2(50),
REMARKS            VARCHAR2(500),
RECORDED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""")

T(m, "HMS_PATIENT_DOCUMENT", "DOCUMENT_ID", """
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
REF_TYPE           VARCHAR2(20),
REF_ID             NUMBER,
DOCUMENT_TYPE      VARCHAR2(50),
DOCUMENT_NAME      VARCHAR2(200),
FILE_NAME          VARCHAR2(300),
FILE_CONTENT       BLOB,
FILE_SIZE_KB       NUMBER,
MIME_TYPE          VARCHAR2(100),
UPLOADED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
REMARKS            VARCHAR2(500)
""", comment="REF_TYPE = OPD/IPD/LAB ... , REF_ID = related visit/admission id")

# =====================================================================
# 04 SERVICE MASTER (needed by OPD/IPD/LAB/BILLING)
# =====================================================================
m = module(4, "04_service_tables.sql", "SERVICE / CHARGE MASTER")

T(m, "HMS_SERVICE_CATEGORY", "CATEGORY_ID", """
CATEGORY_CODE      VARCHAR2(30)  NOT NULL,
CATEGORY_NAME      VARCHAR2(200) NOT NULL,
CATEGORY_TYPE      VARCHAR2(30) CHECK (CATEGORY_TYPE IN ('CONSULTATION','LAB','RADIOLOGY','PROCEDURE','BED','OT','NURSING','PHARMACY','PACKAGE','MISC')),
PARENT_CATEGORY_ID NUMBER REFERENCES HMS_SERVICE_CATEGORY(CATEGORY_ID),
DISPLAY_ORDER      NUMBER
""", "CONSTRAINT UK_SVC_CAT UNIQUE (CATEGORY_CODE)")

T(m, "HMS_SERVICE_MASTER", "SERVICE_ID", f"""
CATEGORY_ID        NUMBER NOT NULL REFERENCES HMS_SERVICE_CATEGORY(CATEGORY_ID),
DEPT_ID            NUMBER REFERENCES HMS_DEPARTMENT(DEPT_ID),
SERVICE_CODE       VARCHAR2(30)  NOT NULL,
SERVICE_NAME       VARCHAR2(300) NOT NULL,
SHORT_NAME         VARCHAR2(100),
BASE_CHARGE        NUMBER(12,2) DEFAULT 0 NOT NULL,
EMERGENCY_CHARGE   NUMBER(12,2),
{yn('TAX_APPLICABLE')},
TAX_PERCENT        NUMBER(5,2) DEFAULT 0,
TURN_AROUND_TIME   VARCHAR2(50),
{yn('SAMPLE_REQUIRED')},
SAMPLE_TYPE        VARCHAR2(100),
REPORTING_SECTION  VARCHAR2(100),
{yn('IS_PACKAGE')},
{yn('IS_OUTSOURCED')},
OUTSOURCE_LAB      VARCHAR2(200),
OUTSOURCE_COST     NUMBER(12,2),
{yn('CONSENT_REQUIRED')},
GENDER_SPECIFIC    VARCHAR2(10) CHECK (GENDER_SPECIFIC IN ('MALE','FEMALE','ALL')),
{yn('DOCTOR_COMMISSION_APPLICABLE')}
""", "CONSTRAINT UK_SERVICE_CODE UNIQUE (SERVICE_CODE)")

T(m, "HMS_SERVICE_CHARGE", "CHARGE_ID", """
SERVICE_ID         NUMBER NOT NULL REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
PATIENT_CATEGORY   VARCHAR2(30) NOT NULL,
CHARGE_AMOUNT      NUMBER(12,2) NOT NULL,
DISCOUNT_PERCENT   NUMBER(5,2) DEFAULT 0,
EFFECTIVE_FROM     DATE NOT NULL,
EFFECTIVE_TO       DATE
""", "CONSTRAINT UK_SVC_CHARGE UNIQUE (SERVICE_ID, BRANCH_ID, PATIENT_CATEGORY, EFFECTIVE_FROM)",
  comment="Category-wise (GENERAL/VIP/CORPORATE) rate")

T(m, "HMS_SERVICE_PACKAGE_DTL", "PACKAGE_DTL_ID", f"""
PACKAGE_SERVICE_ID NUMBER NOT NULL REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
CHILD_SERVICE_ID   NUMBER NOT NULL REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
QUANTITY           NUMBER DEFAULT 1,
{yn('IS_MANDATORY','Y')},
DISPLAY_ORDER      NUMBER
""", "CONSTRAINT UK_PKG_DTL UNIQUE (PACKAGE_SERVICE_ID, CHILD_SERVICE_ID)")

T(m, "HMS_DOCTOR_COMMISSION", "COMMISSION_ID", """
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
SERVICE_ID         NUMBER REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
CATEGORY_ID        NUMBER REFERENCES HMS_SERVICE_CATEGORY(CATEGORY_ID),
COMMISSION_TYPE    VARCHAR2(20) CHECK (COMMISSION_TYPE IN ('PERCENT','FIXED')),
COMMISSION_VALUE   NUMBER(12,2) NOT NULL,
EFFECTIVE_FROM     DATE NOT NULL,
EFFECTIVE_TO       DATE
""", comment="Referral / consultation commission setup")

# =====================================================================
# 05 APPOINTMENT
# =====================================================================
m = module(5, "05_appointment_tables.sql", "APPOINTMENT & SCHEDULING")

T(m, "HMS_APPOINTMENT", "APPOINTMENT_ID", """
APPOINTMENT_NO     VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
PATIENT_ID         NUMBER REFERENCES HMS_PATIENT(PATIENT_ID),
PATIENT_NAME       VARCHAR2(200),
MOBILE_NO          VARCHAR2(50),
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
SCHEDULE_ID        NUMBER REFERENCES HMS_DOCTOR_SCHEDULE(SCHEDULE_ID),
APPOINTMENT_DATE   DATE NOT NULL,
SLOT_TIME          VARCHAR2(5),
SERIAL_NO          NUMBER,
BOOKING_SOURCE     VARCHAR2(20) DEFAULT 'COUNTER' CHECK (BOOKING_SOURCE IN ('COUNTER','PHONE','ONLINE','APP')),
APPOINTMENT_STATUS VARCHAR2(20) DEFAULT 'BOOKED' CHECK (APPOINTMENT_STATUS IN ('BOOKED','CONFIRMED','ARRIVED','COMPLETED','CANCELLED','NO_SHOW')),
CANCEL_REASON      VARCHAR2(500),
OPD_VISIT_ID       NUMBER,
REMARKS            VARCHAR2(500)
""", "CONSTRAINT UK_APPOINTMENT_NO UNIQUE (APPOINTMENT_NO)")

T(m, "HMS_COMMUNICATION_LOG", "COMM_ID", """
PATIENT_ID         NUMBER REFERENCES HMS_PATIENT(PATIENT_ID),
CHANNEL            VARCHAR2(20) CHECK (CHANNEL IN ('SMS','EMAIL','WHATSAPP','CALL')),
RECIPIENT          VARCHAR2(200),
MESSAGE_TEXT       VARCHAR2(2000),
REF_TYPE           VARCHAR2(30),
REF_ID             NUMBER,
SEND_STATUS        VARCHAR2(20) DEFAULT 'PENDING' CHECK (SEND_STATUS IN ('PENDING','SENT','FAILED')),
SENT_TIME          TIMESTAMP,
ERROR_MSG          VARCHAR2(1000)
""", active=False)

# =====================================================================
# 06 OPD
# =====================================================================
m = module(6, "06_opd_tables.sql", "OPD (Out Patient Department)")

T(m, "HMS_OPD_VISIT", "VISIT_ID", f"""
VISIT_NO           VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
DEPT_ID            NUMBER NOT NULL REFERENCES HMS_DEPARTMENT(DEPT_ID),
APPOINTMENT_ID     NUMBER REFERENCES HMS_APPOINTMENT(APPOINTMENT_ID),
VISIT_DATE         DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
VISIT_TIME         TIMESTAMP DEFAULT SYSTIMESTAMP,
TOKEN_NO           NUMBER,
VISIT_TYPE         VARCHAR2(20) DEFAULT 'NEW' CHECK (VISIT_TYPE IN ('NEW','FOLLOWUP','REFERRAL','EMERGENCY','REVIEW')),
{yn('IS_FOLLOWUP')},
PREVIOUS_VISIT_ID  NUMBER REFERENCES HMS_OPD_VISIT(VISIT_ID),
CONSULTATION_FEE   NUMBER(12,2) DEFAULT 0,
DISCOUNT_AMOUNT    NUMBER(12,2) DEFAULT 0,
NET_FEE            NUMBER(12,2) DEFAULT 0,
VISIT_STATUS       VARCHAR2(20) DEFAULT 'WAITING' CHECK (VISIT_STATUS IN ('WAITING','IN_CONSULTATION','COMPLETED','CANCELLED','ADMITTED')),
PAYMENT_STATUS     VARCHAR2(20) DEFAULT 'UNPAID' CHECK (PAYMENT_STATUS IN ('UNPAID','PAID','PARTIAL','FREE')),
REMARKS            VARCHAR2(500)
""", "CONSTRAINT UK_OPD_VISIT_NO UNIQUE (VISIT_NO)")

T(m, "HMS_OPD_VITALS", "VITAL_ID", """
VISIT_ID           NUMBER NOT NULL REFERENCES HMS_OPD_VISIT(VISIT_ID),
BP_SYSTOLIC        NUMBER(3),
BP_DIASTOLIC       NUMBER(3),
PULSE_RATE         NUMBER(3),
TEMPERATURE_F      NUMBER(5,2),
RESPIRATORY_RATE   NUMBER(3),
SPO2               NUMBER(3),
WEIGHT_KG          NUMBER(6,2),
HEIGHT_CM          NUMBER(6,2),
BMI                NUMBER(5,2),
BLOOD_SUGAR        NUMBER(6,2),
RECORDED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
RECORDED_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP
""")

T(m, "HMS_OPD_CONSULTATION", "CONSULTATION_ID", f"""
VISIT_ID           NUMBER NOT NULL REFERENCES HMS_OPD_VISIT(VISIT_ID),
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
CHIEF_COMPLAINT    VARCHAR2(2000),
HISTORY_OF_ILLNESS VARCHAR2(4000),
EXAMINATION_NOTES  VARCHAR2(4000),
PROVISIONAL_DIAGNOSIS VARCHAR2(1000),
FINAL_DIAGNOSIS    VARCHAR2(1000),
ICD_ID             NUMBER REFERENCES HMS_ICD_MASTER(ICD_ID),
ADVICE             VARCHAR2(4000),
FOLLOWUP_DATE      DATE,
{yn('ADMISSION_ADVISED')},
REFERRED_TO_DOCTOR_ID NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
CONSULTATION_START TIMESTAMP,
CONSULTATION_END   TIMESTAMP
""")

T(m, "HMS_OPD_PRESCRIPTION", "PRESCRIPTION_ID", """
VISIT_ID           NUMBER NOT NULL REFERENCES HMS_OPD_VISIT(VISIT_ID),
CONSULTATION_ID    NUMBER REFERENCES HMS_OPD_CONSULTATION(CONSULTATION_ID),
PRESCRIPTION_NO    VARCHAR2(30),
PRESCRIPTION_DATE  DATE DEFAULT SYSDATE,
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
NOTES              VARCHAR2(2000)
""")

# PRESCRIPTION_DTL references pharmacy item -> keep ITEM_ID as plain number, FK added in 99 file
T(m, "HMS_OPD_PRESCRIPTION_DTL", "PRESCRIPTION_DTL_ID", """
PRESCRIPTION_ID    NUMBER NOT NULL REFERENCES HMS_OPD_PRESCRIPTION(PRESCRIPTION_ID),
ITEM_ID            NUMBER,
MEDICINE_NAME      VARCHAR2(300) NOT NULL,
DOSAGE             VARCHAR2(100),
FREQUENCY          VARCHAR2(50),
ROUTE              VARCHAR2(50),
DURATION_DAYS      NUMBER,
MEAL_INSTRUCTION   VARCHAR2(50) CHECK (MEAL_INSTRUCTION IN ('BEFORE_MEAL','AFTER_MEAL','WITH_MEAL','EMPTY_STOMACH','ANY')),
QUANTITY           NUMBER,
INSTRUCTIONS       VARCHAR2(500)
""", comment="FREQUENCY e.g. 1+0+1")

T(m, "HMS_OPD_PROCEDURE", "OPD_PROC_ID", """
VISIT_ID           NUMBER NOT NULL REFERENCES HMS_OPD_VISIT(VISIT_ID),
SERVICE_ID         NUMBER NOT NULL REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
PERFORMED_BY       NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
PROCEDURE_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP,
QUANTITY           NUMBER DEFAULT 1,
CHARGE_AMOUNT      NUMBER(12,2),
NOTES              VARCHAR2(1000)
""")

# =====================================================================
# 07 IPD
# =====================================================================
m = module(7, "07_ipd_tables.sql", "IPD (In Patient Department)")

T(m, "HMS_WARD", "WARD_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
DEPT_ID            NUMBER REFERENCES HMS_DEPARTMENT(DEPT_ID),
WARD_CODE          VARCHAR2(20)  NOT NULL,
WARD_NAME          VARCHAR2(200) NOT NULL,
WARD_TYPE          VARCHAR2(30) CHECK (WARD_TYPE IN ('GENERAL','CABIN','ICU','CCU','NICU','PICU','HDU','ISOLATION','MATERNITY','POST_OP','EMERGENCY')),
FLOOR_NO           VARCHAR2(20),
TOTAL_BEDS         NUMBER DEFAULT 0,
GENDER_ALLOWED     VARCHAR2(10) DEFAULT 'ALL' CHECK (GENDER_ALLOWED IN ('MALE','FEMALE','ALL')),
NURSE_STATION_PHONE VARCHAR2(20)
""", "CONSTRAINT UK_WARD UNIQUE (BRANCH_ID, WARD_CODE)")

T(m, "HMS_BED", "BED_ID", """
WARD_ID            NUMBER NOT NULL REFERENCES HMS_WARD(WARD_ID),
BED_NO             VARCHAR2(20) NOT NULL,
BED_TYPE           VARCHAR2(30) CHECK (BED_TYPE IN ('GENERAL','CABIN_AC','CABIN_NON_AC','SUITE','ICU','CCU','NICU','CRADLE')),
SERVICE_ID         NUMBER REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
DAILY_CHARGE       NUMBER(12,2) DEFAULT 0,
BED_STATUS         VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (BED_STATUS IN ('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE','CLEANING'))
""", "CONSTRAINT UK_BED UNIQUE (WARD_ID, BED_NO)")

T(m, "HMS_IPD_ADMISSION", "ADMISSION_ID", f"""
ADMISSION_NO       VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
OPD_VISIT_ID       NUMBER REFERENCES HMS_OPD_VISIT(VISIT_ID),
ADMITTING_DOCTOR_ID NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
CONSULTANT_ID      NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
DEPT_ID            NUMBER NOT NULL REFERENCES HMS_DEPARTMENT(DEPT_ID),
WARD_ID            NUMBER NOT NULL REFERENCES HMS_WARD(WARD_ID),
BED_ID             NUMBER NOT NULL REFERENCES HMS_BED(BED_ID),
ADMISSION_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
ADMISSION_TYPE     VARCHAR2(20) DEFAULT 'PLANNED' CHECK (ADMISSION_TYPE IN ('PLANNED','EMERGENCY','TRANSFER','DAY_CARE','MATERNITY')),
ADMISSION_REASON   VARCHAR2(2000),
PROVISIONAL_DIAGNOSIS VARCHAR2(1000),
ICD_ID             NUMBER REFERENCES HMS_ICD_MASTER(ICD_ID),
{yn('IS_MLC')},
MLC_NO             VARCHAR2(50),
ATTENDANT_NAME     VARCHAR2(200),
ATTENDANT_PHONE    VARCHAR2(50),
ATTENDANT_RELATION VARCHAR2(50),
EXPECTED_STAY_DAYS NUMBER,
INSURANCE_POLICY_ID NUMBER,
ADMISSION_STATUS   VARCHAR2(20) DEFAULT 'ADMITTED' CHECK (ADMISSION_STATUS IN ('ADMITTED','DISCHARGE_INITIATED','DISCHARGED','LAMA','ABSCONDED','DEATH','REFERRED','CANCELLED')),
DISCHARGE_DATE     TIMESTAMP,
REMARKS            VARCHAR2(1000)
""", "CONSTRAINT UK_ADMISSION_NO UNIQUE (ADMISSION_NO)")

T(m, "HMS_BED_TRANSFER", "TRANSFER_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
FROM_BED_ID        NUMBER NOT NULL REFERENCES HMS_BED(BED_ID),
TO_BED_ID          NUMBER NOT NULL REFERENCES HMS_BED(BED_ID),
TRANSFER_DATE      TIMESTAMP DEFAULT SYSTIMESTAMP,
TRANSFER_REASON    VARCHAR2(500),
AUTHORIZED_BY      NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""")

T(m, "HMS_IPD_DOCTOR_VISIT", "IPD_VISIT_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
VISIT_TIME         TIMESTAMP DEFAULT SYSTIMESTAMP,
VISIT_TYPE         VARCHAR2(20) DEFAULT 'ROUTINE' CHECK (VISIT_TYPE IN ('ROUTINE','CALL','EMERGENCY','CONSULTANT')),
PROGRESS_NOTES     VARCHAR2(4000),
INSTRUCTIONS       VARCHAR2(2000),
VISIT_CHARGE       NUMBER(12,2) DEFAULT 0
""")

T(m, "HMS_IPD_MEDICATION", "MEDICATION_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
ITEM_ID            NUMBER,
MEDICINE_NAME      VARCHAR2(300) NOT NULL,
DOSAGE             VARCHAR2(100),
ROUTE              VARCHAR2(50),
FREQUENCY          VARCHAR2(50),
START_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP,
END_DATE           TIMESTAMP,
ORDERED_BY         NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
ORDER_STATUS       VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (ORDER_STATUS IN ('ACTIVE','STOPPED','COMPLETED','HOLD')),
INSTRUCTIONS       VARCHAR2(500)
""", comment="Doctor medication order (chart)")

T(m, "HMS_IPD_MED_ADMINISTRATION", "ADMIN_ID", """
MEDICATION_ID      NUMBER NOT NULL REFERENCES HMS_IPD_MEDICATION(MEDICATION_ID),
SCHEDULED_TIME     TIMESTAMP,
GIVEN_TIME         TIMESTAMP,
GIVEN_BY           NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
ADMIN_STATUS       VARCHAR2(20) DEFAULT 'PENDING' CHECK (ADMIN_STATUS IN ('PENDING','GIVEN','MISSED','REFUSED','HELD')),
NOTES              VARCHAR2(500)
""", comment="Nurse medication administration record (MAR)")

T(m, "HMS_DISCHARGE_SUMMARY", "SUMMARY_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
DISCHARGE_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP,
DISCHARGE_TYPE     VARCHAR2(20) CHECK (DISCHARGE_TYPE IN ('NORMAL','LAMA','REFERRED','DEATH','ABSCONDED','DOR')),
FINAL_DIAGNOSIS    VARCHAR2(2000),
ICD_ID             NUMBER REFERENCES HMS_ICD_MASTER(ICD_ID),
TREATMENT_GIVEN    CLOB,
PROCEDURES_DONE    VARCHAR2(2000),
CONDITION_AT_DISCHARGE VARCHAR2(500),
DISCHARGE_ADVICE   CLOB,
DISCHARGE_MEDICATION CLOB,
FOLLOWUP_DATE      DATE,
DISCHARGED_BY      NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
SUMMARY_STATUS     VARCHAR2(20) DEFAULT 'DRAFT' CHECK (SUMMARY_STATUS IN ('DRAFT','FINAL'))
""", "CONSTRAINT UK_DIS_SUMMARY UNIQUE (ADMISSION_ID)")

# =====================================================================
# 08 DIAGNOSTIC + LAB
# =====================================================================
m = module(8, "08_lab_tables.sql", "DIAGNOSTIC & LABORATORY")

T(m, "HMS_INVESTIGATION_ORDER", "ORDER_ID", """
ORDER_NO           VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
OPD_VISIT_ID       NUMBER REFERENCES HMS_OPD_VISIT(VISIT_ID),
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
ORDER_SOURCE       VARCHAR2(20) CHECK (ORDER_SOURCE IN ('OPD','IPD','EMERGENCY','EXTERNAL')),
REFERRED_DOCTOR_ID NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
ORDER_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP,
PRIORITY           VARCHAR2(20) DEFAULT 'ROUTINE' CHECK (PRIORITY IN ('ROUTINE','URGENT','STAT')),
CLINICAL_NOTES     VARCHAR2(2000),
ORDER_STATUS       VARCHAR2(20) DEFAULT 'ORDERED' CHECK (ORDER_STATUS IN ('ORDERED','PARTIAL','COMPLETED','CANCELLED')),
TOTAL_AMOUNT       NUMBER(12,2) DEFAULT 0,
DISCOUNT_AMOUNT    NUMBER(12,2) DEFAULT 0,
NET_AMOUNT         NUMBER(12,2) DEFAULT 0,
PAYMENT_STATUS     VARCHAR2(20) DEFAULT 'PENDING' CHECK (PAYMENT_STATUS IN ('PENDING','PAID','PARTIAL','CREDIT')),
REMARKS            VARCHAR2(500)
""", "CONSTRAINT UK_INV_ORDER_NO UNIQUE (ORDER_NO)")

T(m, "HMS_INVESTIGATION_ORDER_DTL", "ORDER_DTL_ID", """
ORDER_ID           NUMBER NOT NULL REFERENCES HMS_INVESTIGATION_ORDER(ORDER_ID),
SERVICE_ID         NUMBER NOT NULL REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
SERVICE_NAME       VARCHAR2(300),
CHARGE_AMOUNT      NUMBER(12,2) DEFAULT 0,
DISCOUNT_AMOUNT    NUMBER(12,2) DEFAULT 0,
NET_AMOUNT         NUMBER(12,2) DEFAULT 0,
ITEM_STATUS        VARCHAR2(20) DEFAULT 'ORDERED' CHECK (ITEM_STATUS IN ('ORDERED','SAMPLE_COLLECTED','IN_PROCESS','RESULT_ENTERED','VERIFIED','DELIVERED','CANCELLED')),
REPORTED_DATE      TIMESTAMP,
REPORTED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
VERIFIED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
VERIFIED_DATE      TIMESTAMP
""")

T(m, "HMS_LAB_PARAMETER", "PARAMETER_ID", f"""
SERVICE_ID         NUMBER NOT NULL REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
PARAMETER_CODE     VARCHAR2(30),
PARAMETER_NAME     VARCHAR2(200) NOT NULL,
UNIT               VARCHAR2(50),
RESULT_TYPE        VARCHAR2(20) DEFAULT 'NUMERIC' CHECK (RESULT_TYPE IN ('NUMERIC','TEXT','OPTION','MEMO')),
METHOD_NAME        VARCHAR2(200),
GROUP_NAME         VARCHAR2(100),
DISPLAY_ORDER      NUMBER,
{yn('IS_CALCULATED')},
FORMULA            VARCHAR2(500)
""")

T(m, "HMS_LAB_REFERENCE_RANGE", "RANGE_ID", """
PARAMETER_ID       NUMBER NOT NULL REFERENCES HMS_LAB_PARAMETER(PARAMETER_ID),
GENDER             VARCHAR2(10) DEFAULT 'ALL' CHECK (GENDER IN ('MALE','FEMALE','ALL')),
AGE_FROM_DAYS      NUMBER DEFAULT 0,
AGE_TO_DAYS        NUMBER DEFAULT 54750,
MIN_VALUE          NUMBER,
MAX_VALUE          NUMBER,
CRITICAL_LOW       NUMBER,
CRITICAL_HIGH      NUMBER,
NORMAL_TEXT        VARCHAR2(500)
""")

T(m, "HMS_LAB_SAMPLE", "SAMPLE_ID", """
SAMPLE_NO          VARCHAR2(30) NOT NULL,
ORDER_ID           NUMBER NOT NULL REFERENCES HMS_INVESTIGATION_ORDER(ORDER_ID),
ORDER_DTL_ID       NUMBER REFERENCES HMS_INVESTIGATION_ORDER_DTL(ORDER_DTL_ID),
SAMPLE_TYPE        VARCHAR2(50),
CONTAINER_TYPE     VARCHAR2(50),
COLLECTED_BY       NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
COLLECTION_TIME    TIMESTAMP,
RECEIVED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
RECEIVED_TIME      TIMESTAMP,
SAMPLE_STATUS      VARCHAR2(20) DEFAULT 'PENDING' CHECK (SAMPLE_STATUS IN ('PENDING','COLLECTED','RECEIVED','REJECTED','PROCESSED')),
REJECTION_REASON   VARCHAR2(500)
""", "CONSTRAINT UK_SAMPLE_NO UNIQUE (SAMPLE_NO)", comment="Barcode = SAMPLE_NO")

T(m, "HMS_LAB_EQUIPMENT", "EQUIPMENT_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
EQUIPMENT_CODE     VARCHAR2(30) NOT NULL,
EQUIPMENT_NAME     VARCHAR2(200) NOT NULL,
MANUFACTURER       VARCHAR2(200),
MODEL_NO           VARCHAR2(100),
SERIAL_NO          VARCHAR2(100),
INTERFACE_TYPE     VARCHAR2(30),
LAST_CALIBRATION   DATE,
NEXT_CALIBRATION   DATE
""", "CONSTRAINT UK_LAB_EQUIP UNIQUE (EQUIPMENT_CODE)")

T(m, "HMS_LAB_RESULT", "RESULT_ID", f"""
ORDER_DTL_ID       NUMBER NOT NULL REFERENCES HMS_INVESTIGATION_ORDER_DTL(ORDER_DTL_ID),
SAMPLE_ID          NUMBER REFERENCES HMS_LAB_SAMPLE(SAMPLE_ID),
PARAMETER_ID       NUMBER NOT NULL REFERENCES HMS_LAB_PARAMETER(PARAMETER_ID),
EQUIPMENT_ID       NUMBER REFERENCES HMS_LAB_EQUIPMENT(EQUIPMENT_ID),
RESULT_VALUE       VARCHAR2(1000),
RESULT_NUMERIC     NUMBER,
UNIT               VARCHAR2(50),
REFERENCE_RANGE    VARCHAR2(200),
{yn('IS_ABNORMAL')},
{yn('IS_CRITICAL')},
RESULT_FLAG        VARCHAR2(10) CHECK (RESULT_FLAG IN ('L','H','LL','HH','N')),
ENTERED_BY         NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
ENTERED_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
VERIFIED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
VERIFIED_TIME      TIMESTAMP,
RESULT_STATUS      VARCHAR2(20) DEFAULT 'ENTERED' CHECK (RESULT_STATUS IN ('ENTERED','VERIFIED','AMENDED'))
""", "CONSTRAINT UK_LAB_RESULT UNIQUE (ORDER_DTL_ID, PARAMETER_ID)")

T(m, "HMS_LAB_RESULT_AMENDMENT", "AMENDMENT_ID", """
RESULT_ID          NUMBER NOT NULL REFERENCES HMS_LAB_RESULT(RESULT_ID),
OLD_VALUE          VARCHAR2(1000),
NEW_VALUE          VARCHAR2(1000),
AMEND_REASON       VARCHAR2(500) NOT NULL,
AMENDED_BY         NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
AMENDED_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP
""", active=False)

# =====================================================================
# 09 RADIOLOGY
# =====================================================================
m = module(9, "09_radiology_tables.sql", "RADIOLOGY / IMAGING")

T(m, "HMS_RADIOLOGY_ORDER", "RAD_ORDER_ID", """
ORDER_DTL_ID       NUMBER NOT NULL REFERENCES HMS_INVESTIGATION_ORDER_DTL(ORDER_DTL_ID),
MODALITY           VARCHAR2(20) CHECK (MODALITY IN ('XRAY','USG','CT','MRI','ECG','ECHO','MAMMO','ENDOSCOPY','OTHER')),
BODY_PART          VARCHAR2(100),
SCHEDULED_TIME     TIMESTAMP,
PERFORMED_TIME     TIMESTAMP,
TECHNICIAN_ID      NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
RADIOLOGIST_ID     NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
FINDINGS           CLOB,
IMPRESSION         VARCHAR2(4000),
REPORT_STATUS      VARCHAR2(20) DEFAULT 'PENDING' CHECK (REPORT_STATUS IN ('PENDING','SCANNED','DRAFT','FINAL','DELIVERED')),
PACS_STUDY_UID     VARCHAR2(200)
""")

T(m, "HMS_RADIOLOGY_IMAGE", "IMAGE_ID", """
RAD_ORDER_ID       NUMBER NOT NULL REFERENCES HMS_RADIOLOGY_ORDER(RAD_ORDER_ID),
IMAGE_FILE         BLOB,
FILE_NAME          VARCHAR2(300),
MIME_TYPE          VARCHAR2(100),
IMAGE_DESC         VARCHAR2(500)
""")

T(m, "HMS_REPORT_TEMPLATE", "TEMPLATE_ID", """
SERVICE_ID         NUMBER REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
TEMPLATE_NAME      VARCHAR2(200) NOT NULL,
TEMPLATE_BODY      CLOB
""", comment="Radiology / USG report template")

# =====================================================================
# 10 PHARMACY
# =====================================================================
m = module(10, "10_pharmacy_tables.sql", "PHARMACY")

T(m, "HMS_PHARMA_CATEGORY", "PH_CATEGORY_ID", """
CATEGORY_NAME      VARCHAR2(200) NOT NULL,
PARENT_ID          NUMBER REFERENCES HMS_PHARMA_CATEGORY(PH_CATEGORY_ID)
""", comment="Tablet, Capsule, Syrup, Injection ...")

T(m, "HMS_PHARMA_GENERIC", "GENERIC_ID", """
GENERIC_NAME       VARCHAR2(300) NOT NULL,
DRUG_CLASS         VARCHAR2(200),
INDICATIONS        VARCHAR2(2000),
CONTRAINDICATIONS  VARCHAR2(2000)
""", "CONSTRAINT UK_GENERIC UNIQUE (GENERIC_NAME)")

T(m, "HMS_PHARMA_MANUFACTURER", "MANUFACTURER_ID", """
MANUFACTURER_NAME  VARCHAR2(300) NOT NULL,
COUNTRY            VARCHAR2(100) DEFAULT 'Bangladesh',
CONTACT_PERSON     VARCHAR2(200),
PHONE              VARCHAR2(50)
""", "CONSTRAINT UK_MANUFACTURER UNIQUE (MANUFACTURER_NAME)")

T(m, "HMS_PHARMA_ITEM", "ITEM_ID", f"""
ITEM_CODE          VARCHAR2(30)  NOT NULL,
ITEM_NAME          VARCHAR2(300) NOT NULL,
GENERIC_ID         NUMBER REFERENCES HMS_PHARMA_GENERIC(GENERIC_ID),
PH_CATEGORY_ID     NUMBER REFERENCES HMS_PHARMA_CATEGORY(PH_CATEGORY_ID),
MANUFACTURER_ID    NUMBER REFERENCES HMS_PHARMA_MANUFACTURER(MANUFACTURER_ID),
STRENGTH           VARCHAR2(100),
DOSAGE_FORM        VARCHAR2(50),
UNIT_OF_MEASURE    VARCHAR2(30),
PACK_SIZE          NUMBER DEFAULT 1,
PURCHASE_PRICE     NUMBER(12,2),
MRP                NUMBER(12,2),
VAT_PERCENT        NUMBER(5,2) DEFAULT 0,
REORDER_LEVEL      NUMBER DEFAULT 0,
BARCODE            VARCHAR2(100),
RACK_NO            VARCHAR2(30),
{yn('IS_NARCOTIC')},
{yn('IS_ANTIBIOTIC')},
{yn('REQUIRES_PRESCRIPTION','Y')}
""", "CONSTRAINT UK_ITEM_CODE UNIQUE (ITEM_CODE)")

T(m, "HMS_PHARMA_SUPPLIER", "SUPPLIER_ID", """
SUPPLIER_CODE      VARCHAR2(30)  NOT NULL,
SUPPLIER_NAME      VARCHAR2(300) NOT NULL,
CONTACT_PERSON     VARCHAR2(200),
PHONE              VARCHAR2(50),
EMAIL              VARCHAR2(150),
ADDRESS            VARCHAR2(500),
TRADE_LICENSE      VARCHAR2(100),
DRUG_LICENSE       VARCHAR2(100),
CREDIT_DAYS        NUMBER DEFAULT 0,
OPENING_BALANCE    NUMBER(14,2) DEFAULT 0
""", "CONSTRAINT UK_SUPPLIER_CODE UNIQUE (SUPPLIER_CODE)")

T(m, "HMS_PHARMA_STORE", "STORE_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
STORE_CODE         VARCHAR2(30) NOT NULL,
STORE_NAME         VARCHAR2(200) NOT NULL,
STORE_TYPE         VARCHAR2(20) CHECK (STORE_TYPE IN ('MAIN','OPD','IPD','OT','EMERGENCY','WARD'))
""", "CONSTRAINT UK_PH_STORE UNIQUE (STORE_CODE)")

T(m, "HMS_PHARMA_PURCHASE_ORDER", "PO_ID", """
PO_NO              VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
SUPPLIER_ID        NUMBER NOT NULL REFERENCES HMS_PHARMA_SUPPLIER(SUPPLIER_ID),
PO_DATE            DATE DEFAULT SYSDATE,
EXPECTED_DATE      DATE,
TOTAL_AMOUNT       NUMBER(14,2) DEFAULT 0,
PO_STATUS          VARCHAR2(20) DEFAULT 'DRAFT' CHECK (PO_STATUS IN ('DRAFT','APPROVED','PARTIAL','RECEIVED','CANCELLED')),
APPROVED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
REMARKS            VARCHAR2(500)
""", "CONSTRAINT UK_PO_NO UNIQUE (PO_NO)")

T(m, "HMS_PHARMA_PO_DTL", "PO_DTL_ID", """
PO_ID              NUMBER NOT NULL REFERENCES HMS_PHARMA_PURCHASE_ORDER(PO_ID),
ITEM_ID            NUMBER NOT NULL REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
ORDER_QTY          NUMBER NOT NULL,
RECEIVED_QTY       NUMBER DEFAULT 0,
UNIT_PRICE         NUMBER(12,2),
LINE_TOTAL         NUMBER(14,2)
""")

T(m, "HMS_PHARMA_GRN", "GRN_ID", """
GRN_NO             VARCHAR2(30) NOT NULL,
PO_ID              NUMBER REFERENCES HMS_PHARMA_PURCHASE_ORDER(PO_ID),
SUPPLIER_ID        NUMBER NOT NULL REFERENCES HMS_PHARMA_SUPPLIER(SUPPLIER_ID),
STORE_ID           NUMBER NOT NULL REFERENCES HMS_PHARMA_STORE(STORE_ID),
GRN_DATE           DATE DEFAULT SYSDATE,
INVOICE_NO         VARCHAR2(50),
INVOICE_DATE       DATE,
TOTAL_AMOUNT       NUMBER(14,2) DEFAULT 0,
DISCOUNT_AMOUNT    NUMBER(14,2) DEFAULT 0,
VAT_AMOUNT         NUMBER(14,2) DEFAULT 0,
NET_AMOUNT         NUMBER(14,2) DEFAULT 0,
GRN_STATUS         VARCHAR2(20) DEFAULT 'DRAFT' CHECK (GRN_STATUS IN ('DRAFT','POSTED','CANCELLED'))
""", "CONSTRAINT UK_GRN_NO UNIQUE (GRN_NO)", comment="Goods Receive Note")

T(m, "HMS_PHARMA_GRN_DTL", "GRN_DTL_ID", """
GRN_ID             NUMBER NOT NULL REFERENCES HMS_PHARMA_GRN(GRN_ID),
ITEM_ID            NUMBER NOT NULL REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
BATCH_NO           VARCHAR2(50) NOT NULL,
MFG_DATE           DATE,
EXPIRY_DATE        DATE NOT NULL,
QUANTITY           NUMBER NOT NULL,
FREE_QTY           NUMBER DEFAULT 0,
UNIT_COST          NUMBER(12,2),
MRP                NUMBER(12,2),
LINE_TOTAL         NUMBER(14,2)
""")

T(m, "HMS_PHARMA_STOCK", "STOCK_ID", """
STORE_ID           NUMBER NOT NULL REFERENCES HMS_PHARMA_STORE(STORE_ID),
ITEM_ID            NUMBER NOT NULL REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
BATCH_NO           VARCHAR2(50) NOT NULL,
EXPIRY_DATE        DATE NOT NULL,
QTY_AVAILABLE      NUMBER DEFAULT 0 NOT NULL,
UNIT_COST          NUMBER(12,2),
MRP                NUMBER(12,2)
""", "CONSTRAINT UK_PH_STOCK UNIQUE (STORE_ID, ITEM_ID, BATCH_NO),\n    CONSTRAINT CK_PH_STOCK_QTY CHECK (QTY_AVAILABLE >= 0)")

T(m, "HMS_PHARMA_SALE", "SALE_ID", """
SALE_NO            VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
STORE_ID           NUMBER NOT NULL REFERENCES HMS_PHARMA_STORE(STORE_ID),
PATIENT_ID         NUMBER REFERENCES HMS_PATIENT(PATIENT_ID),
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
PRESCRIPTION_ID    NUMBER REFERENCES HMS_OPD_PRESCRIPTION(PRESCRIPTION_ID),
CUSTOMER_NAME      VARCHAR2(200),
CUSTOMER_PHONE     VARCHAR2(50),
SALE_TYPE          VARCHAR2(20) DEFAULT 'OTC' CHECK (SALE_TYPE IN ('OTC','OPD','IPD','EMERGENCY','OT')),
SALE_DATE          TIMESTAMP DEFAULT SYSTIMESTAMP,
GROSS_AMOUNT       NUMBER(14,2) DEFAULT 0,
DISCOUNT_AMOUNT    NUMBER(14,2) DEFAULT 0,
VAT_AMOUNT         NUMBER(14,2) DEFAULT 0,
NET_AMOUNT         NUMBER(14,2) DEFAULT 0,
PAID_AMOUNT        NUMBER(14,2) DEFAULT 0,
PAYMENT_MODE       VARCHAR2(20),
SALE_STATUS        VARCHAR2(20) DEFAULT 'COMPLETED' CHECK (SALE_STATUS IN ('DRAFT','COMPLETED','CANCELLED','IPD_CREDIT'))
""", "CONSTRAINT UK_SALE_NO UNIQUE (SALE_NO)")

T(m, "HMS_PHARMA_SALE_DTL", "SALE_DTL_ID", """
SALE_ID            NUMBER NOT NULL REFERENCES HMS_PHARMA_SALE(SALE_ID),
ITEM_ID            NUMBER NOT NULL REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
STOCK_ID           NUMBER NOT NULL REFERENCES HMS_PHARMA_STOCK(STOCK_ID),
BATCH_NO           VARCHAR2(50),
QUANTITY           NUMBER NOT NULL CHECK (QUANTITY > 0),
UNIT_PRICE         NUMBER(12,2) NOT NULL,
DISCOUNT_AMOUNT    NUMBER(12,2) DEFAULT 0,
LINE_TOTAL         NUMBER(14,2)
""")

T(m, "HMS_PHARMA_SALE_RETURN", "RETURN_ID", """
RETURN_NO          VARCHAR2(30) NOT NULL,
SALE_ID            NUMBER NOT NULL REFERENCES HMS_PHARMA_SALE(SALE_ID),
SALE_DTL_ID        NUMBER NOT NULL REFERENCES HMS_PHARMA_SALE_DTL(SALE_DTL_ID),
RETURN_QTY         NUMBER NOT NULL CHECK (RETURN_QTY > 0),
REFUND_AMOUNT      NUMBER(12,2),
RETURN_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
RETURN_REASON      VARCHAR2(500)
""", "CONSTRAINT UK_PH_RETURN_NO UNIQUE (RETURN_NO)")

T(m, "HMS_PHARMA_TRANSACTION", "TXN_ID", """
STORE_ID           NUMBER NOT NULL REFERENCES HMS_PHARMA_STORE(STORE_ID),
ITEM_ID            NUMBER NOT NULL REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
STOCK_ID           NUMBER REFERENCES HMS_PHARMA_STOCK(STOCK_ID),
BATCH_NO           VARCHAR2(50),
TXN_TYPE           VARCHAR2(20) NOT NULL CHECK (TXN_TYPE IN ('GRN','SALE','SALE_RETURN','TRANSFER_IN','TRANSFER_OUT','ADJUST_PLUS','ADJUST_MINUS','EXPIRED','DAMAGE','OPENING')),
TXN_QTY            NUMBER NOT NULL,
REF_TYPE           VARCHAR2(30),
REF_ID             NUMBER,
TXN_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP
""", active=False, comment="Stock ledger (sob movement ekhane log hobe)")

# =====================================================================
# 11 OT
# =====================================================================
m = module(11, "11_ot_tables.sql", "OPERATION THEATRE (OT)")

T(m, "HMS_OT_MASTER", "OT_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
OT_CODE            VARCHAR2(20) NOT NULL,
OT_NAME            VARCHAR2(100) NOT NULL,
OT_TYPE            VARCHAR2(30) CHECK (OT_TYPE IN ('MAJOR','MINOR','CARDIAC','NEURO','ORTHO','GYNAE','EMERGENCY')),
FLOOR_NO           VARCHAR2(20),
OT_STATUS          VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (OT_STATUS IN ('AVAILABLE','IN_USE','CLEANING','MAINTENANCE'))
""", "CONSTRAINT UK_OT_CODE UNIQUE (OT_CODE)")

T(m, "HMS_SURGERY_MASTER", "SURGERY_ID", """
SERVICE_ID         NUMBER REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
SURGERY_CODE       VARCHAR2(30) NOT NULL,
SURGERY_NAME       VARCHAR2(300) NOT NULL,
SURGERY_CATEGORY   VARCHAR2(30) CHECK (SURGERY_CATEGORY IN ('MINOR','MAJOR','SUPER_MAJOR')),
EST_DURATION_MIN   NUMBER,
SURGEON_FEE        NUMBER(12,2),
ANESTHESIA_FEE     NUMBER(12,2),
OT_CHARGE          NUMBER(12,2)
""", "CONSTRAINT UK_SURGERY_CODE UNIQUE (SURGERY_CODE)")

T(m, "HMS_OT_BOOKING", "BOOKING_ID", """
BOOKING_NO         VARCHAR2(30) NOT NULL,
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
OT_ID              NUMBER NOT NULL REFERENCES HMS_OT_MASTER(OT_ID),
SURGERY_ID         NUMBER NOT NULL REFERENCES HMS_SURGERY_MASTER(SURGERY_ID),
PRIMARY_SURGEON_ID NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
ANESTHETIST_ID     NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
ANESTHESIA_TYPE    VARCHAR2(30) CHECK (ANESTHESIA_TYPE IN ('GENERAL','SPINAL','EPIDURAL','LOCAL','REGIONAL','SEDATION')),
SCHEDULED_START    TIMESTAMP NOT NULL,
SCHEDULED_END      TIMESTAMP,
ACTUAL_START       TIMESTAMP,
ACTUAL_END         TIMESTAMP,
PRIORITY           VARCHAR2(20) DEFAULT 'ELECTIVE' CHECK (PRIORITY IN ('ELECTIVE','URGENT','EMERGENCY')),
PRE_OP_DIAGNOSIS   VARCHAR2(1000),
BOOKING_STATUS     VARCHAR2(20) DEFAULT 'SCHEDULED' CHECK (BOOKING_STATUS IN ('SCHEDULED','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','POSTPONED')),
CONSENT_TAKEN      CHAR(1) DEFAULT 'N' CHECK (CONSENT_TAKEN IN ('Y','N'))
""", "CONSTRAINT UK_OT_BOOKING_NO UNIQUE (BOOKING_NO)")

T(m, "HMS_OT_TEAM", "TEAM_ID", """
BOOKING_ID         NUMBER NOT NULL REFERENCES HMS_OT_BOOKING(BOOKING_ID),
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
TEAM_ROLE          VARCHAR2(30) CHECK (TEAM_ROLE IN ('SURGEON','ASSISTANT_SURGEON','ANESTHETIST','SCRUB_NURSE','CIRCULATING_NURSE','TECHNICIAN')),
FEE_AMOUNT         NUMBER(12,2) DEFAULT 0
""", "CONSTRAINT UK_OT_TEAM UNIQUE (BOOKING_ID, EMPLOYEE_ID, TEAM_ROLE)")

T(m, "HMS_OT_NOTES", "OT_NOTE_ID", """
BOOKING_ID         NUMBER NOT NULL REFERENCES HMS_OT_BOOKING(BOOKING_ID),
POST_OP_DIAGNOSIS  VARCHAR2(1000),
PROCEDURE_DETAILS  CLOB,
FINDINGS           VARCHAR2(4000),
COMPLICATIONS      VARCHAR2(2000),
BLOOD_LOSS_ML      NUMBER,
SPECIMEN_SENT      VARCHAR2(500),
POST_OP_INSTRUCTIONS VARCHAR2(4000),
WRITTEN_BY         NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID)
""")

T(m, "HMS_OT_CONSUMABLE", "CONSUMABLE_ID", """
BOOKING_ID         NUMBER NOT NULL REFERENCES HMS_OT_BOOKING(BOOKING_ID),
ITEM_ID            NUMBER NOT NULL REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
STOCK_ID           NUMBER REFERENCES HMS_PHARMA_STOCK(STOCK_ID),
QUANTITY           NUMBER NOT NULL,
UNIT_PRICE         NUMBER(12,2),
LINE_TOTAL         NUMBER(14,2)
""")

# =====================================================================
# 12 BLOOD BANK
# =====================================================================
m = module(12, "12_blood_bank_tables.sql", "BLOOD BANK")

T(m, "HMS_BLOOD_DONOR", "DONOR_ID", """
DONOR_CODE         VARCHAR2(30) NOT NULL,
DONOR_NAME         VARCHAR2(200) NOT NULL,
GENDER             VARCHAR2(10) CHECK (GENDER IN ('MALE','FEMALE','OTHER')),
DATE_OF_BIRTH      DATE,
BLOOD_GROUP        VARCHAR2(5) NOT NULL,
PHONE              VARCHAR2(50),
ADDRESS            VARCHAR2(500),
WEIGHT_KG          NUMBER(5,2),
LAST_DONATION_DATE DATE,
DONOR_TYPE         VARCHAR2(20) CHECK (DONOR_TYPE IN ('VOLUNTARY','REPLACEMENT','PAID','AUTOLOGOUS')),
IS_DEFERRED        CHAR(1) DEFAULT 'N' CHECK (IS_DEFERRED IN ('Y','N')),
DEFER_REASON       VARCHAR2(500)
""", "CONSTRAINT UK_DONOR_CODE UNIQUE (DONOR_CODE)")

T(m, "HMS_BLOOD_COLLECTION", "COLLECTION_ID", """
DONOR_ID           NUMBER NOT NULL REFERENCES HMS_BLOOD_DONOR(DONOR_ID),
BAG_NO             VARCHAR2(30) NOT NULL,
COLLECTION_DATE    TIMESTAMP DEFAULT SYSTIMESTAMP,
BAG_TYPE           VARCHAR2(20) CHECK (BAG_TYPE IN ('SINGLE','DOUBLE','TRIPLE','QUADRUPLE')),
VOLUME_ML          NUMBER DEFAULT 450,
HB_LEVEL           NUMBER(4,1),
SCREENING_STATUS   VARCHAR2(20) DEFAULT 'PENDING' CHECK (SCREENING_STATUS IN ('PENDING','PASSED','FAILED')),
HIV_RESULT         VARCHAR2(10),
HBSAG_RESULT       VARCHAR2(10),
HCV_RESULT         VARCHAR2(10),
VDRL_RESULT        VARCHAR2(10),
MALARIA_RESULT     VARCHAR2(10),
COLLECTED_BY       NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""", "CONSTRAINT UK_BAG_NO UNIQUE (BAG_NO)")

T(m, "HMS_BLOOD_INVENTORY", "BLOOD_STOCK_ID", """
COLLECTION_ID      NUMBER NOT NULL REFERENCES HMS_BLOOD_COLLECTION(COLLECTION_ID),
COMPONENT_TYPE     VARCHAR2(20) NOT NULL CHECK (COMPONENT_TYPE IN ('WHOLE_BLOOD','PRBC','FFP','PLATELET','CRYO')),
BLOOD_GROUP        VARCHAR2(5) NOT NULL,
VOLUME_ML          NUMBER,
EXPIRY_DATE        TIMESTAMP NOT NULL,
STORAGE_LOCATION   VARCHAR2(50),
UNIT_STATUS        VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (UNIT_STATUS IN ('QUARANTINE','AVAILABLE','RESERVED','ISSUED','EXPIRED','DISCARDED'))
""")

T(m, "HMS_BLOOD_REQUISITION", "REQUISITION_ID", """
REQUISITION_NO     VARCHAR2(30) NOT NULL,
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
REQUESTED_BY       NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
BLOOD_GROUP        VARCHAR2(5) NOT NULL,
COMPONENT_TYPE     VARCHAR2(20),
UNITS_REQUIRED     NUMBER DEFAULT 1,
PRIORITY           VARCHAR2(20) DEFAULT 'ROUTINE' CHECK (PRIORITY IN ('ROUTINE','URGENT','EMERGENCY')),
REQUIRED_DATE      TIMESTAMP,
REQ_STATUS         VARCHAR2(20) DEFAULT 'PENDING' CHECK (REQ_STATUS IN ('PENDING','CROSSMATCHED','PARTIAL','ISSUED','CANCELLED'))
""", "CONSTRAINT UK_BLOOD_REQ_NO UNIQUE (REQUISITION_NO)")

T(m, "HMS_BLOOD_CROSSMATCH", "CROSSMATCH_ID", """
REQUISITION_ID     NUMBER NOT NULL REFERENCES HMS_BLOOD_REQUISITION(REQUISITION_ID),
BLOOD_STOCK_ID     NUMBER NOT NULL REFERENCES HMS_BLOOD_INVENTORY(BLOOD_STOCK_ID),
CROSSMATCH_RESULT  VARCHAR2(20) CHECK (CROSSMATCH_RESULT IN ('COMPATIBLE','INCOMPATIBLE')),
TESTED_BY          NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
TESTED_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP
""")

T(m, "HMS_BLOOD_ISSUE", "ISSUE_ID", """
REQUISITION_ID     NUMBER NOT NULL REFERENCES HMS_BLOOD_REQUISITION(REQUISITION_ID),
BLOOD_STOCK_ID     NUMBER NOT NULL REFERENCES HMS_BLOOD_INVENTORY(BLOOD_STOCK_ID),
ISSUE_TIME         TIMESTAMP DEFAULT SYSTIMESTAMP,
ISSUED_BY          NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
RECEIVED_BY_NAME   VARCHAR2(200),
CHARGE_AMOUNT      NUMBER(12,2),
TRANSFUSION_REACTION VARCHAR2(1000)
""", "CONSTRAINT UK_BLOOD_ISSUE UNIQUE (BLOOD_STOCK_ID)")

# =====================================================================
# 13 NURSING
# =====================================================================
m = module(13, "13_nursing_tables.sql", "NURSING")

T(m, "HMS_NURSING_ASSESSMENT", "ASSESSMENT_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
ASSESSMENT_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSCIOUSNESS      VARCHAR2(50),
PAIN_SCORE         NUMBER(2) CHECK (PAIN_SCORE BETWEEN 0 AND 10),
FALL_RISK_SCORE    NUMBER,
BRADEN_SCORE       NUMBER,
GCS_SCORE          NUMBER(2),
NOTES              VARCHAR2(2000),
NURSE_ID           NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""")

T(m, "HMS_IPD_VITALS", "IPD_VITAL_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
RECORDED_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
BP_SYSTOLIC        NUMBER(3),
BP_DIASTOLIC       NUMBER(3),
PULSE_RATE         NUMBER(3),
TEMPERATURE_F      NUMBER(5,2),
RESPIRATORY_RATE   NUMBER(3),
SPO2               NUMBER(3),
BLOOD_SUGAR        NUMBER(6,2),
INTAKE_ML          NUMBER,
OUTPUT_ML          NUMBER,
RECORDED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""")

T(m, "HMS_NURSING_CARE_PLAN", "CARE_PLAN_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
NURSING_DIAGNOSIS  VARCHAR2(1000),
GOAL               VARCHAR2(1000),
INTERVENTIONS      VARCHAR2(4000),
EVALUATION         VARCHAR2(2000),
PLAN_STATUS        VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (PLAN_STATUS IN ('ACTIVE','ACHIEVED','REVISED','CLOSED')),
NURSE_ID           NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""")

T(m, "HMS_NURSING_NOTES", "NOTE_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
NOTE_TIME          TIMESTAMP DEFAULT SYSTIMESTAMP,
SHIFT_ID           NUMBER REFERENCES HMS_SHIFT_MASTER(SHIFT_ID),
NOTE_TEXT          VARCHAR2(4000) NOT NULL,
NURSE_ID           NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""")

# =====================================================================
# 14 DIET
# =====================================================================
m = module(14, "14_diet_tables.sql", "DIET / KITCHEN")

T(m, "HMS_DIET_MASTER", "DIET_ID", """
DIET_CODE          VARCHAR2(30) NOT NULL,
DIET_NAME          VARCHAR2(200) NOT NULL,
DIET_TYPE          VARCHAR2(30) CHECK (DIET_TYPE IN ('NORMAL','DIABETIC','LIQUID','SOFT','SALT_FREE','RENAL','CARDIAC','HIGH_PROTEIN','NPO')),
CALORIES           NUMBER,
DIET_DESC          VARCHAR2(1000),
RATE_PER_DAY       NUMBER(12,2) DEFAULT 0
""", "CONSTRAINT UK_DIET_CODE UNIQUE (DIET_CODE)")

T(m, "HMS_DIET_ORDER", "DIET_ORDER_ID", """
ADMISSION_ID       NUMBER NOT NULL REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
DIET_ID            NUMBER NOT NULL REFERENCES HMS_DIET_MASTER(DIET_ID),
ORDERED_BY         NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
START_DATE         DATE DEFAULT SYSDATE,
END_DATE           DATE,
SPECIAL_INSTRUCTIONS VARCHAR2(1000),
ORDER_STATUS       VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (ORDER_STATUS IN ('ACTIVE','STOPPED','COMPLETED'))
""")

T(m, "HMS_DIET_SERVING", "SERVING_ID", """
DIET_ORDER_ID      NUMBER NOT NULL REFERENCES HMS_DIET_ORDER(DIET_ORDER_ID),
SERVING_DATE       DATE DEFAULT TRUNC(SYSDATE),
MEAL_TYPE          VARCHAR2(20) CHECK (MEAL_TYPE IN ('BREAKFAST','LUNCH','SNACKS','DINNER')),
SERVED_TIME        TIMESTAMP,
SERVED_BY          NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
SERVING_STATUS     VARCHAR2(20) DEFAULT 'PENDING' CHECK (SERVING_STATUS IN ('PENDING','SERVED','REFUSED','SKIPPED'))
""")

# =====================================================================
# 15 INSURANCE / TPA
# =====================================================================
m = module(15, "15_insurance_tables.sql", "INSURANCE / TPA / CORPORATE")

T(m, "HMS_INSURANCE_COMPANY", "INS_COMPANY_ID", """
COMPANY_CODE       VARCHAR2(30) NOT NULL,
COMPANY_NAME       VARCHAR2(300) NOT NULL,
COMPANY_TYPE       VARCHAR2(20) CHECK (COMPANY_TYPE IN ('INSURANCE','TPA','CORPORATE','GOVT')),
CONTACT_PERSON     VARCHAR2(200),
PHONE              VARCHAR2(50),
EMAIL              VARCHAR2(150),
ADDRESS            VARCHAR2(500),
CREDIT_LIMIT       NUMBER(14,2),
DISCOUNT_PERCENT   NUMBER(5,2) DEFAULT 0
""", "CONSTRAINT UK_INS_COMPANY UNIQUE (COMPANY_CODE)")

T(m, "HMS_INSURANCE_PLAN", "PLAN_ID", """
INS_COMPANY_ID     NUMBER NOT NULL REFERENCES HMS_INSURANCE_COMPANY(INS_COMPANY_ID),
PLAN_NAME          VARCHAR2(200) NOT NULL,
COVERAGE_LIMIT     NUMBER(14,2),
ROOM_RENT_LIMIT    NUMBER(12,2),
CO_PAY_PERCENT     NUMBER(5,2) DEFAULT 0,
COVERAGE_DETAILS   VARCHAR2(4000)
""")

T(m, "HMS_PATIENT_INSURANCE", "POLICY_ID", """
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
PLAN_ID            NUMBER NOT NULL REFERENCES HMS_INSURANCE_PLAN(PLAN_ID),
POLICY_NO          VARCHAR2(100) NOT NULL,
MEMBER_ID          VARCHAR2(100),
POLICY_HOLDER_NAME VARCHAR2(200),
RELATION_TO_HOLDER VARCHAR2(50),
VALID_FROM         DATE,
VALID_TO           DATE
""")

T(m, "HMS_INSURANCE_PREAUTH", "PREAUTH_ID", """
POLICY_ID          NUMBER NOT NULL REFERENCES HMS_PATIENT_INSURANCE(POLICY_ID),
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
REQUEST_DATE       DATE DEFAULT SYSDATE,
REQUESTED_AMOUNT   NUMBER(14,2),
APPROVED_AMOUNT    NUMBER(14,2),
APPROVAL_REF_NO    VARCHAR2(100),
PREAUTH_STATUS     VARCHAR2(20) DEFAULT 'PENDING' CHECK (PREAUTH_STATUS IN ('PENDING','APPROVED','PARTIAL','REJECTED'))
""")

# claims -> reference billing, created in billing file

# =====================================================================
# 16 ACCOUNTS & BILLING
# =====================================================================
m = module(16, "16_billing_accounts_tables.sql", "ACCOUNT & BILLING")

T(m, "HMS_BILLING", "BILL_ID", """
BILL_NO            VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
BILL_TYPE          VARCHAR2(20) NOT NULL CHECK (BILL_TYPE IN ('OPD','IPD','LAB','PHARMACY','EMERGENCY','OT','PACKAGE','MISC')),
OPD_VISIT_ID       NUMBER REFERENCES HMS_OPD_VISIT(VISIT_ID),
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
POLICY_ID          NUMBER REFERENCES HMS_PATIENT_INSURANCE(POLICY_ID),
BILL_DATE          TIMESTAMP DEFAULT SYSTIMESTAMP,
GROSS_AMOUNT       NUMBER(14,2) DEFAULT 0,
HEADER_DISCOUNT    NUMBER(14,2) DEFAULT 0,
DISCOUNT_AMOUNT    NUMBER(14,2) DEFAULT 0,
DISCOUNT_REASON    VARCHAR2(500),
DISCOUNT_APPROVED_BY NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
VAT_AMOUNT         NUMBER(14,2) DEFAULT 0,
NET_AMOUNT         NUMBER(14,2) DEFAULT 0,
INSURANCE_AMOUNT   NUMBER(14,2) DEFAULT 0,
PATIENT_PAYABLE    NUMBER(14,2) DEFAULT 0,
PAID_AMOUNT        NUMBER(14,2) DEFAULT 0,
DUE_AMOUNT         NUMBER(14,2) DEFAULT 0,
BILL_STATUS        VARCHAR2(20) DEFAULT 'OPEN' CHECK (BILL_STATUS IN ('DRAFT','OPEN','PARTIAL','PAID','CANCELLED','REFUNDED')),
CANCEL_REASON      VARCHAR2(500),
REMARKS            VARCHAR2(500)
""", "CONSTRAINT UK_BILL_NO UNIQUE (BILL_NO)")

T(m, "HMS_BILLING_DTL", "BILL_DTL_ID", """
BILL_ID            NUMBER NOT NULL REFERENCES HMS_BILLING(BILL_ID),
SERVICE_ID         NUMBER REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
ITEM_DESC          VARCHAR2(300) NOT NULL,
REF_TYPE           VARCHAR2(30),
REF_ID             NUMBER,
SERVICE_DATE       DATE DEFAULT SYSDATE,
DOCTOR_ID          NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
QUANTITY           NUMBER DEFAULT 1,
UNIT_PRICE         NUMBER(12,2) DEFAULT 0,
GROSS_AMOUNT       NUMBER(14,2) DEFAULT 0,
DISCOUNT_AMOUNT    NUMBER(14,2) DEFAULT 0,
VAT_AMOUNT         NUMBER(14,2) DEFAULT 0,
NET_AMOUNT         NUMBER(14,2) DEFAULT 0
""", comment="REF_TYPE = LAB_ORDER_DTL / PHARMA_SALE / BED / OT_BOOKING ...")

T(m, "HMS_PATIENT_ADVANCE", "ADVANCE_ID", """
ADVANCE_NO         VARCHAR2(30) NOT NULL,
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
ADVANCE_DATE       TIMESTAMP DEFAULT SYSTIMESTAMP,
AMOUNT             NUMBER(14,2) NOT NULL CHECK (AMOUNT > 0),
ADJUSTED_AMOUNT    NUMBER(14,2) DEFAULT 0,
REFUNDED_AMOUNT    NUMBER(14,2) DEFAULT 0,
PAYMENT_MODE       VARCHAR2(20) CHECK (PAYMENT_MODE IN ('CASH','CARD','BKASH','NAGAD','ROCKET','BANK','CHEQUE')),
TRANSACTION_REF    VARCHAR2(100),
ADVANCE_STATUS     VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (ADVANCE_STATUS IN ('ACTIVE','ADJUSTED','REFUNDED','CANCELLED'))
""", "CONSTRAINT UK_ADVANCE_NO UNIQUE (ADVANCE_NO)")

T(m, "HMS_PAYMENT_RECEIPT", "RECEIPT_ID", """
RECEIPT_NO         VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
BILL_ID            NUMBER REFERENCES HMS_BILLING(BILL_ID),
PATIENT_ID         NUMBER NOT NULL REFERENCES HMS_PATIENT(PATIENT_ID),
RECEIPT_DATE       TIMESTAMP DEFAULT SYSTIMESTAMP,
RECEIPT_TYPE       VARCHAR2(20) DEFAULT 'PAYMENT' CHECK (RECEIPT_TYPE IN ('PAYMENT','ADVANCE','REFUND','ADJUSTMENT')),
AMOUNT             NUMBER(14,2) NOT NULL,
PAYMENT_MODE       VARCHAR2(20) CHECK (PAYMENT_MODE IN ('CASH','CARD','BKASH','NAGAD','ROCKET','BANK','CHEQUE','ADVANCE','INSURANCE')),
TRANSACTION_REF    VARCHAR2(100),
CARD_LAST4         VARCHAR2(4),
BANK_NAME          VARCHAR2(150),
CASHIER_ID         NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
RECEIPT_STATUS     VARCHAR2(20) DEFAULT 'VALID' CHECK (RECEIPT_STATUS IN ('VALID','CANCELLED'))
""", "CONSTRAINT UK_RECEIPT_NO UNIQUE (RECEIPT_NO)")

T(m, "HMS_INSURANCE_CLAIM", "CLAIM_ID", """
CLAIM_NO           VARCHAR2(30) NOT NULL,
POLICY_ID          NUMBER NOT NULL REFERENCES HMS_PATIENT_INSURANCE(POLICY_ID),
BILL_ID            NUMBER NOT NULL REFERENCES HMS_BILLING(BILL_ID),
CLAIM_DATE         DATE DEFAULT SYSDATE,
CLAIM_AMOUNT       NUMBER(14,2),
APPROVED_AMOUNT    NUMBER(14,2),
SETTLED_AMOUNT     NUMBER(14,2),
SETTLEMENT_DATE    DATE,
CLAIM_STATUS       VARCHAR2(20) DEFAULT 'SUBMITTED' CHECK (CLAIM_STATUS IN ('SUBMITTED','UNDER_REVIEW','APPROVED','PARTIAL','REJECTED','SETTLED')),
REJECTION_REASON   VARCHAR2(1000)
""", "CONSTRAINT UK_CLAIM_NO UNIQUE (CLAIM_NO)")

T(m, "HMS_DOCTOR_EARNING", "EARNING_ID", """
DOCTOR_ID          NUMBER NOT NULL REFERENCES HMS_DOCTOR(DOCTOR_ID),
BILL_DTL_ID        NUMBER REFERENCES HMS_BILLING_DTL(BILL_DTL_ID),
EARNING_DATE       DATE DEFAULT SYSDATE,
EARNING_TYPE       VARCHAR2(20) CHECK (EARNING_TYPE IN ('CONSULTATION','REFERRAL','SURGERY','VISIT','PROCEDURE')),
BASE_AMOUNT        NUMBER(12,2),
EARNING_AMOUNT     NUMBER(12,2) NOT NULL,
PAYOUT_STATUS      VARCHAR2(20) DEFAULT 'PENDING' CHECK (PAYOUT_STATUS IN ('PENDING','PAID','HOLD')),
PAID_DATE          DATE
""")

T(m, "HMS_CHART_OF_ACCOUNTS", "COA_ID", f"""
ACCOUNT_CODE       VARCHAR2(30) NOT NULL,
ACCOUNT_NAME       VARCHAR2(200) NOT NULL,
ACCOUNT_TYPE       VARCHAR2(20) NOT NULL CHECK (ACCOUNT_TYPE IN ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE')),
PARENT_COA_ID      NUMBER REFERENCES HMS_CHART_OF_ACCOUNTS(COA_ID),
ACCOUNT_LEVEL      NUMBER DEFAULT 1,
{yn('IS_POSTING','Y')},
OPENING_BALANCE    NUMBER(16,2) DEFAULT 0
""", "CONSTRAINT UK_COA_CODE UNIQUE (ACCOUNT_CODE)")

T(m, "HMS_JOURNAL_VOUCHER", "VOUCHER_ID", """
VOUCHER_NO         VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
VOUCHER_DATE       DATE DEFAULT SYSDATE NOT NULL,
VOUCHER_TYPE       VARCHAR2(20) CHECK (VOUCHER_TYPE IN ('JOURNAL','RECEIPT','PAYMENT','CONTRA')),
NARRATION          VARCHAR2(1000),
REF_TYPE           VARCHAR2(30),
REF_ID             NUMBER,
TOTAL_DEBIT        NUMBER(16,2) DEFAULT 0,
TOTAL_CREDIT       NUMBER(16,2) DEFAULT 0,
VOUCHER_STATUS     VARCHAR2(20) DEFAULT 'DRAFT' CHECK (VOUCHER_STATUS IN ('DRAFT','POSTED','CANCELLED')),
APPROVED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""", "CONSTRAINT UK_VOUCHER_NO UNIQUE (VOUCHER_NO)")

T(m, "HMS_JOURNAL_VOUCHER_DTL", "VOUCHER_DTL_ID", """
VOUCHER_ID         NUMBER NOT NULL REFERENCES HMS_JOURNAL_VOUCHER(VOUCHER_ID),
COA_ID             NUMBER NOT NULL REFERENCES HMS_CHART_OF_ACCOUNTS(COA_ID),
DEBIT_AMOUNT       NUMBER(16,2) DEFAULT 0,
CREDIT_AMOUNT      NUMBER(16,2) DEFAULT 0,
LINE_NARRATION     VARCHAR2(500)
""", "CONSTRAINT CK_JV_DR_CR CHECK (DEBIT_AMOUNT >= 0 AND CREDIT_AMOUNT >= 0)")

# =====================================================================
# 17 INVENTORY & STORE (general / non-medicine)
# =====================================================================
m = module(17, "17_inventory_tables.sql", "INVENTORY & STORE (General items + Asset)")

T(m, "HMS_INV_STORE", "INV_STORE_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
STORE_CODE         VARCHAR2(30) NOT NULL,
STORE_NAME         VARCHAR2(200) NOT NULL,
STORE_INCHARGE_ID  NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""", "CONSTRAINT UK_INV_STORE UNIQUE (STORE_CODE)")

T(m, "HMS_INV_ITEM", "INV_ITEM_ID", """
ITEM_CODE          VARCHAR2(30) NOT NULL,
ITEM_NAME          VARCHAR2(300) NOT NULL,
ITEM_GROUP         VARCHAR2(50) CHECK (ITEM_GROUP IN ('SURGICAL','LINEN','STATIONERY','HOUSEKEEPING','LAB_REAGENT','EQUIPMENT','FOOD','OTHER')),
UNIT_OF_MEASURE    VARCHAR2(30),
REORDER_LEVEL      NUMBER DEFAULT 0,
LAST_PURCHASE_RATE NUMBER(12,2)
""", "CONSTRAINT UK_INV_ITEM UNIQUE (ITEM_CODE)")

T(m, "HMS_INV_STOCK", "INV_STOCK_ID", """
INV_STORE_ID       NUMBER NOT NULL REFERENCES HMS_INV_STORE(INV_STORE_ID),
INV_ITEM_ID        NUMBER NOT NULL REFERENCES HMS_INV_ITEM(INV_ITEM_ID),
QTY_AVAILABLE      NUMBER DEFAULT 0 NOT NULL,
AVG_COST           NUMBER(12,2)
""", "CONSTRAINT UK_INV_STOCK UNIQUE (INV_STORE_ID, INV_ITEM_ID)")

T(m, "HMS_INDENT", "INDENT_ID", """
INDENT_NO          VARCHAR2(30) NOT NULL,
FROM_DEPT_ID       NUMBER NOT NULL REFERENCES HMS_DEPARTMENT(DEPT_ID),
INV_STORE_ID       NUMBER NOT NULL REFERENCES HMS_INV_STORE(INV_STORE_ID),
INDENT_DATE        DATE DEFAULT SYSDATE,
REQUESTED_BY       NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
APPROVED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
INDENT_STATUS      VARCHAR2(20) DEFAULT 'PENDING' CHECK (INDENT_STATUS IN ('PENDING','APPROVED','PARTIAL','ISSUED','REJECTED'))
""", "CONSTRAINT UK_INDENT_NO UNIQUE (INDENT_NO)", comment="Department requisition")

T(m, "HMS_INDENT_DTL", "INDENT_DTL_ID", """
INDENT_ID          NUMBER NOT NULL REFERENCES HMS_INDENT(INDENT_ID),
INV_ITEM_ID        NUMBER NOT NULL REFERENCES HMS_INV_ITEM(INV_ITEM_ID),
REQUESTED_QTY      NUMBER NOT NULL,
APPROVED_QTY       NUMBER,
ISSUED_QTY         NUMBER DEFAULT 0
""")

T(m, "HMS_ASSET", "ASSET_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
DEPT_ID            NUMBER REFERENCES HMS_DEPARTMENT(DEPT_ID),
ASSET_CODE         VARCHAR2(30) NOT NULL,
ASSET_NAME         VARCHAR2(300) NOT NULL,
ASSET_CATEGORY     VARCHAR2(50),
SERIAL_NO          VARCHAR2(100),
PURCHASE_DATE      DATE,
PURCHASE_COST      NUMBER(14,2),
WARRANTY_UPTO      DATE,
AMC_UPTO           DATE,
DEPRECIATION_RATE  NUMBER(5,2),
ASSET_STATUS       VARCHAR2(20) DEFAULT 'IN_USE' CHECK (ASSET_STATUS IN ('IN_USE','IN_STORE','UNDER_REPAIR','CONDEMNED','DISPOSED'))
""", "CONSTRAINT UK_ASSET_CODE UNIQUE (ASSET_CODE)")

# =====================================================================
# 18 HR / PAYROLL
# =====================================================================
m = module(18, "18_hr_tables.sql", "ADMIN / HR / PAYROLL")

T(m, "HMS_DUTY_ROSTER", "ROSTER_ID", """
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
SHIFT_ID           NUMBER NOT NULL REFERENCES HMS_SHIFT_MASTER(SHIFT_ID),
DEPT_ID            NUMBER REFERENCES HMS_DEPARTMENT(DEPT_ID),
WARD_ID            NUMBER REFERENCES HMS_WARD(WARD_ID),
DUTY_DATE          DATE NOT NULL,
ROSTER_STATUS      VARCHAR2(20) DEFAULT 'SCHEDULED' CHECK (ROSTER_STATUS IN ('SCHEDULED','PRESENT','ABSENT','LEAVE','SWAPPED'))
""", "CONSTRAINT UK_ROSTER UNIQUE (EMPLOYEE_ID, DUTY_DATE, SHIFT_ID)")

T(m, "HMS_ATTENDANCE", "ATTENDANCE_ID", """
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
ATTENDANCE_DATE    DATE NOT NULL,
CHECK_IN           TIMESTAMP,
CHECK_OUT          TIMESTAMP,
ATTENDANCE_STATUS  VARCHAR2(20) CHECK (ATTENDANCE_STATUS IN ('PRESENT','ABSENT','LATE','HALF_DAY','LEAVE','HOLIDAY','WEEKEND')),
LATE_MINUTES       NUMBER DEFAULT 0,
OVERTIME_MINUTES   NUMBER DEFAULT 0,
SOURCE_DEVICE      VARCHAR2(50)
""", "CONSTRAINT UK_ATTENDANCE UNIQUE (EMPLOYEE_ID, ATTENDANCE_DATE)")

T(m, "HMS_LEAVE_TYPE", "LEAVE_TYPE_ID", f"""
LEAVE_CODE         VARCHAR2(20) NOT NULL,
LEAVE_NAME         VARCHAR2(100) NOT NULL,
DAYS_PER_YEAR      NUMBER,
{yn('IS_PAID','Y')},
{yn('CARRY_FORWARD')}
""", "CONSTRAINT UK_LEAVE_CODE UNIQUE (LEAVE_CODE)")

T(m, "HMS_LEAVE_APPLICATION", "LEAVE_ID", """
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
LEAVE_TYPE_ID      NUMBER NOT NULL REFERENCES HMS_LEAVE_TYPE(LEAVE_TYPE_ID),
START_DATE         DATE NOT NULL,
END_DATE           DATE NOT NULL,
TOTAL_DAYS         NUMBER,
REASON             VARCHAR2(1000),
APPROVED_BY        NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
LEAVE_STATUS       VARCHAR2(20) DEFAULT 'PENDING' CHECK (LEAVE_STATUS IN ('PENDING','APPROVED','REJECTED','CANCELLED'))
""", "CONSTRAINT CK_LEAVE_DATES CHECK (END_DATE >= START_DATE)")

T(m, "HMS_SALARY_STRUCTURE", "SALARY_ID", """
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
EFFECTIVE_FROM     DATE NOT NULL,
BASIC_SALARY       NUMBER(12,2) NOT NULL,
HOUSE_RENT         NUMBER(12,2) DEFAULT 0,
MEDICAL_ALLOWANCE  NUMBER(12,2) DEFAULT 0,
CONVEYANCE         NUMBER(12,2) DEFAULT 0,
OTHER_ALLOWANCE    NUMBER(12,2) DEFAULT 0,
PF_PERCENT         NUMBER(5,2) DEFAULT 0,
TAX_DEDUCTION      NUMBER(12,2) DEFAULT 0,
GROSS_SALARY       NUMBER(12,2)
""", "CONSTRAINT UK_SALARY UNIQUE (EMPLOYEE_ID, EFFECTIVE_FROM)")

T(m, "HMS_PAYROLL", "PAYROLL_ID", """
EMPLOYEE_ID        NUMBER NOT NULL REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
SALARY_MONTH       VARCHAR2(7) NOT NULL,
WORKING_DAYS       NUMBER,
PRESENT_DAYS       NUMBER,
GROSS_SALARY       NUMBER(12,2),
OVERTIME_AMOUNT    NUMBER(12,2) DEFAULT 0,
BONUS_AMOUNT       NUMBER(12,2) DEFAULT 0,
TOTAL_DEDUCTION    NUMBER(12,2) DEFAULT 0,
NET_SALARY         NUMBER(12,2),
PAYMENT_DATE       DATE,
PAYROLL_STATUS     VARCHAR2(20) DEFAULT 'DRAFT' CHECK (PAYROLL_STATUS IN ('DRAFT','APPROVED','PAID'))
""", "CONSTRAINT UK_PAYROLL UNIQUE (EMPLOYEE_ID, SALARY_MONTH)", comment="SALARY_MONTH format YYYY-MM")

# =====================================================================
# 19 EMERGENCY / AMBULANCE
# =====================================================================
m = module(19, "19_emergency_tables.sql", "EMERGENCY & AMBULANCE")

T(m, "HMS_EMERGENCY_VISIT", "ER_VISIT_ID", f"""
ER_NO              VARCHAR2(30) NOT NULL,
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
PATIENT_ID         NUMBER REFERENCES HMS_PATIENT(PATIENT_ID),
UNKNOWN_PATIENT_DESC VARCHAR2(500),
ARRIVAL_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
ARRIVAL_MODE       VARCHAR2(20) CHECK (ARRIVAL_MODE IN ('WALK_IN','AMBULANCE','POLICE','REFERRED','OTHER')),
BROUGHT_BY         VARCHAR2(200),
{yn('IS_MLC')},
ATTENDING_DOCTOR_ID NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
ER_OUTCOME         VARCHAR2(20) CHECK (ER_OUTCOME IN ('DISCHARGED','ADMITTED','REFERRED','LAMA','DEATH','BROUGHT_DEAD')),
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
DEPARTURE_TIME     TIMESTAMP
""", "CONSTRAINT UK_ER_NO UNIQUE (ER_NO)")

T(m, "HMS_EMERGENCY_TRIAGE", "TRIAGE_ID", """
ER_VISIT_ID        NUMBER NOT NULL REFERENCES HMS_EMERGENCY_VISIT(ER_VISIT_ID),
TRIAGE_LEVEL       VARCHAR2(10) CHECK (TRIAGE_LEVEL IN ('RED','ORANGE','YELLOW','GREEN','BLACK')),
CHIEF_COMPLAINT    VARCHAR2(1000),
BP_SYSTOLIC        NUMBER(3),
BP_DIASTOLIC       NUMBER(3),
PULSE_RATE         NUMBER(3),
SPO2               NUMBER(3),
GCS_SCORE          NUMBER(2),
TRIAGE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
TRIAGED_BY         NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID)
""")

T(m, "HMS_AMBULANCE", "AMBULANCE_ID", """
BRANCH_ID          NUMBER NOT NULL REFERENCES HMS_BRANCH(BRANCH_ID),
VEHICLE_NO         VARCHAR2(30) NOT NULL,
AMBULANCE_TYPE     VARCHAR2(20) CHECK (AMBULANCE_TYPE IN ('BASIC','ACLS','ICU','NICU','FREEZER')),
DRIVER_ID          NUMBER REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
DRIVER_PHONE       VARCHAR2(50),
PER_KM_RATE        NUMBER(10,2),
BASE_FARE          NUMBER(10,2),
AMB_STATUS         VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (AMB_STATUS IN ('AVAILABLE','ON_TRIP','MAINTENANCE'))
""", "CONSTRAINT UK_VEHICLE_NO UNIQUE (VEHICLE_NO)")

T(m, "HMS_AMBULANCE_TRIP", "TRIP_ID", """
TRIP_NO            VARCHAR2(30) NOT NULL,
AMBULANCE_ID       NUMBER NOT NULL REFERENCES HMS_AMBULANCE(AMBULANCE_ID),
PATIENT_ID         NUMBER REFERENCES HMS_PATIENT(PATIENT_ID),
CALLER_NAME        VARCHAR2(200),
CALLER_PHONE       VARCHAR2(50),
PICKUP_ADDRESS     VARCHAR2(500),
DROP_ADDRESS       VARCHAR2(500),
DISPATCH_TIME      TIMESTAMP,
RETURN_TIME        TIMESTAMP,
DISTANCE_KM        NUMBER(8,2),
CHARGE_AMOUNT      NUMBER(12,2),
TRIP_STATUS        VARCHAR2(20) DEFAULT 'REQUESTED' CHECK (TRIP_STATUS IN ('REQUESTED','DISPATCHED','COMPLETED','CANCELLED'))
""", "CONSTRAINT UK_TRIP_NO UNIQUE (TRIP_NO)")

# =====================================================================
# 20 MORTUARY
# =====================================================================
m = module(20, "20_mortuary_tables.sql", "MORTUARY")

T(m, "HMS_MORTUARY", "MORTUARY_ID", f"""
BODY_NO            VARCHAR2(30) NOT NULL,
PATIENT_ID         NUMBER REFERENCES HMS_PATIENT(PATIENT_ID),
ADMISSION_ID       NUMBER REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
DECEASED_NAME      VARCHAR2(200) NOT NULL,
DATE_OF_DEATH      TIMESTAMP NOT NULL,
CAUSE_OF_DEATH     VARCHAR2(1000),
DEATH_CERT_NO      VARCHAR2(50),
CERTIFIED_BY       NUMBER REFERENCES HMS_DOCTOR(DOCTOR_ID),
{yn('IS_MLC')},
{yn('POSTMORTEM_REQUIRED')},
CHAMBER_NO         VARCHAR2(20),
RECEIVED_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
RELEASED_TIME      TIMESTAMP,
RELEASED_TO_NAME   VARCHAR2(200),
RELEASED_TO_RELATION VARCHAR2(50),
RELEASED_TO_NID    VARCHAR2(50),
BODY_STATUS        VARCHAR2(20) DEFAULT 'IN_MORTUARY' CHECK (BODY_STATUS IN ('IN_MORTUARY','RELEASED','SENT_FOR_PM'))
""", "CONSTRAINT UK_BODY_NO UNIQUE (BODY_NO)")

# =====================================================================
# 21 AUDIT
# =====================================================================
m = module(21, "21_audit_tables.sql", "AUDIT & SECURITY LOG")

T(m, "HMS_AUDIT_TRAIL", "AUDIT_ID", """
TABLE_NAME         VARCHAR2(100) NOT NULL,
RECORD_ID          NUMBER,
ACTION_TYPE        VARCHAR2(10) NOT NULL CHECK (ACTION_TYPE IN ('INSERT','UPDATE','DELETE')),
COLUMN_NAME        VARCHAR2(100),
OLD_VALUE          VARCHAR2(4000),
NEW_VALUE          VARCHAR2(4000),
ACTION_BY          VARCHAR2(100),
ACTION_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
IP_ADDRESS         VARCHAR2(50),
MODULE_NAME        VARCHAR2(100)
""", active=False)

T(m, "HMS_ERROR_LOG", "ERROR_ID", """
ERROR_CODE         NUMBER,
ERROR_MSG          VARCHAR2(4000),
ERROR_BACKTRACE    VARCHAR2(4000),
PROGRAM_NAME       VARCHAR2(200),
PARAMS             VARCHAR2(4000),
LOGGED_BY          VARCHAR2(100),
LOGGED_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP
""", active=False)

# Late foreign keys (circular / forward references)
LATE_FKS = [
  ("HMS_DEPARTMENT", "FK_DEPT_HOD", "HOD_EMPLOYEE_ID", "HMS_EMPLOYEE", "EMPLOYEE_ID"),
  ("HMS_APPOINTMENT", "FK_APPT_OPD_VISIT", "OPD_VISIT_ID", "HMS_OPD_VISIT", "VISIT_ID"),
  ("HMS_OPD_PRESCRIPTION_DTL", "FK_PRESC_DTL_ITEM", "ITEM_ID", "HMS_PHARMA_ITEM", "ITEM_ID"),
  ("HMS_IPD_MEDICATION", "FK_IPD_MED_ITEM", "ITEM_ID", "HMS_PHARMA_ITEM", "ITEM_ID"),
  ("HMS_IPD_ADMISSION", "FK_ADM_POLICY", "INSURANCE_POLICY_ID", "HMS_PATIENT_INSURANCE", "POLICY_ID"),
]
