/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 01_core_tables.sql
 Purpose   : Tables - CORE / MASTER MODULE (Foundation)
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : CORE / MASTER MODULE (Foundation)

-- ----------------------------------------------------------------------------
-- HMS_BRANCH  : Hospital branch / unit
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BRANCH (
    BRANCH_ID              NUMBER DEFAULT SEQ_BRANCH.NEXTVAL NOT NULL,
    BRANCH_CODE            VARCHAR2(20) NOT NULL,
    BRANCH_NAME            VARCHAR2(200) NOT NULL,
    ADDRESS_LINE1          VARCHAR2(300),
    ADDRESS_LINE2          VARCHAR2(300),
    CITY                   VARCHAR2(100),
    DISTRICT               VARCHAR2(100),
    DIVISION               VARCHAR2(100),
    COUNTRY                VARCHAR2(100) DEFAULT 'Bangladesh',
    POST_CODE              VARCHAR2(20),
    PHONE                  VARCHAR2(50),
    EMAIL                  VARCHAR2(150),
    LICENSE_NO             VARCHAR2(100),
    LOGO                   BLOB,
    IS_HEAD_OFFICE         CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_HEAD_OFFICE IN ('Y','N')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BRANCH PRIMARY KEY (BRANCH_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_BRANCH_CODE UNIQUE (BRANCH_CODE)
)
TABLESPACE HMS_DATA
LOB (LOGO) STORE AS SECUREFILE (TABLESPACE HMS_LOB);
COMMENT ON TABLE HMS_BRANCH IS 'Hospital branch / unit';

-- ----------------------------------------------------------------------------
-- HMS_DEPARTMENT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DEPARTMENT (
    DEPT_ID                NUMBER DEFAULT SEQ_DEPARTMENT.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_DEPARTMENT_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    DEPT_CODE              VARCHAR2(20) NOT NULL,
    DEPT_NAME              VARCHAR2(200) NOT NULL,
    DEPT_TYPE              VARCHAR2(30) CHECK (DEPT_TYPE IN ('CLINICAL','NON_CLINICAL','DIAGNOSTIC','ADMIN','SUPPORT','PHARMACY','LAB')),
    PARENT_DEPT_ID         NUMBER CONSTRAINT FK_DEPARTMENT_PARENT_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    HOD_EMPLOYEE_ID        NUMBER,
    FLOOR_NO               VARCHAR2(20),
    ROOM_NO                VARCHAR2(20),
    EXTENSION_NO           VARCHAR2(20),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_DEPT UNIQUE (BRANCH_ID, DEPT_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_DESIGNATION
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DESIGNATION (
    DESIGNATION_ID         NUMBER DEFAULT SEQ_DESIGNATION.NEXTVAL NOT NULL,
    DESIGNATION_CODE       VARCHAR2(20) NOT NULL,
    DESIGNATION_NAME       VARCHAR2(200) NOT NULL,
    DESIGNATION_LEVEL      NUMBER,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DESIGNATION PRIMARY KEY (DESIGNATION_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_DESIGNATION_CODE UNIQUE (DESIGNATION_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_EMPLOYEE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_EMPLOYEE (
    EMPLOYEE_ID            NUMBER DEFAULT SEQ_EMPLOYEE.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_EMPLOYEE_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    DEPT_ID                NUMBER NOT NULL CONSTRAINT FK_EMPLOYEE_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    DESIGNATION_ID         NUMBER NOT NULL CONSTRAINT FK_EMPLOYEE_DESIGNATION_ID REFERENCES HMS_DESIGNATION(DESIGNATION_ID),
    EMPLOYEE_CODE          VARCHAR2(30) NOT NULL,
    FIRST_NAME             VARCHAR2(100) NOT NULL,
    LAST_NAME              VARCHAR2(100),
    GENDER                 VARCHAR2(10) CHECK (GENDER IN ('MALE','FEMALE','OTHER')),
    DATE_OF_BIRTH          DATE,
    NID_NUMBER             VARCHAR2(50),
    PASSPORT_NO            VARCHAR2(50),
    BLOOD_GROUP            VARCHAR2(5),
    MARITAL_STATUS         VARCHAR2(20),
    RELIGION               VARCHAR2(30),
    PHOTO                  BLOB,
    PHONE                  VARCHAR2(50),
    EMERGENCY_CONTACT      VARCHAR2(50),
    EMAIL                  VARCHAR2(150),
    PRESENT_ADDRESS        VARCHAR2(500),
    PERMANENT_ADDRESS      VARCHAR2(500),
    JOINING_DATE           DATE NOT NULL,
    RESIGNATION_DATE       DATE,
    EMPLOYEE_TYPE          VARCHAR2(30) CHECK (EMPLOYEE_TYPE IN ('PERMANENT','CONTRACT','VISITING','INTERN','TRAINEE')),
    REPORTING_TO           NUMBER CONSTRAINT FK_EMPLOYEE_REPORTING_TO REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    BANK_NAME              VARCHAR2(150),
    BANK_ACCOUNT_NO        VARCHAR2(50),
    TIN_NO                 VARCHAR2(50),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_EMPLOYEE_CODE UNIQUE (EMPLOYEE_CODE)
)
TABLESPACE HMS_DATA
LOB (PHOTO) STORE AS SECUREFILE (TABLESPACE HMS_LOB);

-- ----------------------------------------------------------------------------
-- HMS_EMPLOYEE_QUALIFICATION
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_EMPLOYEE_QUALIFICATION (
    QUALIFICATION_ID       NUMBER DEFAULT SEQ_EMPLOYEE_QUALIFICATION.NEXTVAL NOT NULL,
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_EMPQUA_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    DEGREE_NAME            VARCHAR2(200) NOT NULL,
    INSTITUTE              VARCHAR2(300),
    BOARD_UNIVERSITY       VARCHAR2(300),
    PASSING_YEAR           NUMBER(4),
    RESULT_GRADE           VARCHAR2(50),
    CERTIFICATE_DOC        BLOB,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_EMPLOYEE_QUALIFICATION PRIMARY KEY (QUALIFICATION_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA
LOB (CERTIFICATE_DOC) STORE AS SECUREFILE (TABLESPACE HMS_LOB);

-- ----------------------------------------------------------------------------
-- HMS_EMPLOYEE_EXPERIENCE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_EMPLOYEE_EXPERIENCE (
    EXPERIENCE_ID          NUMBER DEFAULT SEQ_EMPLOYEE_EXPERIENCE.NEXTVAL NOT NULL,
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_EMPEXP_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    ORGANIZATION_NAME      VARCHAR2(300) NOT NULL,
    POSITION_HELD          VARCHAR2(200),
    START_DATE             DATE,
    END_DATE               DATE,
    RESPONSIBILITIES       VARCHAR2(1000),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_EMPLOYEE_EXPERIENCE PRIMARY KEY (EXPERIENCE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_DOCTOR
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DOCTOR (
    DOCTOR_ID              NUMBER DEFAULT SEQ_DOCTOR.NEXTVAL NOT NULL,
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_DOCTOR_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    DOCTOR_CODE            VARCHAR2(30) NOT NULL,
    SPECIALIZATION         VARCHAR2(200),
    SUB_SPECIALIZATION     VARCHAR2(200),
    QUALIFICATION          VARCHAR2(500),
    BMDC_REG_NO            VARCHAR2(50),
    EXPERIENCE_YEARS       NUMBER,
    CONSULTATION_FEE       NUMBER(12,2) DEFAULT 0,
    FOLLOWUP_FEE           NUMBER(12,2) DEFAULT 0,
    FOLLOWUP_VALID_DAYS    NUMBER DEFAULT 7,
    DOCTOR_TYPE            VARCHAR2(30) CHECK (DOCTOR_TYPE IN ('FULL_TIME','PART_TIME','VISITING','CONSULTANT','RESIDENT')),
    MAX_PATIENT_PER_DAY    NUMBER,
    SIGNATURE_IMAGE        BLOB,
    IS_SURGEON             CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_SURGEON IN ('Y','N')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DOCTOR PRIMARY KEY (DOCTOR_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_DOCTOR_CODE UNIQUE (DOCTOR_CODE)
)
TABLESPACE HMS_DATA
LOB (SIGNATURE_IMAGE) STORE AS SECUREFILE (TABLESPACE HMS_LOB);

-- ----------------------------------------------------------------------------
-- HMS_DOCTOR_DEPT_MAP
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DOCTOR_DEPT_MAP (
    MAP_ID                 NUMBER DEFAULT SEQ_DOCTOR_DEPT_MAP.NEXTVAL NOT NULL,
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_DOCTOR_DEPT_MAP_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    DEPT_ID                NUMBER NOT NULL CONSTRAINT FK_DOCTOR_DEPT_MAP_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    IS_PRIMARY             CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_PRIMARY IN ('Y','N')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DOCTOR_DEPT_MAP PRIMARY KEY (MAP_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_DOC_DEPT UNIQUE (DOCTOR_ID, DEPT_ID)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_DOCTOR_SCHEDULE  : START_TIME/END_TIME format HH24:MI (e.g. 17:30)
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DOCTOR_SCHEDULE (
    SCHEDULE_ID            NUMBER DEFAULT SEQ_DOCTOR_SCHEDULE.NEXTVAL NOT NULL,
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_DOCTOR_SCHEDULE_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_DOCTOR_SCHEDULE_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    DAY_OF_WEEK            VARCHAR2(10) NOT NULL CHECK (DAY_OF_WEEK IN ('SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY')),
    START_TIME             VARCHAR2(5) NOT NULL,
    END_TIME               VARCHAR2(5) NOT NULL,
    SLOT_DURATION_MIN      NUMBER DEFAULT 10,
    MAX_SLOTS              NUMBER,
    ROOM_NO                VARCHAR2(20),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DOCTOR_SCHEDULE PRIMARY KEY (SCHEDULE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_DOCTOR_SCHEDULE IS 'START_TIME/END_TIME format HH24:MI (e.g. 17:30)';

-- ----------------------------------------------------------------------------
-- HMS_LOOKUP_MASTER  : Generic dropdown values (Blood group, Religion, Relation ...)
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LOOKUP_MASTER (
    LOOKUP_ID              NUMBER DEFAULT SEQ_LOOKUP_MASTER.NEXTVAL NOT NULL,
    LOOKUP_TYPE            VARCHAR2(100) NOT NULL,
    LOOKUP_CODE            VARCHAR2(50) NOT NULL,
    LOOKUP_VALUE           VARCHAR2(200) NOT NULL,
    DISPLAY_ORDER          NUMBER,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LOOKUP_MASTER PRIMARY KEY (LOOKUP_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_LOOKUP UNIQUE (LOOKUP_TYPE, LOOKUP_CODE)
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_LOOKUP_MASTER IS 'Generic dropdown values (Blood group, Religion, Relation ...)';

-- ----------------------------------------------------------------------------
-- HMS_SYSTEM_CONFIG
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_SYSTEM_CONFIG (
    CONFIG_ID              NUMBER DEFAULT SEQ_SYSTEM_CONFIG.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER CONSTRAINT FK_SYSTEM_CONFIG_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    CONFIG_KEY             VARCHAR2(100) NOT NULL,
    CONFIG_VALUE           VARCHAR2(1000),
    CONFIG_DESC            VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_SYSTEM_CONFIG PRIMARY KEY (CONFIG_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SYS_CONFIG UNIQUE (BRANCH_ID, CONFIG_KEY)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_NUMBER_SERIES  : MRN, Bill No, Visit No, Admission No generate korar jonno
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_NUMBER_SERIES (
    SERIES_ID              NUMBER DEFAULT SEQ_NUMBER_SERIES.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_NUMBER_SERIES_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    SERIES_TYPE            VARCHAR2(50) NOT NULL,
    PREFIX                 VARCHAR2(20),
    CURRENT_NO             NUMBER DEFAULT 0 NOT NULL,
    PAD_LENGTH             NUMBER DEFAULT 6,
    RESET_CYCLE            VARCHAR2(10) DEFAULT 'NEVER' CHECK (RESET_CYCLE IN ('NEVER','YEARLY','MONTHLY','DAILY')),
    LAST_RESET_DATE        DATE,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_NUMBER_SERIES PRIMARY KEY (SERIES_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_NUM_SERIES UNIQUE (BRANCH_ID, SERIES_TYPE)
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_NUMBER_SERIES IS 'MRN, Bill No, Visit No, Admission No generate korar jonno';

-- ----------------------------------------------------------------------------
-- HMS_ICD_MASTER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_ICD_MASTER (
    ICD_ID                 NUMBER DEFAULT SEQ_ICD_MASTER.NEXTVAL NOT NULL,
    ICD_CODE               VARCHAR2(20) NOT NULL,
    ICD_DESCRIPTION        VARCHAR2(500) NOT NULL,
    ICD_CATEGORY           VARCHAR2(200),
    PARENT_ICD_ID          NUMBER CONSTRAINT FK_ICD_MASTER_PARENT_ICD_ID REFERENCES HMS_ICD_MASTER(ICD_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_ICD_MASTER PRIMARY KEY (ICD_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_ICD_CODE UNIQUE (ICD_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_SHIFT_MASTER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_SHIFT_MASTER (
    SHIFT_ID               NUMBER DEFAULT SEQ_SHIFT_MASTER.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_SHIFT_MASTER_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    SHIFT_CODE             VARCHAR2(20) NOT NULL,
    SHIFT_NAME             VARCHAR2(100) NOT NULL,
    START_TIME             VARCHAR2(5) NOT NULL,
    END_TIME               VARCHAR2(5) NOT NULL,
    GRACE_MIN              NUMBER DEFAULT 15,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_SHIFT_MASTER PRIMARY KEY (SHIFT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SHIFT UNIQUE (BRANCH_ID, SHIFT_CODE)
)
TABLESPACE HMS_DATA;

