/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 03_patient_tables.sql
 Purpose   : Tables - PATIENT MANAGEMENT MODULE
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : PATIENT MANAGEMENT MODULE

-- ----------------------------------------------------------------------------
-- HMS_PATIENT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PATIENT (
    PATIENT_ID             NUMBER DEFAULT SEQ_PATIENT.NEXTVAL NOT NULL,
    MRN                    VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_PATIENT_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    TITLE                  VARCHAR2(10),
    FIRST_NAME             VARCHAR2(100) NOT NULL,
    MIDDLE_NAME            VARCHAR2(100),
    LAST_NAME              VARCHAR2(100),
    FATHER_NAME            VARCHAR2(200),
    MOTHER_NAME            VARCHAR2(200),
    SPOUSE_NAME            VARCHAR2(200),
    GENDER                 VARCHAR2(10) NOT NULL CHECK (GENDER IN ('MALE','FEMALE','OTHER')),
    DATE_OF_BIRTH          DATE,
    AGE_YEARS              NUMBER,
    AGE_MONTHS             NUMBER,
    AGE_DAYS               NUMBER,
    BLOOD_GROUP            VARCHAR2(5),
    MARITAL_STATUS         VARCHAR2(20),
    RELIGION               VARCHAR2(30),
    NATIONALITY            VARCHAR2(50) DEFAULT 'Bangladeshi',
    NID_NUMBER             VARCHAR2(50),
    BIRTH_REG_NO           VARCHAR2(50),
    PASSPORT_NO            VARCHAR2(50),
    OCCUPATION             VARCHAR2(100),
    PHONE_PRIMARY          VARCHAR2(50) NOT NULL,
    PHONE_SECONDARY        VARCHAR2(50),
    EMAIL                  VARCHAR2(150),
    PRESENT_ADDRESS        VARCHAR2(500),
    PRESENT_THANA          VARCHAR2(100),
    PRESENT_DISTRICT       VARCHAR2(100),
    PRESENT_DIVISION       VARCHAR2(100),
    PERMANENT_ADDRESS      VARCHAR2(500),
    PERMANENT_DISTRICT     VARCHAR2(100),
    EMERGENCY_CONTACT_NAME VARCHAR2(200),
    EMERGENCY_CONTACT_PHONE VARCHAR2(50),
    EMERGENCY_CONTACT_RELATION VARCHAR2(50),
    PHOTO                  BLOB,
    REFERRED_BY            VARCHAR2(200),
    REFERRED_DOCTOR_ID     NUMBER CONSTRAINT FK_PATIENT_REFERRED_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    REGISTRATION_DATE      DATE DEFAULT SYSDATE,
    IS_VIP                 CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_VIP IN ('Y','N')),
    IS_MEDICO_LEGAL        CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_MEDICO_LEGAL IN ('Y','N')),
    PATIENT_CATEGORY       VARCHAR2(30) DEFAULT 'GENERAL' CHECK (PATIENT_CATEGORY IN ('GENERAL','STAFF','VIP','CORPORATE','INSURANCE','POOR_FREE')),
    REMARKS                VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PATIENT PRIMARY KEY (PATIENT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_PATIENT_MRN UNIQUE (MRN)
)
TABLESPACE HMS_DATA
LOB (PHOTO) STORE AS SECUREFILE (TABLESPACE HMS_LOB);

-- ----------------------------------------------------------------------------
-- HMS_PATIENT_ALLERGY
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PATIENT_ALLERGY (
    ALLERGY_ID             NUMBER DEFAULT SEQ_PATIENT_ALLERGY.NEXTVAL NOT NULL,
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_PATIENT_ALLERGY_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    ALLERGY_TYPE           VARCHAR2(30) CHECK (ALLERGY_TYPE IN ('DRUG','FOOD','ENVIRONMENT','OTHER')),
    ALLERGY_NAME           VARCHAR2(200) NOT NULL,
    SEVERITY               VARCHAR2(20) CHECK (SEVERITY IN ('MILD','MODERATE','SEVERE')),
    REACTION_DESC          VARCHAR2(500),
    NOTED_DATE             DATE DEFAULT SYSDATE,
    NOTED_BY               NUMBER CONSTRAINT FK_PATIENT_ALLERGY_NOTED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PATIENT_ALLERGY PRIMARY KEY (ALLERGY_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PATIENT_MEDICAL_HISTORY
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PATIENT_MEDICAL_HISTORY (
    HISTORY_ID             NUMBER DEFAULT SEQ_PATIENT_MEDICAL_HISTORY.NEXTVAL NOT NULL,
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_PATMEDHIS_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    DISEASE_NAME           VARCHAR2(200),
    ICD_ID                 NUMBER CONSTRAINT FK_PATMEDHIS_ICD_ID REFERENCES HMS_ICD_MASTER(ICD_ID),
    DIAGNOSIS_DATE         DATE,
    IS_CHRONIC             CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_CHRONIC IN ('Y','N')),
    TREATMENT_DETAILS      VARCHAR2(4000),
    IS_FAMILY_HISTORY      CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_FAMILY_HISTORY IN ('Y','N')),
    RELATION               VARCHAR2(50),
    REMARKS                VARCHAR2(500),
    RECORDED_BY            NUMBER CONSTRAINT FK_PATMEDHIS_RECORDED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PATIENT_MEDICAL_HISTORY PRIMARY KEY (HISTORY_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PATIENT_DOCUMENT  : REF_TYPE = OPD/IPD/LAB ... , REF_ID = related visit/admission id
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PATIENT_DOCUMENT (
    DOCUMENT_ID            NUMBER DEFAULT SEQ_PATIENT_DOCUMENT.NEXTVAL NOT NULL,
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_PATIENT_DOCUMENT_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    REF_TYPE               VARCHAR2(20),
    REF_ID                 NUMBER,
    DOCUMENT_TYPE          VARCHAR2(50),
    DOCUMENT_NAME          VARCHAR2(200),
    FILE_NAME              VARCHAR2(300),
    FILE_CONTENT           BLOB,
    FILE_SIZE_KB           NUMBER,
    MIME_TYPE              VARCHAR2(100),
    UPLOADED_BY            NUMBER CONSTRAINT FK_PATDOC_UPLOADED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    REMARKS                VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PATIENT_DOCUMENT PRIMARY KEY (DOCUMENT_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA
LOB (FILE_CONTENT) STORE AS SECUREFILE (TABLESPACE HMS_LOB);
COMMENT ON TABLE HMS_PATIENT_DOCUMENT IS 'REF_TYPE = OPD/IPD/LAB ... , REF_ID = related visit/admission id';

