/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 04_service_tables.sql
 Purpose   : Tables - SERVICE / CHARGE MASTER
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : SERVICE / CHARGE MASTER

-- ----------------------------------------------------------------------------
-- HMS_SERVICE_CATEGORY
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_SERVICE_CATEGORY (
    CATEGORY_ID            NUMBER DEFAULT SEQ_SERVICE_CATEGORY.NEXTVAL NOT NULL,
    CATEGORY_CODE          VARCHAR2(30) NOT NULL,
    CATEGORY_NAME          VARCHAR2(200) NOT NULL,
    CATEGORY_TYPE          VARCHAR2(30) CHECK (CATEGORY_TYPE IN ('CONSULTATION','LAB','RADIOLOGY','PROCEDURE','BED','OT','NURSING','PHARMACY','PACKAGE','MISC')),
    PARENT_CATEGORY_ID     NUMBER CONSTRAINT FK_SERCAT_PARENT_CATEGORY_ID REFERENCES HMS_SERVICE_CATEGORY(CATEGORY_ID),
    DISPLAY_ORDER          NUMBER,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_SERVICE_CATEGORY PRIMARY KEY (CATEGORY_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SVC_CAT UNIQUE (CATEGORY_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_SERVICE_MASTER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_SERVICE_MASTER (
    SERVICE_ID             NUMBER DEFAULT SEQ_SERVICE_MASTER.NEXTVAL NOT NULL,
    CATEGORY_ID            NUMBER NOT NULL CONSTRAINT FK_SERVICE_MASTER_CATEGORY_ID REFERENCES HMS_SERVICE_CATEGORY(CATEGORY_ID),
    DEPT_ID                NUMBER CONSTRAINT FK_SERVICE_MASTER_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    SERVICE_CODE           VARCHAR2(30) NOT NULL,
    SERVICE_NAME           VARCHAR2(300) NOT NULL,
    SHORT_NAME             VARCHAR2(100),
    BASE_CHARGE            NUMBER(12,2) DEFAULT 0 NOT NULL,
    EMERGENCY_CHARGE       NUMBER(12,2),
    TAX_APPLICABLE         CHAR(1) DEFAULT 'N' NOT NULL CHECK (TAX_APPLICABLE IN ('Y','N')),
    TAX_PERCENT            NUMBER(5,2) DEFAULT 0,
    TURN_AROUND_TIME       VARCHAR2(50),
    SAMPLE_REQUIRED        CHAR(1) DEFAULT 'N' NOT NULL CHECK (SAMPLE_REQUIRED IN ('Y','N')),
    SAMPLE_TYPE            VARCHAR2(100),
    REPORTING_SECTION      VARCHAR2(100),
    IS_PACKAGE             CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_PACKAGE IN ('Y','N')),
    IS_OUTSOURCED          CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_OUTSOURCED IN ('Y','N')),
    OUTSOURCE_LAB          VARCHAR2(200),
    OUTSOURCE_COST         NUMBER(12,2),
    CONSENT_REQUIRED       CHAR(1) DEFAULT 'N' NOT NULL CHECK (CONSENT_REQUIRED IN ('Y','N')),
    GENDER_SPECIFIC        VARCHAR2(10) CHECK (GENDER_SPECIFIC IN ('MALE','FEMALE','ALL')),
    DOCTOR_COMMISSION_APPLICABLE CHAR(1) DEFAULT 'N' NOT NULL CHECK (DOCTOR_COMMISSION_APPLICABLE IN ('Y','N')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_SERVICE_MASTER PRIMARY KEY (SERVICE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SERVICE_CODE UNIQUE (SERVICE_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_SERVICE_CHARGE  : Category-wise (GENERAL/VIP/CORPORATE) rate
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_SERVICE_CHARGE (
    CHARGE_ID              NUMBER DEFAULT SEQ_SERVICE_CHARGE.NEXTVAL NOT NULL,
    SERVICE_ID             NUMBER NOT NULL CONSTRAINT FK_SERVICE_CHARGE_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_SERVICE_CHARGE_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    PATIENT_CATEGORY       VARCHAR2(30) NOT NULL,
    CHARGE_AMOUNT          NUMBER(12,2) NOT NULL,
    DISCOUNT_PERCENT       NUMBER(5,2) DEFAULT 0,
    EFFECTIVE_FROM         DATE NOT NULL,
    EFFECTIVE_TO           DATE,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_SERVICE_CHARGE PRIMARY KEY (CHARGE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SVC_CHARGE UNIQUE (SERVICE_ID, BRANCH_ID, PATIENT_CATEGORY, EFFECTIVE_FROM)
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_SERVICE_CHARGE IS 'Category-wise (GENERAL/VIP/CORPORATE) rate';

-- ----------------------------------------------------------------------------
-- HMS_SERVICE_PACKAGE_DTL
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_SERVICE_PACKAGE_DTL (
    PACKAGE_DTL_ID         NUMBER DEFAULT SEQ_SERVICE_PACKAGE_DTL.NEXTVAL NOT NULL,
    PACKAGE_SERVICE_ID     NUMBER NOT NULL CONSTRAINT FK_SERPACDTL_PACKAGE_SERVICE_I REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    CHILD_SERVICE_ID       NUMBER NOT NULL CONSTRAINT FK_SERPACDTL_CHILD_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    QUANTITY               NUMBER DEFAULT 1,
    IS_MANDATORY           CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_MANDATORY IN ('Y','N')),
    DISPLAY_ORDER          NUMBER,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_SERVICE_PACKAGE_DTL PRIMARY KEY (PACKAGE_DTL_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_PKG_DTL UNIQUE (PACKAGE_SERVICE_ID, CHILD_SERVICE_ID)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_DOCTOR_COMMISSION  : Referral / consultation commission setup
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DOCTOR_COMMISSION (
    COMMISSION_ID          NUMBER DEFAULT SEQ_DOCTOR_COMMISSION.NEXTVAL NOT NULL,
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_DOCTOR_COMMISSION_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    SERVICE_ID             NUMBER CONSTRAINT FK_DOCCOM_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    CATEGORY_ID            NUMBER CONSTRAINT FK_DOCCOM_CATEGORY_ID REFERENCES HMS_SERVICE_CATEGORY(CATEGORY_ID),
    COMMISSION_TYPE        VARCHAR2(20) CHECK (COMMISSION_TYPE IN ('PERCENT','FIXED')),
    COMMISSION_VALUE       NUMBER(12,2) NOT NULL,
    EFFECTIVE_FROM         DATE NOT NULL,
    EFFECTIVE_TO           DATE,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DOCTOR_COMMISSION PRIMARY KEY (COMMISSION_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_DOCTOR_COMMISSION IS 'Referral / consultation commission setup';

