/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 05_appointment_tables.sql
 Purpose   : Tables - APPOINTMENT & SCHEDULING
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : APPOINTMENT & SCHEDULING

-- ----------------------------------------------------------------------------
-- HMS_APPOINTMENT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_APPOINTMENT (
    APPOINTMENT_ID         NUMBER DEFAULT SEQ_APPOINTMENT.NEXTVAL NOT NULL,
    APPOINTMENT_NO         VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_APPOINTMENT_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    PATIENT_ID             NUMBER CONSTRAINT FK_APPOINTMENT_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    PATIENT_NAME           VARCHAR2(200),
    MOBILE_NO              VARCHAR2(50),
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_APPOINTMENT_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    SCHEDULE_ID            NUMBER CONSTRAINT FK_APPOINTMENT_SCHEDULE_ID REFERENCES HMS_DOCTOR_SCHEDULE(SCHEDULE_ID),
    APPOINTMENT_DATE       DATE NOT NULL,
    SLOT_TIME              VARCHAR2(5),
    SERIAL_NO              NUMBER,
    BOOKING_SOURCE         VARCHAR2(20) DEFAULT 'COUNTER' CHECK (BOOKING_SOURCE IN ('COUNTER','PHONE','ONLINE','APP')),
    APPOINTMENT_STATUS     VARCHAR2(20) DEFAULT 'BOOKED' CHECK (APPOINTMENT_STATUS IN ('BOOKED','CONFIRMED','ARRIVED','COMPLETED','CANCELLED','NO_SHOW')),
    CANCEL_REASON          VARCHAR2(500),
    OPD_VISIT_ID           NUMBER,
    REMARKS                VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_APPOINTMENT PRIMARY KEY (APPOINTMENT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_APPOINTMENT_NO UNIQUE (APPOINTMENT_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_COMMUNICATION_LOG
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_COMMUNICATION_LOG (
    COMM_ID                NUMBER DEFAULT SEQ_COMMUNICATION_LOG.NEXTVAL NOT NULL,
    PATIENT_ID             NUMBER CONSTRAINT FK_COMLOG_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    CHANNEL                VARCHAR2(20) CHECK (CHANNEL IN ('SMS','EMAIL','WHATSAPP','CALL')),
    RECIPIENT              VARCHAR2(200),
    MESSAGE_TEXT           VARCHAR2(2000),
    REF_TYPE               VARCHAR2(30),
    REF_ID                 NUMBER,
    SEND_STATUS            VARCHAR2(20) DEFAULT 'PENDING' CHECK (SEND_STATUS IN ('PENDING','SENT','FAILED')),
    SENT_TIME              TIMESTAMP,
    ERROR_MSG              VARCHAR2(1000),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_COMMUNICATION_LOG PRIMARY KEY (COMM_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

