/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 06_opd_tables.sql
 Purpose   : Tables - OPD (Out Patient Department)
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : OPD (Out Patient Department)

-- ----------------------------------------------------------------------------
-- HMS_OPD_VISIT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OPD_VISIT (
    VISIT_ID               NUMBER DEFAULT SEQ_OPD_VISIT.NEXTVAL NOT NULL,
    VISIT_NO               VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_OPD_VISIT_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_OPD_VISIT_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_OPD_VISIT_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    DEPT_ID                NUMBER NOT NULL CONSTRAINT FK_OPD_VISIT_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    APPOINTMENT_ID         NUMBER CONSTRAINT FK_OPD_VISIT_APPOINTMENT_ID REFERENCES HMS_APPOINTMENT(APPOINTMENT_ID),
    VISIT_DATE             DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    VISIT_TIME             TIMESTAMP DEFAULT SYSTIMESTAMP,
    TOKEN_NO               NUMBER,
    VISIT_TYPE             VARCHAR2(20) DEFAULT 'NEW' CHECK (VISIT_TYPE IN ('NEW','FOLLOWUP','REFERRAL','EMERGENCY','REVIEW')),
    IS_FOLLOWUP            CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_FOLLOWUP IN ('Y','N')),
    PREVIOUS_VISIT_ID      NUMBER CONSTRAINT FK_OPD_VISIT_PREVIOUS_VISIT_ID REFERENCES HMS_OPD_VISIT(VISIT_ID),
    CONSULTATION_FEE       NUMBER(12,2) DEFAULT 0,
    DISCOUNT_AMOUNT        NUMBER(12,2) DEFAULT 0,
    NET_FEE                NUMBER(12,2) DEFAULT 0,
    VISIT_STATUS           VARCHAR2(20) DEFAULT 'WAITING' CHECK (VISIT_STATUS IN ('WAITING','IN_CONSULTATION','COMPLETED','CANCELLED','ADMITTED')),
    PAYMENT_STATUS         VARCHAR2(20) DEFAULT 'UNPAID' CHECK (PAYMENT_STATUS IN ('UNPAID','PAID','PARTIAL','FREE')),
    REMARKS                VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OPD_VISIT PRIMARY KEY (VISIT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_OPD_VISIT_NO UNIQUE (VISIT_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_OPD_VITALS
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OPD_VITALS (
    VITAL_ID               NUMBER DEFAULT SEQ_OPD_VITALS.NEXTVAL NOT NULL,
    VISIT_ID               NUMBER NOT NULL CONSTRAINT FK_OPD_VITALS_VISIT_ID REFERENCES HMS_OPD_VISIT(VISIT_ID),
    BP_SYSTOLIC            NUMBER(3),
    BP_DIASTOLIC           NUMBER(3),
    PULSE_RATE             NUMBER(3),
    TEMPERATURE_F          NUMBER(5,2),
    RESPIRATORY_RATE       NUMBER(3),
    SPO2                   NUMBER(3),
    WEIGHT_KG              NUMBER(6,2),
    HEIGHT_CM              NUMBER(6,2),
    BMI                    NUMBER(5,2),
    BLOOD_SUGAR            NUMBER(6,2),
    RECORDED_BY            NUMBER CONSTRAINT FK_OPD_VITALS_RECORDED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    RECORDED_TIME          TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OPD_VITALS PRIMARY KEY (VITAL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_OPD_CONSULTATION
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OPD_CONSULTATION (
    CONSULTATION_ID        NUMBER DEFAULT SEQ_OPD_CONSULTATION.NEXTVAL NOT NULL,
    VISIT_ID               NUMBER NOT NULL CONSTRAINT FK_OPD_CONSULTATION_VISIT_ID REFERENCES HMS_OPD_VISIT(VISIT_ID),
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_OPD_CONSULTATION_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    CHIEF_COMPLAINT        VARCHAR2(2000),
    HISTORY_OF_ILLNESS     VARCHAR2(4000),
    EXAMINATION_NOTES      VARCHAR2(4000),
    PROVISIONAL_DIAGNOSIS  VARCHAR2(1000),
    FINAL_DIAGNOSIS        VARCHAR2(1000),
    ICD_ID                 NUMBER CONSTRAINT FK_OPD_CONSULTATION_ICD_ID REFERENCES HMS_ICD_MASTER(ICD_ID),
    ADVICE                 VARCHAR2(4000),
    FOLLOWUP_DATE          DATE,
    ADMISSION_ADVISED      CHAR(1) DEFAULT 'N' NOT NULL CHECK (ADMISSION_ADVISED IN ('Y','N')),
    REFERRED_TO_DOCTOR_ID  NUMBER CONSTRAINT FK_OPDCON_REFERRED_TO_DOCTOR_I REFERENCES HMS_DOCTOR(DOCTOR_ID),
    CONSULTATION_START     TIMESTAMP,
    CONSULTATION_END       TIMESTAMP,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OPD_CONSULTATION PRIMARY KEY (CONSULTATION_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_OPD_PRESCRIPTION
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OPD_PRESCRIPTION (
    PRESCRIPTION_ID        NUMBER DEFAULT SEQ_OPD_PRESCRIPTION.NEXTVAL NOT NULL,
    VISIT_ID               NUMBER NOT NULL CONSTRAINT FK_OPD_PRESCRIPTION_VISIT_ID REFERENCES HMS_OPD_VISIT(VISIT_ID),
    CONSULTATION_ID        NUMBER CONSTRAINT FK_OPDPRE_CONSULTATION_ID REFERENCES HMS_OPD_CONSULTATION(CONSULTATION_ID),
    PRESCRIPTION_NO        VARCHAR2(30),
    PRESCRIPTION_DATE      DATE DEFAULT SYSDATE,
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_OPD_PRESCRIPTION_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    NOTES                  VARCHAR2(2000),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OPD_PRESCRIPTION PRIMARY KEY (PRESCRIPTION_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_OPD_PRESCRIPTION_DTL  : FREQUENCY e.g. 1+0+1
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OPD_PRESCRIPTION_DTL (
    PRESCRIPTION_DTL_ID    NUMBER DEFAULT SEQ_OPD_PRESCRIPTION_DTL.NEXTVAL NOT NULL,
    PRESCRIPTION_ID        NUMBER NOT NULL CONSTRAINT FK_OPDPREDTL_PRESCRIPTION_ID REFERENCES HMS_OPD_PRESCRIPTION(PRESCRIPTION_ID),
    ITEM_ID                NUMBER,
    MEDICINE_NAME          VARCHAR2(300) NOT NULL,
    DOSAGE                 VARCHAR2(100),
    FREQUENCY              VARCHAR2(50),
    ROUTE                  VARCHAR2(50),
    DURATION_DAYS          NUMBER,
    MEAL_INSTRUCTION       VARCHAR2(50) CHECK (MEAL_INSTRUCTION IN ('BEFORE_MEAL','AFTER_MEAL','WITH_MEAL','EMPTY_STOMACH','ANY')),
    QUANTITY               NUMBER,
    INSTRUCTIONS           VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OPD_PRESCRIPTION_DTL PRIMARY KEY (PRESCRIPTION_DTL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_OPD_PRESCRIPTION_DTL IS 'FREQUENCY e.g. 1+0+1';

-- ----------------------------------------------------------------------------
-- HMS_OPD_PROCEDURE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OPD_PROCEDURE (
    OPD_PROC_ID            NUMBER DEFAULT SEQ_OPD_PROCEDURE.NEXTVAL NOT NULL,
    VISIT_ID               NUMBER NOT NULL CONSTRAINT FK_OPD_PROCEDURE_VISIT_ID REFERENCES HMS_OPD_VISIT(VISIT_ID),
    SERVICE_ID             NUMBER NOT NULL CONSTRAINT FK_OPD_PROCEDURE_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    PERFORMED_BY           NUMBER CONSTRAINT FK_OPD_PROCEDURE_PERFORMED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    PROCEDURE_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP,
    QUANTITY               NUMBER DEFAULT 1,
    CHARGE_AMOUNT          NUMBER(12,2),
    NOTES                  VARCHAR2(1000),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OPD_PROCEDURE PRIMARY KEY (OPD_PROC_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

