/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 07_ipd_tables.sql
 Purpose   : Tables - IPD (In Patient Department)
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : IPD (In Patient Department)

-- ----------------------------------------------------------------------------
-- HMS_WARD
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_WARD (
    WARD_ID                NUMBER DEFAULT SEQ_WARD.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_WARD_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    DEPT_ID                NUMBER CONSTRAINT FK_WARD_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    WARD_CODE              VARCHAR2(20) NOT NULL,
    WARD_NAME              VARCHAR2(200) NOT NULL,
    WARD_TYPE              VARCHAR2(30) CHECK (WARD_TYPE IN ('GENERAL','CABIN','ICU','CCU','NICU','PICU','HDU','ISOLATION','MATERNITY','POST_OP','EMERGENCY')),
    FLOOR_NO               VARCHAR2(20),
    TOTAL_BEDS             NUMBER DEFAULT 0,
    GENDER_ALLOWED         VARCHAR2(10) DEFAULT 'ALL' CHECK (GENDER_ALLOWED IN ('MALE','FEMALE','ALL')),
    NURSE_STATION_PHONE    VARCHAR2(20),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_WARD PRIMARY KEY (WARD_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_WARD UNIQUE (BRANCH_ID, WARD_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_BED
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BED (
    BED_ID                 NUMBER DEFAULT SEQ_BED.NEXTVAL NOT NULL,
    WARD_ID                NUMBER NOT NULL CONSTRAINT FK_BED_WARD_ID REFERENCES HMS_WARD(WARD_ID),
    BED_NO                 VARCHAR2(20) NOT NULL,
    BED_TYPE               VARCHAR2(30) CHECK (BED_TYPE IN ('GENERAL','CABIN_AC','CABIN_NON_AC','SUITE','ICU','CCU','NICU','CRADLE')),
    SERVICE_ID             NUMBER CONSTRAINT FK_BED_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    DAILY_CHARGE           NUMBER(12,2) DEFAULT 0,
    BED_STATUS             VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (BED_STATUS IN ('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE','CLEANING')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BED PRIMARY KEY (BED_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_BED UNIQUE (WARD_ID, BED_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_IPD_ADMISSION
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_IPD_ADMISSION (
    ADMISSION_ID           NUMBER DEFAULT SEQ_IPD_ADMISSION.NEXTVAL NOT NULL,
    ADMISSION_NO           VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_IPD_ADMISSION_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_IPD_ADMISSION_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    OPD_VISIT_ID           NUMBER CONSTRAINT FK_IPD_ADMISSION_OPD_VISIT_ID REFERENCES HMS_OPD_VISIT(VISIT_ID),
    ADMITTING_DOCTOR_ID    NUMBER NOT NULL CONSTRAINT FK_IPDADM_ADMITTING_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    CONSULTANT_ID          NUMBER CONSTRAINT FK_IPD_ADMISSION_CONSULTANT_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    DEPT_ID                NUMBER NOT NULL CONSTRAINT FK_IPD_ADMISSION_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    WARD_ID                NUMBER NOT NULL CONSTRAINT FK_IPD_ADMISSION_WARD_ID REFERENCES HMS_WARD(WARD_ID),
    BED_ID                 NUMBER NOT NULL CONSTRAINT FK_IPD_ADMISSION_BED_ID REFERENCES HMS_BED(BED_ID),
    ADMISSION_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ADMISSION_TYPE         VARCHAR2(20) DEFAULT 'PLANNED' CHECK (ADMISSION_TYPE IN ('PLANNED','EMERGENCY','TRANSFER','DAY_CARE','MATERNITY')),
    ADMISSION_REASON       VARCHAR2(2000),
    PROVISIONAL_DIAGNOSIS  VARCHAR2(1000),
    ICD_ID                 NUMBER CONSTRAINT FK_IPD_ADMISSION_ICD_ID REFERENCES HMS_ICD_MASTER(ICD_ID),
    IS_MLC                 CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_MLC IN ('Y','N')),
    MLC_NO                 VARCHAR2(50),
    ATTENDANT_NAME         VARCHAR2(200),
    ATTENDANT_PHONE        VARCHAR2(50),
    ATTENDANT_RELATION     VARCHAR2(50),
    EXPECTED_STAY_DAYS     NUMBER,
    INSURANCE_POLICY_ID    NUMBER,
    ADMISSION_STATUS       VARCHAR2(20) DEFAULT 'ADMITTED' CHECK (ADMISSION_STATUS IN ('ADMITTED','DISCHARGE_INITIATED','DISCHARGED','LAMA','ABSCONDED','DEATH','REFERRED','CANCELLED')),
    DISCHARGE_DATE         TIMESTAMP,
    REMARKS                VARCHAR2(1000),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_IPD_ADMISSION PRIMARY KEY (ADMISSION_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_ADMISSION_NO UNIQUE (ADMISSION_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_BED_TRANSFER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BED_TRANSFER (
    TRANSFER_ID            NUMBER DEFAULT SEQ_BED_TRANSFER.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_BED_TRANSFER_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    FROM_BED_ID            NUMBER NOT NULL CONSTRAINT FK_BED_TRANSFER_FROM_BED_ID REFERENCES HMS_BED(BED_ID),
    TO_BED_ID              NUMBER NOT NULL CONSTRAINT FK_BED_TRANSFER_TO_BED_ID REFERENCES HMS_BED(BED_ID),
    TRANSFER_DATE          TIMESTAMP DEFAULT SYSTIMESTAMP,
    TRANSFER_REASON        VARCHAR2(500),
    AUTHORIZED_BY          NUMBER CONSTRAINT FK_BED_TRANSFER_AUTHORIZED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BED_TRANSFER PRIMARY KEY (TRANSFER_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_IPD_DOCTOR_VISIT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_IPD_DOCTOR_VISIT (
    IPD_VISIT_ID           NUMBER DEFAULT SEQ_IPD_DOCTOR_VISIT.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_IPDDOCVIS_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_IPD_DOCTOR_VISIT_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    VISIT_TIME             TIMESTAMP DEFAULT SYSTIMESTAMP,
    VISIT_TYPE             VARCHAR2(20) DEFAULT 'ROUTINE' CHECK (VISIT_TYPE IN ('ROUTINE','CALL','EMERGENCY','CONSULTANT')),
    PROGRESS_NOTES         VARCHAR2(4000),
    INSTRUCTIONS           VARCHAR2(2000),
    VISIT_CHARGE           NUMBER(12,2) DEFAULT 0,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_IPD_DOCTOR_VISIT PRIMARY KEY (IPD_VISIT_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_IPD_MEDICATION  : Doctor medication order (chart)
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_IPD_MEDICATION (
    MEDICATION_ID          NUMBER DEFAULT SEQ_IPD_MEDICATION.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_IPD_MEDICATION_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    ITEM_ID                NUMBER,
    MEDICINE_NAME          VARCHAR2(300) NOT NULL,
    DOSAGE                 VARCHAR2(100),
    ROUTE                  VARCHAR2(50),
    FREQUENCY              VARCHAR2(50),
    START_DATE             TIMESTAMP DEFAULT SYSTIMESTAMP,
    END_DATE               TIMESTAMP,
    ORDERED_BY             NUMBER CONSTRAINT FK_IPD_MEDICATION_ORDERED_BY REFERENCES HMS_DOCTOR(DOCTOR_ID),
    ORDER_STATUS           VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (ORDER_STATUS IN ('ACTIVE','STOPPED','COMPLETED','HOLD')),
    INSTRUCTIONS           VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_IPD_MEDICATION PRIMARY KEY (MEDICATION_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_IPD_MEDICATION IS 'Doctor medication order (chart)';

-- ----------------------------------------------------------------------------
-- HMS_IPD_MED_ADMINISTRATION  : Nurse medication administration record (MAR)
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_IPD_MED_ADMINISTRATION (
    ADMIN_ID               NUMBER DEFAULT SEQ_IPD_MED_ADMINISTRATION.NEXTVAL NOT NULL,
    MEDICATION_ID          NUMBER NOT NULL CONSTRAINT FK_IPDMEDADM_MEDICATION_ID REFERENCES HMS_IPD_MEDICATION(MEDICATION_ID),
    SCHEDULED_TIME         TIMESTAMP,
    GIVEN_TIME             TIMESTAMP,
    GIVEN_BY               NUMBER CONSTRAINT FK_IPDMEDADM_GIVEN_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    ADMIN_STATUS           VARCHAR2(20) DEFAULT 'PENDING' CHECK (ADMIN_STATUS IN ('PENDING','GIVEN','MISSED','REFUSED','HELD')),
    NOTES                  VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_IPD_MED_ADMINISTRATION PRIMARY KEY (ADMIN_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_IPD_MED_ADMINISTRATION IS 'Nurse medication administration record (MAR)';

-- ----------------------------------------------------------------------------
-- HMS_DISCHARGE_SUMMARY
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DISCHARGE_SUMMARY (
    SUMMARY_ID             NUMBER DEFAULT SEQ_DISCHARGE_SUMMARY.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_DISSUM_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    DISCHARGE_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP,
    DISCHARGE_TYPE         VARCHAR2(20) CHECK (DISCHARGE_TYPE IN ('NORMAL','LAMA','REFERRED','DEATH','ABSCONDED','DOR')),
    FINAL_DIAGNOSIS        VARCHAR2(2000),
    ICD_ID                 NUMBER CONSTRAINT FK_DISCHARGE_SUMMARY_ICD_ID REFERENCES HMS_ICD_MASTER(ICD_ID),
    TREATMENT_GIVEN        CLOB,
    PROCEDURES_DONE        VARCHAR2(2000),
    CONDITION_AT_DISCHARGE VARCHAR2(500),
    DISCHARGE_ADVICE       CLOB,
    DISCHARGE_MEDICATION   CLOB,
    FOLLOWUP_DATE          DATE,
    DISCHARGED_BY          NUMBER CONSTRAINT FK_DISSUM_DISCHARGED_BY REFERENCES HMS_DOCTOR(DOCTOR_ID),
    SUMMARY_STATUS         VARCHAR2(20) DEFAULT 'DRAFT' CHECK (SUMMARY_STATUS IN ('DRAFT','FINAL')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DISCHARGE_SUMMARY PRIMARY KEY (SUMMARY_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_DIS_SUMMARY UNIQUE (ADMISSION_ID)
)
TABLESPACE HMS_DATA
LOB (TREATMENT_GIVEN) STORE AS SECUREFILE (TABLESPACE HMS_LOB)
LOB (DISCHARGE_ADVICE) STORE AS SECUREFILE (TABLESPACE HMS_LOB)
LOB (DISCHARGE_MEDICATION) STORE AS SECUREFILE (TABLESPACE HMS_LOB);

