/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 08_lab_tables.sql
 Purpose   : Tables - DIAGNOSTIC & LABORATORY
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : DIAGNOSTIC & LABORATORY

-- ----------------------------------------------------------------------------
-- HMS_INVESTIGATION_ORDER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INVESTIGATION_ORDER (
    ORDER_ID               NUMBER DEFAULT SEQ_INVESTIGATION_ORDER.NEXTVAL NOT NULL,
    ORDER_NO               VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_INVORD_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_INVORD_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    OPD_VISIT_ID           NUMBER CONSTRAINT FK_INVORD_OPD_VISIT_ID REFERENCES HMS_OPD_VISIT(VISIT_ID),
    ADMISSION_ID           NUMBER CONSTRAINT FK_INVORD_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    ORDER_SOURCE           VARCHAR2(20) CHECK (ORDER_SOURCE IN ('OPD','IPD','EMERGENCY','EXTERNAL')),
    REFERRED_DOCTOR_ID     NUMBER CONSTRAINT FK_INVORD_REFERRED_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    ORDER_DATE             TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIORITY               VARCHAR2(20) DEFAULT 'ROUTINE' CHECK (PRIORITY IN ('ROUTINE','URGENT','STAT')),
    CLINICAL_NOTES         VARCHAR2(2000),
    ORDER_STATUS           VARCHAR2(20) DEFAULT 'ORDERED' CHECK (ORDER_STATUS IN ('ORDERED','PARTIAL','COMPLETED','CANCELLED')),
    TOTAL_AMOUNT           NUMBER(12,2) DEFAULT 0,
    DISCOUNT_AMOUNT        NUMBER(12,2) DEFAULT 0,
    NET_AMOUNT             NUMBER(12,2) DEFAULT 0,
    PAYMENT_STATUS         VARCHAR2(20) DEFAULT 'PENDING' CHECK (PAYMENT_STATUS IN ('PENDING','PAID','PARTIAL','CREDIT')),
    REMARKS                VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INVESTIGATION_ORDER PRIMARY KEY (ORDER_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_INV_ORDER_NO UNIQUE (ORDER_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_INVESTIGATION_ORDER_DTL
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INVESTIGATION_ORDER_DTL (
    ORDER_DTL_ID           NUMBER DEFAULT SEQ_INVESTIGATION_ORDER_DTL.NEXTVAL NOT NULL,
    ORDER_ID               NUMBER NOT NULL CONSTRAINT FK_INVORDDTL_ORDER_ID REFERENCES HMS_INVESTIGATION_ORDER(ORDER_ID),
    SERVICE_ID             NUMBER NOT NULL CONSTRAINT FK_INVORDDTL_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    SERVICE_NAME           VARCHAR2(300),
    CHARGE_AMOUNT          NUMBER(12,2) DEFAULT 0,
    DISCOUNT_AMOUNT        NUMBER(12,2) DEFAULT 0,
    NET_AMOUNT             NUMBER(12,2) DEFAULT 0,
    ITEM_STATUS            VARCHAR2(20) DEFAULT 'ORDERED' CHECK (ITEM_STATUS IN ('ORDERED','SAMPLE_COLLECTED','IN_PROCESS','RESULT_ENTERED','VERIFIED','DELIVERED','CANCELLED')),
    REPORTED_DATE          TIMESTAMP,
    REPORTED_BY            NUMBER CONSTRAINT FK_INVORDDTL_REPORTED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    VERIFIED_BY            NUMBER CONSTRAINT FK_INVORDDTL_VERIFIED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    VERIFIED_DATE          TIMESTAMP,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INVESTIGATION_ORDER_DTL PRIMARY KEY (ORDER_DTL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_LAB_PARAMETER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LAB_PARAMETER (
    PARAMETER_ID           NUMBER DEFAULT SEQ_LAB_PARAMETER.NEXTVAL NOT NULL,
    SERVICE_ID             NUMBER NOT NULL CONSTRAINT FK_LAB_PARAMETER_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    PARAMETER_CODE         VARCHAR2(30),
    PARAMETER_NAME         VARCHAR2(200) NOT NULL,
    UNIT                   VARCHAR2(50),
    RESULT_TYPE            VARCHAR2(20) DEFAULT 'NUMERIC' CHECK (RESULT_TYPE IN ('NUMERIC','TEXT','OPTION','MEMO')),
    METHOD_NAME            VARCHAR2(200),
    GROUP_NAME             VARCHAR2(100),
    DISPLAY_ORDER          NUMBER,
    IS_CALCULATED          CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_CALCULATED IN ('Y','N')),
    FORMULA                VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LAB_PARAMETER PRIMARY KEY (PARAMETER_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_LAB_REFERENCE_RANGE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LAB_REFERENCE_RANGE (
    RANGE_ID               NUMBER DEFAULT SEQ_LAB_REFERENCE_RANGE.NEXTVAL NOT NULL,
    PARAMETER_ID           NUMBER NOT NULL CONSTRAINT FK_LABREFRAN_PARAMETER_ID REFERENCES HMS_LAB_PARAMETER(PARAMETER_ID),
    GENDER                 VARCHAR2(10) DEFAULT 'ALL' CHECK (GENDER IN ('MALE','FEMALE','ALL')),
    AGE_FROM_DAYS          NUMBER DEFAULT 0,
    AGE_TO_DAYS            NUMBER DEFAULT 54750,
    MIN_VALUE              NUMBER,
    MAX_VALUE              NUMBER,
    CRITICAL_LOW           NUMBER,
    CRITICAL_HIGH          NUMBER,
    NORMAL_TEXT            VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LAB_REFERENCE_RANGE PRIMARY KEY (RANGE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_LAB_SAMPLE  : Barcode = SAMPLE_NO
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LAB_SAMPLE (
    SAMPLE_ID              NUMBER DEFAULT SEQ_LAB_SAMPLE.NEXTVAL NOT NULL,
    SAMPLE_NO              VARCHAR2(30) NOT NULL,
    ORDER_ID               NUMBER NOT NULL CONSTRAINT FK_LAB_SAMPLE_ORDER_ID REFERENCES HMS_INVESTIGATION_ORDER(ORDER_ID),
    ORDER_DTL_ID           NUMBER CONSTRAINT FK_LAB_SAMPLE_ORDER_DTL_ID REFERENCES HMS_INVESTIGATION_ORDER_DTL(ORDER_DTL_ID),
    SAMPLE_TYPE            VARCHAR2(50),
    CONTAINER_TYPE         VARCHAR2(50),
    COLLECTED_BY           NUMBER CONSTRAINT FK_LAB_SAMPLE_COLLECTED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    COLLECTION_TIME        TIMESTAMP,
    RECEIVED_BY            NUMBER CONSTRAINT FK_LAB_SAMPLE_RECEIVED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    RECEIVED_TIME          TIMESTAMP,
    SAMPLE_STATUS          VARCHAR2(20) DEFAULT 'PENDING' CHECK (SAMPLE_STATUS IN ('PENDING','COLLECTED','RECEIVED','REJECTED','PROCESSED')),
    REJECTION_REASON       VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LAB_SAMPLE PRIMARY KEY (SAMPLE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SAMPLE_NO UNIQUE (SAMPLE_NO)
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_LAB_SAMPLE IS 'Barcode = SAMPLE_NO';

-- ----------------------------------------------------------------------------
-- HMS_LAB_EQUIPMENT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LAB_EQUIPMENT (
    EQUIPMENT_ID           NUMBER DEFAULT SEQ_LAB_EQUIPMENT.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_LAB_EQUIPMENT_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    EQUIPMENT_CODE         VARCHAR2(30) NOT NULL,
    EQUIPMENT_NAME         VARCHAR2(200) NOT NULL,
    MANUFACTURER           VARCHAR2(200),
    MODEL_NO               VARCHAR2(100),
    SERIAL_NO              VARCHAR2(100),
    INTERFACE_TYPE         VARCHAR2(30),
    LAST_CALIBRATION       DATE,
    NEXT_CALIBRATION       DATE,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LAB_EQUIPMENT PRIMARY KEY (EQUIPMENT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_LAB_EQUIP UNIQUE (EQUIPMENT_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_LAB_RESULT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LAB_RESULT (
    RESULT_ID              NUMBER DEFAULT SEQ_LAB_RESULT.NEXTVAL NOT NULL,
    ORDER_DTL_ID           NUMBER NOT NULL CONSTRAINT FK_LAB_RESULT_ORDER_DTL_ID REFERENCES HMS_INVESTIGATION_ORDER_DTL(ORDER_DTL_ID),
    SAMPLE_ID              NUMBER CONSTRAINT FK_LAB_RESULT_SAMPLE_ID REFERENCES HMS_LAB_SAMPLE(SAMPLE_ID),
    PARAMETER_ID           NUMBER NOT NULL CONSTRAINT FK_LAB_RESULT_PARAMETER_ID REFERENCES HMS_LAB_PARAMETER(PARAMETER_ID),
    EQUIPMENT_ID           NUMBER CONSTRAINT FK_LAB_RESULT_EQUIPMENT_ID REFERENCES HMS_LAB_EQUIPMENT(EQUIPMENT_ID),
    RESULT_VALUE           VARCHAR2(1000),
    RESULT_NUMERIC         NUMBER,
    UNIT                   VARCHAR2(50),
    REFERENCE_RANGE        VARCHAR2(200),
    IS_ABNORMAL            CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_ABNORMAL IN ('Y','N')),
    IS_CRITICAL            CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_CRITICAL IN ('Y','N')),
    RESULT_FLAG            VARCHAR2(10) CHECK (RESULT_FLAG IN ('L','H','LL','HH','N')),
    ENTERED_BY             NUMBER CONSTRAINT FK_LAB_RESULT_ENTERED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    ENTERED_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP,
    VERIFIED_BY            NUMBER CONSTRAINT FK_LAB_RESULT_VERIFIED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    VERIFIED_TIME          TIMESTAMP,
    RESULT_STATUS          VARCHAR2(20) DEFAULT 'ENTERED' CHECK (RESULT_STATUS IN ('ENTERED','VERIFIED','AMENDED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LAB_RESULT PRIMARY KEY (RESULT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_LAB_RESULT UNIQUE (ORDER_DTL_ID, PARAMETER_ID)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_LAB_RESULT_AMENDMENT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LAB_RESULT_AMENDMENT (
    AMENDMENT_ID           NUMBER DEFAULT SEQ_LAB_RESULT_AMENDMENT.NEXTVAL NOT NULL,
    RESULT_ID              NUMBER NOT NULL CONSTRAINT FK_LABRESAME_RESULT_ID REFERENCES HMS_LAB_RESULT(RESULT_ID),
    OLD_VALUE              VARCHAR2(1000),
    NEW_VALUE              VARCHAR2(1000),
    AMEND_REASON           VARCHAR2(500) NOT NULL,
    AMENDED_BY             NUMBER CONSTRAINT FK_LABRESAME_AMENDED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    AMENDED_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LAB_RESULT_AMENDMENT PRIMARY KEY (AMENDMENT_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

