/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 09_radiology_tables.sql
 Purpose   : Tables - RADIOLOGY / IMAGING
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : RADIOLOGY / IMAGING

-- ----------------------------------------------------------------------------
-- HMS_RADIOLOGY_ORDER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_RADIOLOGY_ORDER (
    RAD_ORDER_ID           NUMBER DEFAULT SEQ_RADIOLOGY_ORDER.NEXTVAL NOT NULL,
    ORDER_DTL_ID           NUMBER NOT NULL CONSTRAINT FK_RADORD_ORDER_DTL_ID REFERENCES HMS_INVESTIGATION_ORDER_DTL(ORDER_DTL_ID),
    MODALITY               VARCHAR2(20) CHECK (MODALITY IN ('XRAY','USG','CT','MRI','ECG','ECHO','MAMMO','ENDOSCOPY','OTHER')),
    BODY_PART              VARCHAR2(100),
    SCHEDULED_TIME         TIMESTAMP,
    PERFORMED_TIME         TIMESTAMP,
    TECHNICIAN_ID          NUMBER CONSTRAINT FK_RADORD_TECHNICIAN_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    RADIOLOGIST_ID         NUMBER CONSTRAINT FK_RADORD_RADIOLOGIST_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    FINDINGS               CLOB,
    IMPRESSION             VARCHAR2(4000),
    REPORT_STATUS          VARCHAR2(20) DEFAULT 'PENDING' CHECK (REPORT_STATUS IN ('PENDING','SCANNED','DRAFT','FINAL','DELIVERED')),
    PACS_STUDY_UID         VARCHAR2(200),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_RADIOLOGY_ORDER PRIMARY KEY (RAD_ORDER_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA
LOB (FINDINGS) STORE AS SECUREFILE (TABLESPACE HMS_LOB);

-- ----------------------------------------------------------------------------
-- HMS_RADIOLOGY_IMAGE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_RADIOLOGY_IMAGE (
    IMAGE_ID               NUMBER DEFAULT SEQ_RADIOLOGY_IMAGE.NEXTVAL NOT NULL,
    RAD_ORDER_ID           NUMBER NOT NULL CONSTRAINT FK_RADIMA_RAD_ORDER_ID REFERENCES HMS_RADIOLOGY_ORDER(RAD_ORDER_ID),
    IMAGE_FILE             BLOB,
    FILE_NAME              VARCHAR2(300),
    MIME_TYPE              VARCHAR2(100),
    IMAGE_DESC             VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_RADIOLOGY_IMAGE PRIMARY KEY (IMAGE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA
LOB (IMAGE_FILE) STORE AS SECUREFILE (TABLESPACE HMS_LOB);

-- ----------------------------------------------------------------------------
-- HMS_REPORT_TEMPLATE  : Radiology / USG report template
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_REPORT_TEMPLATE (
    TEMPLATE_ID            NUMBER DEFAULT SEQ_REPORT_TEMPLATE.NEXTVAL NOT NULL,
    SERVICE_ID             NUMBER CONSTRAINT FK_REPORT_TEMPLATE_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    TEMPLATE_NAME          VARCHAR2(200) NOT NULL,
    TEMPLATE_BODY          CLOB,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_REPORT_TEMPLATE PRIMARY KEY (TEMPLATE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA
LOB (TEMPLATE_BODY) STORE AS SECUREFILE (TABLESPACE HMS_LOB);
COMMENT ON TABLE HMS_REPORT_TEMPLATE IS 'Radiology / USG report template';

