/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 10_pharmacy_tables.sql
 Purpose   : Tables - PHARMACY
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : PHARMACY

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_CATEGORY  : Tablet, Capsule, Syrup, Injection ...
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_CATEGORY (
    PH_CATEGORY_ID         NUMBER DEFAULT SEQ_PHARMA_CATEGORY.NEXTVAL NOT NULL,
    CATEGORY_NAME          VARCHAR2(200) NOT NULL,
    PARENT_ID              NUMBER CONSTRAINT FK_PHARMA_CATEGORY_PARENT_ID REFERENCES HMS_PHARMA_CATEGORY(PH_CATEGORY_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_CATEGORY PRIMARY KEY (PH_CATEGORY_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_PHARMA_CATEGORY IS 'Tablet, Capsule, Syrup, Injection ...';

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_GENERIC
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_GENERIC (
    GENERIC_ID             NUMBER DEFAULT SEQ_PHARMA_GENERIC.NEXTVAL NOT NULL,
    GENERIC_NAME           VARCHAR2(300) NOT NULL,
    DRUG_CLASS             VARCHAR2(200),
    INDICATIONS            VARCHAR2(2000),
    CONTRAINDICATIONS      VARCHAR2(2000),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_GENERIC PRIMARY KEY (GENERIC_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_GENERIC UNIQUE (GENERIC_NAME)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_MANUFACTURER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_MANUFACTURER (
    MANUFACTURER_ID        NUMBER DEFAULT SEQ_PHARMA_MANUFACTURER.NEXTVAL NOT NULL,
    MANUFACTURER_NAME      VARCHAR2(300) NOT NULL,
    COUNTRY                VARCHAR2(100) DEFAULT 'Bangladesh',
    CONTACT_PERSON         VARCHAR2(200),
    PHONE                  VARCHAR2(50),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_MANUFACTURER PRIMARY KEY (MANUFACTURER_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_MANUFACTURER UNIQUE (MANUFACTURER_NAME)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_ITEM
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_ITEM (
    ITEM_ID                NUMBER DEFAULT SEQ_PHARMA_ITEM.NEXTVAL NOT NULL,
    ITEM_CODE              VARCHAR2(30) NOT NULL,
    ITEM_NAME              VARCHAR2(300) NOT NULL,
    GENERIC_ID             NUMBER CONSTRAINT FK_PHARMA_ITEM_GENERIC_ID REFERENCES HMS_PHARMA_GENERIC(GENERIC_ID),
    PH_CATEGORY_ID         NUMBER CONSTRAINT FK_PHARMA_ITEM_PH_CATEGORY_ID REFERENCES HMS_PHARMA_CATEGORY(PH_CATEGORY_ID),
    MANUFACTURER_ID        NUMBER CONSTRAINT FK_PHARMA_ITEM_MANUFACTURER_ID REFERENCES HMS_PHARMA_MANUFACTURER(MANUFACTURER_ID),
    STRENGTH               VARCHAR2(100),
    DOSAGE_FORM            VARCHAR2(50),
    UNIT_OF_MEASURE        VARCHAR2(30),
    PACK_SIZE              NUMBER DEFAULT 1,
    PURCHASE_PRICE         NUMBER(12,2),
    MRP                    NUMBER(12,2),
    VAT_PERCENT            NUMBER(5,2) DEFAULT 0,
    REORDER_LEVEL          NUMBER DEFAULT 0,
    BARCODE                VARCHAR2(100),
    RACK_NO                VARCHAR2(30),
    IS_NARCOTIC            CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_NARCOTIC IN ('Y','N')),
    IS_ANTIBIOTIC          CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_ANTIBIOTIC IN ('Y','N')),
    REQUIRES_PRESCRIPTION  CHAR(1) DEFAULT 'Y' NOT NULL CHECK (REQUIRES_PRESCRIPTION IN ('Y','N')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_ITEM PRIMARY KEY (ITEM_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_ITEM_CODE UNIQUE (ITEM_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_SUPPLIER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_SUPPLIER (
    SUPPLIER_ID            NUMBER DEFAULT SEQ_PHARMA_SUPPLIER.NEXTVAL NOT NULL,
    SUPPLIER_CODE          VARCHAR2(30) NOT NULL,
    SUPPLIER_NAME          VARCHAR2(300) NOT NULL,
    CONTACT_PERSON         VARCHAR2(200),
    PHONE                  VARCHAR2(50),
    EMAIL                  VARCHAR2(150),
    ADDRESS                VARCHAR2(500),
    TRADE_LICENSE          VARCHAR2(100),
    DRUG_LICENSE           VARCHAR2(100),
    CREDIT_DAYS            NUMBER DEFAULT 0,
    OPENING_BALANCE        NUMBER(14,2) DEFAULT 0,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_SUPPLIER PRIMARY KEY (SUPPLIER_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SUPPLIER_CODE UNIQUE (SUPPLIER_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_STORE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_STORE (
    STORE_ID               NUMBER DEFAULT SEQ_PHARMA_STORE.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_PHARMA_STORE_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    STORE_CODE             VARCHAR2(30) NOT NULL,
    STORE_NAME             VARCHAR2(200) NOT NULL,
    STORE_TYPE             VARCHAR2(20) CHECK (STORE_TYPE IN ('MAIN','OPD','IPD','OT','EMERGENCY','WARD')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_STORE PRIMARY KEY (STORE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_PH_STORE UNIQUE (STORE_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_PURCHASE_ORDER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_PURCHASE_ORDER (
    PO_ID                  NUMBER DEFAULT SEQ_PHARMA_PURCHASE_ORDER.NEXTVAL NOT NULL,
    PO_NO                  VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_PHAPURORD_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    SUPPLIER_ID            NUMBER NOT NULL CONSTRAINT FK_PHAPURORD_SUPPLIER_ID REFERENCES HMS_PHARMA_SUPPLIER(SUPPLIER_ID),
    PO_DATE                DATE DEFAULT SYSDATE,
    EXPECTED_DATE          DATE,
    TOTAL_AMOUNT           NUMBER(14,2) DEFAULT 0,
    PO_STATUS              VARCHAR2(20) DEFAULT 'DRAFT' CHECK (PO_STATUS IN ('DRAFT','APPROVED','PARTIAL','RECEIVED','CANCELLED')),
    APPROVED_BY            NUMBER CONSTRAINT FK_PHAPURORD_APPROVED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    REMARKS                VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_PURCHASE_ORDER PRIMARY KEY (PO_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_PO_NO UNIQUE (PO_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_PO_DTL
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_PO_DTL (
    PO_DTL_ID              NUMBER DEFAULT SEQ_PHARMA_PO_DTL.NEXTVAL NOT NULL,
    PO_ID                  NUMBER NOT NULL CONSTRAINT FK_PHARMA_PO_DTL_PO_ID REFERENCES HMS_PHARMA_PURCHASE_ORDER(PO_ID),
    ITEM_ID                NUMBER NOT NULL CONSTRAINT FK_PHARMA_PO_DTL_ITEM_ID REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
    ORDER_QTY              NUMBER NOT NULL,
    RECEIVED_QTY           NUMBER DEFAULT 0,
    UNIT_PRICE             NUMBER(12,2),
    LINE_TOTAL             NUMBER(14,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_PO_DTL PRIMARY KEY (PO_DTL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_GRN  : Goods Receive Note
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_GRN (
    GRN_ID                 NUMBER DEFAULT SEQ_PHARMA_GRN.NEXTVAL NOT NULL,
    GRN_NO                 VARCHAR2(30) NOT NULL,
    PO_ID                  NUMBER CONSTRAINT FK_PHARMA_GRN_PO_ID REFERENCES HMS_PHARMA_PURCHASE_ORDER(PO_ID),
    SUPPLIER_ID            NUMBER NOT NULL CONSTRAINT FK_PHARMA_GRN_SUPPLIER_ID REFERENCES HMS_PHARMA_SUPPLIER(SUPPLIER_ID),
    STORE_ID               NUMBER NOT NULL CONSTRAINT FK_PHARMA_GRN_STORE_ID REFERENCES HMS_PHARMA_STORE(STORE_ID),
    GRN_DATE               DATE DEFAULT SYSDATE,
    INVOICE_NO             VARCHAR2(50),
    INVOICE_DATE           DATE,
    TOTAL_AMOUNT           NUMBER(14,2) DEFAULT 0,
    DISCOUNT_AMOUNT        NUMBER(14,2) DEFAULT 0,
    VAT_AMOUNT             NUMBER(14,2) DEFAULT 0,
    NET_AMOUNT             NUMBER(14,2) DEFAULT 0,
    GRN_STATUS             VARCHAR2(20) DEFAULT 'DRAFT' CHECK (GRN_STATUS IN ('DRAFT','POSTED','CANCELLED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_GRN PRIMARY KEY (GRN_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_GRN_NO UNIQUE (GRN_NO)
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_PHARMA_GRN IS 'Goods Receive Note';

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_GRN_DTL
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_GRN_DTL (
    GRN_DTL_ID             NUMBER DEFAULT SEQ_PHARMA_GRN_DTL.NEXTVAL NOT NULL,
    GRN_ID                 NUMBER NOT NULL CONSTRAINT FK_PHARMA_GRN_DTL_GRN_ID REFERENCES HMS_PHARMA_GRN(GRN_ID),
    ITEM_ID                NUMBER NOT NULL CONSTRAINT FK_PHARMA_GRN_DTL_ITEM_ID REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
    BATCH_NO               VARCHAR2(50) NOT NULL,
    MFG_DATE               DATE,
    EXPIRY_DATE            DATE NOT NULL,
    QUANTITY               NUMBER NOT NULL,
    FREE_QTY               NUMBER DEFAULT 0,
    UNIT_COST              NUMBER(12,2),
    MRP                    NUMBER(12,2),
    LINE_TOTAL             NUMBER(14,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_GRN_DTL PRIMARY KEY (GRN_DTL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_STOCK
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_STOCK (
    STOCK_ID               NUMBER DEFAULT SEQ_PHARMA_STOCK.NEXTVAL NOT NULL,
    STORE_ID               NUMBER NOT NULL CONSTRAINT FK_PHARMA_STOCK_STORE_ID REFERENCES HMS_PHARMA_STORE(STORE_ID),
    ITEM_ID                NUMBER NOT NULL CONSTRAINT FK_PHARMA_STOCK_ITEM_ID REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
    BATCH_NO               VARCHAR2(50) NOT NULL,
    EXPIRY_DATE            DATE NOT NULL,
    QTY_AVAILABLE          NUMBER DEFAULT 0 NOT NULL,
    UNIT_COST              NUMBER(12,2),
    MRP                    NUMBER(12,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_STOCK PRIMARY KEY (STOCK_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_PH_STOCK UNIQUE (STORE_ID, ITEM_ID, BATCH_NO),
    CONSTRAINT CK_PH_STOCK_QTY CHECK (QTY_AVAILABLE >= 0)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_SALE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_SALE (
    SALE_ID                NUMBER DEFAULT SEQ_PHARMA_SALE.NEXTVAL NOT NULL,
    SALE_NO                VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_PHARMA_SALE_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    STORE_ID               NUMBER NOT NULL CONSTRAINT FK_PHARMA_SALE_STORE_ID REFERENCES HMS_PHARMA_STORE(STORE_ID),
    PATIENT_ID             NUMBER CONSTRAINT FK_PHARMA_SALE_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    ADMISSION_ID           NUMBER CONSTRAINT FK_PHARMA_SALE_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    PRESCRIPTION_ID        NUMBER CONSTRAINT FK_PHARMA_SALE_PRESCRIPTION_ID REFERENCES HMS_OPD_PRESCRIPTION(PRESCRIPTION_ID),
    CUSTOMER_NAME          VARCHAR2(200),
    CUSTOMER_PHONE         VARCHAR2(50),
    SALE_TYPE              VARCHAR2(20) DEFAULT 'OTC' CHECK (SALE_TYPE IN ('OTC','OPD','IPD','EMERGENCY','OT')),
    SALE_DATE              TIMESTAMP DEFAULT SYSTIMESTAMP,
    GROSS_AMOUNT           NUMBER(14,2) DEFAULT 0,
    DISCOUNT_AMOUNT        NUMBER(14,2) DEFAULT 0,
    VAT_AMOUNT             NUMBER(14,2) DEFAULT 0,
    NET_AMOUNT             NUMBER(14,2) DEFAULT 0,
    PAID_AMOUNT            NUMBER(14,2) DEFAULT 0,
    PAYMENT_MODE           VARCHAR2(20),
    SALE_STATUS            VARCHAR2(20) DEFAULT 'COMPLETED' CHECK (SALE_STATUS IN ('DRAFT','COMPLETED','CANCELLED','IPD_CREDIT')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_SALE PRIMARY KEY (SALE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SALE_NO UNIQUE (SALE_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_SALE_DTL
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_SALE_DTL (
    SALE_DTL_ID            NUMBER DEFAULT SEQ_PHARMA_SALE_DTL.NEXTVAL NOT NULL,
    SALE_ID                NUMBER NOT NULL CONSTRAINT FK_PHARMA_SALE_DTL_SALE_ID REFERENCES HMS_PHARMA_SALE(SALE_ID),
    ITEM_ID                NUMBER NOT NULL CONSTRAINT FK_PHARMA_SALE_DTL_ITEM_ID REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
    STOCK_ID               NUMBER NOT NULL CONSTRAINT FK_PHARMA_SALE_DTL_STOCK_ID REFERENCES HMS_PHARMA_STOCK(STOCK_ID),
    BATCH_NO               VARCHAR2(50),
    QUANTITY               NUMBER NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE             NUMBER(12,2) NOT NULL,
    DISCOUNT_AMOUNT        NUMBER(12,2) DEFAULT 0,
    LINE_TOTAL             NUMBER(14,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_SALE_DTL PRIMARY KEY (SALE_DTL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_SALE_RETURN
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_SALE_RETURN (
    RETURN_ID              NUMBER DEFAULT SEQ_PHARMA_SALE_RETURN.NEXTVAL NOT NULL,
    RETURN_NO              VARCHAR2(30) NOT NULL,
    SALE_ID                NUMBER NOT NULL CONSTRAINT FK_PHARMA_SALE_RETURN_SALE_ID REFERENCES HMS_PHARMA_SALE(SALE_ID),
    SALE_DTL_ID            NUMBER NOT NULL CONSTRAINT FK_PHASALRET_SALE_DTL_ID REFERENCES HMS_PHARMA_SALE_DTL(SALE_DTL_ID),
    RETURN_QTY             NUMBER NOT NULL CHECK (RETURN_QTY > 0),
    REFUND_AMOUNT          NUMBER(12,2),
    RETURN_DATE            TIMESTAMP DEFAULT SYSTIMESTAMP,
    RETURN_REASON          VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_SALE_RETURN PRIMARY KEY (RETURN_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_PH_RETURN_NO UNIQUE (RETURN_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PHARMA_TRANSACTION  : Stock ledger (sob movement ekhane log hobe)
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PHARMA_TRANSACTION (
    TXN_ID                 NUMBER DEFAULT SEQ_PHARMA_TRANSACTION.NEXTVAL NOT NULL,
    STORE_ID               NUMBER NOT NULL CONSTRAINT FK_PHARMA_TRANSACTION_STORE_ID REFERENCES HMS_PHARMA_STORE(STORE_ID),
    ITEM_ID                NUMBER NOT NULL CONSTRAINT FK_PHARMA_TRANSACTION_ITEM_ID REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
    STOCK_ID               NUMBER CONSTRAINT FK_PHARMA_TRANSACTION_STOCK_ID REFERENCES HMS_PHARMA_STOCK(STOCK_ID),
    BATCH_NO               VARCHAR2(50),
    TXN_TYPE               VARCHAR2(20) NOT NULL CHECK (TXN_TYPE IN ('GRN','SALE','SALE_RETURN','TRANSFER_IN','TRANSFER_OUT','ADJUST_PLUS','ADJUST_MINUS','EXPIRED','DAMAGE','OPENING')),
    TXN_QTY                NUMBER NOT NULL,
    REF_TYPE               VARCHAR2(30),
    REF_ID                 NUMBER,
    TXN_DATE               TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PHARMA_TRANSACTION PRIMARY KEY (TXN_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_PHARMA_TRANSACTION IS 'Stock ledger (sob movement ekhane log hobe)';

