/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 11_ot_tables.sql
 Purpose   : Tables - OPERATION THEATRE (OT)
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : OPERATION THEATRE (OT)

-- ----------------------------------------------------------------------------
-- HMS_OT_MASTER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OT_MASTER (
    OT_ID                  NUMBER DEFAULT SEQ_OT_MASTER.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_OT_MASTER_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    OT_CODE                VARCHAR2(20) NOT NULL,
    OT_NAME                VARCHAR2(100) NOT NULL,
    OT_TYPE                VARCHAR2(30) CHECK (OT_TYPE IN ('MAJOR','MINOR','CARDIAC','NEURO','ORTHO','GYNAE','EMERGENCY')),
    FLOOR_NO               VARCHAR2(20),
    OT_STATUS              VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (OT_STATUS IN ('AVAILABLE','IN_USE','CLEANING','MAINTENANCE')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OT_MASTER PRIMARY KEY (OT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_OT_CODE UNIQUE (OT_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_SURGERY_MASTER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_SURGERY_MASTER (
    SURGERY_ID             NUMBER DEFAULT SEQ_SURGERY_MASTER.NEXTVAL NOT NULL,
    SERVICE_ID             NUMBER CONSTRAINT FK_SURGERY_MASTER_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    SURGERY_CODE           VARCHAR2(30) NOT NULL,
    SURGERY_NAME           VARCHAR2(300) NOT NULL,
    SURGERY_CATEGORY       VARCHAR2(30) CHECK (SURGERY_CATEGORY IN ('MINOR','MAJOR','SUPER_MAJOR')),
    EST_DURATION_MIN       NUMBER,
    SURGEON_FEE            NUMBER(12,2),
    ANESTHESIA_FEE         NUMBER(12,2),
    OT_CHARGE              NUMBER(12,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_SURGERY_MASTER PRIMARY KEY (SURGERY_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SURGERY_CODE UNIQUE (SURGERY_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_OT_BOOKING
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OT_BOOKING (
    BOOKING_ID             NUMBER DEFAULT SEQ_OT_BOOKING.NEXTVAL NOT NULL,
    BOOKING_NO             VARCHAR2(30) NOT NULL,
    ADMISSION_ID           NUMBER CONSTRAINT FK_OT_BOOKING_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_OT_BOOKING_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    OT_ID                  NUMBER NOT NULL CONSTRAINT FK_OT_BOOKING_OT_ID REFERENCES HMS_OT_MASTER(OT_ID),
    SURGERY_ID             NUMBER NOT NULL CONSTRAINT FK_OT_BOOKING_SURGERY_ID REFERENCES HMS_SURGERY_MASTER(SURGERY_ID),
    PRIMARY_SURGEON_ID     NUMBER NOT NULL CONSTRAINT FK_OTBOO_PRIMARY_SURGEON_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    ANESTHETIST_ID         NUMBER CONSTRAINT FK_OT_BOOKING_ANESTHETIST_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    ANESTHESIA_TYPE        VARCHAR2(30) CHECK (ANESTHESIA_TYPE IN ('GENERAL','SPINAL','EPIDURAL','LOCAL','REGIONAL','SEDATION')),
    SCHEDULED_START        TIMESTAMP NOT NULL,
    SCHEDULED_END          TIMESTAMP,
    ACTUAL_START           TIMESTAMP,
    ACTUAL_END             TIMESTAMP,
    PRIORITY               VARCHAR2(20) DEFAULT 'ELECTIVE' CHECK (PRIORITY IN ('ELECTIVE','URGENT','EMERGENCY')),
    PRE_OP_DIAGNOSIS       VARCHAR2(1000),
    BOOKING_STATUS         VARCHAR2(20) DEFAULT 'SCHEDULED' CHECK (BOOKING_STATUS IN ('SCHEDULED','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','POSTPONED')),
    CONSENT_TAKEN          CHAR(1) DEFAULT 'N' CHECK (CONSENT_TAKEN IN ('Y','N')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OT_BOOKING PRIMARY KEY (BOOKING_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_OT_BOOKING_NO UNIQUE (BOOKING_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_OT_TEAM
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OT_TEAM (
    TEAM_ID                NUMBER DEFAULT SEQ_OT_TEAM.NEXTVAL NOT NULL,
    BOOKING_ID             NUMBER NOT NULL CONSTRAINT FK_OT_TEAM_BOOKING_ID REFERENCES HMS_OT_BOOKING(BOOKING_ID),
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_OT_TEAM_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    TEAM_ROLE              VARCHAR2(30) CHECK (TEAM_ROLE IN ('SURGEON','ASSISTANT_SURGEON','ANESTHETIST','SCRUB_NURSE','CIRCULATING_NURSE','TECHNICIAN')),
    FEE_AMOUNT             NUMBER(12,2) DEFAULT 0,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OT_TEAM PRIMARY KEY (TEAM_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_OT_TEAM UNIQUE (BOOKING_ID, EMPLOYEE_ID, TEAM_ROLE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_OT_NOTES
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OT_NOTES (
    OT_NOTE_ID             NUMBER DEFAULT SEQ_OT_NOTES.NEXTVAL NOT NULL,
    BOOKING_ID             NUMBER NOT NULL CONSTRAINT FK_OT_NOTES_BOOKING_ID REFERENCES HMS_OT_BOOKING(BOOKING_ID),
    POST_OP_DIAGNOSIS      VARCHAR2(1000),
    PROCEDURE_DETAILS      CLOB,
    FINDINGS               VARCHAR2(4000),
    COMPLICATIONS          VARCHAR2(2000),
    BLOOD_LOSS_ML          NUMBER,
    SPECIMEN_SENT          VARCHAR2(500),
    POST_OP_INSTRUCTIONS   VARCHAR2(4000),
    WRITTEN_BY             NUMBER CONSTRAINT FK_OT_NOTES_WRITTEN_BY REFERENCES HMS_DOCTOR(DOCTOR_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OT_NOTES PRIMARY KEY (OT_NOTE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA
LOB (PROCEDURE_DETAILS) STORE AS SECUREFILE (TABLESPACE HMS_LOB);

-- ----------------------------------------------------------------------------
-- HMS_OT_CONSUMABLE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_OT_CONSUMABLE (
    CONSUMABLE_ID          NUMBER DEFAULT SEQ_OT_CONSUMABLE.NEXTVAL NOT NULL,
    BOOKING_ID             NUMBER NOT NULL CONSTRAINT FK_OT_CONSUMABLE_BOOKING_ID REFERENCES HMS_OT_BOOKING(BOOKING_ID),
    ITEM_ID                NUMBER NOT NULL CONSTRAINT FK_OT_CONSUMABLE_ITEM_ID REFERENCES HMS_PHARMA_ITEM(ITEM_ID),
    STOCK_ID               NUMBER CONSTRAINT FK_OT_CONSUMABLE_STOCK_ID REFERENCES HMS_PHARMA_STOCK(STOCK_ID),
    QUANTITY               NUMBER NOT NULL,
    UNIT_PRICE             NUMBER(12,2),
    LINE_TOTAL             NUMBER(14,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_OT_CONSUMABLE PRIMARY KEY (CONSUMABLE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

