/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 12_blood_bank_tables.sql
 Purpose   : Tables - BLOOD BANK
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : BLOOD BANK

-- ----------------------------------------------------------------------------
-- HMS_BLOOD_DONOR
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BLOOD_DONOR (
    DONOR_ID               NUMBER DEFAULT SEQ_BLOOD_DONOR.NEXTVAL NOT NULL,
    DONOR_CODE             VARCHAR2(30) NOT NULL,
    DONOR_NAME             VARCHAR2(200) NOT NULL,
    GENDER                 VARCHAR2(10) CHECK (GENDER IN ('MALE','FEMALE','OTHER')),
    DATE_OF_BIRTH          DATE,
    BLOOD_GROUP            VARCHAR2(5) NOT NULL,
    PHONE                  VARCHAR2(50),
    ADDRESS                VARCHAR2(500),
    WEIGHT_KG              NUMBER(5,2),
    LAST_DONATION_DATE     DATE,
    DONOR_TYPE             VARCHAR2(20) CHECK (DONOR_TYPE IN ('VOLUNTARY','REPLACEMENT','PAID','AUTOLOGOUS')),
    IS_DEFERRED            CHAR(1) DEFAULT 'N' CHECK (IS_DEFERRED IN ('Y','N')),
    DEFER_REASON           VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BLOOD_DONOR PRIMARY KEY (DONOR_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_DONOR_CODE UNIQUE (DONOR_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_BLOOD_COLLECTION
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BLOOD_COLLECTION (
    COLLECTION_ID          NUMBER DEFAULT SEQ_BLOOD_COLLECTION.NEXTVAL NOT NULL,
    DONOR_ID               NUMBER NOT NULL CONSTRAINT FK_BLOOD_COLLECTION_DONOR_ID REFERENCES HMS_BLOOD_DONOR(DONOR_ID),
    BAG_NO                 VARCHAR2(30) NOT NULL,
    COLLECTION_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    BAG_TYPE               VARCHAR2(20) CHECK (BAG_TYPE IN ('SINGLE','DOUBLE','TRIPLE','QUADRUPLE')),
    VOLUME_ML              NUMBER DEFAULT 450,
    HB_LEVEL               NUMBER(4,1),
    SCREENING_STATUS       VARCHAR2(20) DEFAULT 'PENDING' CHECK (SCREENING_STATUS IN ('PENDING','PASSED','FAILED')),
    HIV_RESULT             VARCHAR2(10),
    HBSAG_RESULT           VARCHAR2(10),
    HCV_RESULT             VARCHAR2(10),
    VDRL_RESULT            VARCHAR2(10),
    MALARIA_RESULT         VARCHAR2(10),
    COLLECTED_BY           NUMBER CONSTRAINT FK_BLOCOL_COLLECTED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BLOOD_COLLECTION PRIMARY KEY (COLLECTION_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_BAG_NO UNIQUE (BAG_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_BLOOD_INVENTORY
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BLOOD_INVENTORY (
    BLOOD_STOCK_ID         NUMBER DEFAULT SEQ_BLOOD_INVENTORY.NEXTVAL NOT NULL,
    COLLECTION_ID          NUMBER NOT NULL CONSTRAINT FK_BLOINV_COLLECTION_ID REFERENCES HMS_BLOOD_COLLECTION(COLLECTION_ID),
    COMPONENT_TYPE         VARCHAR2(20) NOT NULL CHECK (COMPONENT_TYPE IN ('WHOLE_BLOOD','PRBC','FFP','PLATELET','CRYO')),
    BLOOD_GROUP            VARCHAR2(5) NOT NULL,
    VOLUME_ML              NUMBER,
    EXPIRY_DATE            TIMESTAMP NOT NULL,
    STORAGE_LOCATION       VARCHAR2(50),
    UNIT_STATUS            VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (UNIT_STATUS IN ('QUARANTINE','AVAILABLE','RESERVED','ISSUED','EXPIRED','DISCARDED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BLOOD_INVENTORY PRIMARY KEY (BLOOD_STOCK_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_BLOOD_REQUISITION
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BLOOD_REQUISITION (
    REQUISITION_ID         NUMBER DEFAULT SEQ_BLOOD_REQUISITION.NEXTVAL NOT NULL,
    REQUISITION_NO         VARCHAR2(30) NOT NULL,
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_BLOREQ_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    ADMISSION_ID           NUMBER CONSTRAINT FK_BLOREQ_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    REQUESTED_BY           NUMBER CONSTRAINT FK_BLOREQ_REQUESTED_BY REFERENCES HMS_DOCTOR(DOCTOR_ID),
    BLOOD_GROUP            VARCHAR2(5) NOT NULL,
    COMPONENT_TYPE         VARCHAR2(20),
    UNITS_REQUIRED         NUMBER DEFAULT 1,
    PRIORITY               VARCHAR2(20) DEFAULT 'ROUTINE' CHECK (PRIORITY IN ('ROUTINE','URGENT','EMERGENCY')),
    REQUIRED_DATE          TIMESTAMP,
    REQ_STATUS             VARCHAR2(20) DEFAULT 'PENDING' CHECK (REQ_STATUS IN ('PENDING','CROSSMATCHED','PARTIAL','ISSUED','CANCELLED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BLOOD_REQUISITION PRIMARY KEY (REQUISITION_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_BLOOD_REQ_NO UNIQUE (REQUISITION_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_BLOOD_CROSSMATCH
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BLOOD_CROSSMATCH (
    CROSSMATCH_ID          NUMBER DEFAULT SEQ_BLOOD_CROSSMATCH.NEXTVAL NOT NULL,
    REQUISITION_ID         NUMBER NOT NULL CONSTRAINT FK_BLOCRO_REQUISITION_ID REFERENCES HMS_BLOOD_REQUISITION(REQUISITION_ID),
    BLOOD_STOCK_ID         NUMBER NOT NULL CONSTRAINT FK_BLOCRO_BLOOD_STOCK_ID REFERENCES HMS_BLOOD_INVENTORY(BLOOD_STOCK_ID),
    CROSSMATCH_RESULT      VARCHAR2(20) CHECK (CROSSMATCH_RESULT IN ('COMPATIBLE','INCOMPATIBLE')),
    TESTED_BY              NUMBER CONSTRAINT FK_BLOOD_CROSSMATCH_TESTED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    TESTED_TIME            TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BLOOD_CROSSMATCH PRIMARY KEY (CROSSMATCH_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_BLOOD_ISSUE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BLOOD_ISSUE (
    ISSUE_ID               NUMBER DEFAULT SEQ_BLOOD_ISSUE.NEXTVAL NOT NULL,
    REQUISITION_ID         NUMBER NOT NULL CONSTRAINT FK_BLOOD_ISSUE_REQUISITION_ID REFERENCES HMS_BLOOD_REQUISITION(REQUISITION_ID),
    BLOOD_STOCK_ID         NUMBER NOT NULL CONSTRAINT FK_BLOOD_ISSUE_BLOOD_STOCK_ID REFERENCES HMS_BLOOD_INVENTORY(BLOOD_STOCK_ID),
    ISSUE_TIME             TIMESTAMP DEFAULT SYSTIMESTAMP,
    ISSUED_BY              NUMBER CONSTRAINT FK_BLOOD_ISSUE_ISSUED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    RECEIVED_BY_NAME       VARCHAR2(200),
    CHARGE_AMOUNT          NUMBER(12,2),
    TRANSFUSION_REACTION   VARCHAR2(1000),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BLOOD_ISSUE PRIMARY KEY (ISSUE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_BLOOD_ISSUE UNIQUE (BLOOD_STOCK_ID)
)
TABLESPACE HMS_DATA;

