/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 13_nursing_tables.sql
 Purpose   : Tables - NURSING
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : NURSING

-- ----------------------------------------------------------------------------
-- HMS_NURSING_ASSESSMENT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_NURSING_ASSESSMENT (
    ASSESSMENT_ID          NUMBER DEFAULT SEQ_NURSING_ASSESSMENT.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_NURASS_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    ASSESSMENT_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSCIOUSNESS          VARCHAR2(50),
    PAIN_SCORE             NUMBER(2) CHECK (PAIN_SCORE BETWEEN 0 AND 10),
    FALL_RISK_SCORE        NUMBER,
    BRADEN_SCORE           NUMBER,
    GCS_SCORE              NUMBER(2),
    NOTES                  VARCHAR2(2000),
    NURSE_ID               NUMBER CONSTRAINT FK_NURSING_ASSESSMENT_NURSE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_NURSING_ASSESSMENT PRIMARY KEY (ASSESSMENT_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_IPD_VITALS
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_IPD_VITALS (
    IPD_VITAL_ID           NUMBER DEFAULT SEQ_IPD_VITALS.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_IPD_VITALS_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    RECORDED_TIME          TIMESTAMP DEFAULT SYSTIMESTAMP,
    BP_SYSTOLIC            NUMBER(3),
    BP_DIASTOLIC           NUMBER(3),
    PULSE_RATE             NUMBER(3),
    TEMPERATURE_F          NUMBER(5,2),
    RESPIRATORY_RATE       NUMBER(3),
    SPO2                   NUMBER(3),
    BLOOD_SUGAR            NUMBER(6,2),
    INTAKE_ML              NUMBER,
    OUTPUT_ML              NUMBER,
    RECORDED_BY            NUMBER CONSTRAINT FK_IPD_VITALS_RECORDED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_IPD_VITALS PRIMARY KEY (IPD_VITAL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_NURSING_CARE_PLAN
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_NURSING_CARE_PLAN (
    CARE_PLAN_ID           NUMBER DEFAULT SEQ_NURSING_CARE_PLAN.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_NURCARPLA_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    NURSING_DIAGNOSIS      VARCHAR2(1000),
    GOAL                   VARCHAR2(1000),
    INTERVENTIONS          VARCHAR2(4000),
    EVALUATION             VARCHAR2(2000),
    PLAN_STATUS            VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (PLAN_STATUS IN ('ACTIVE','ACHIEVED','REVISED','CLOSED')),
    NURSE_ID               NUMBER CONSTRAINT FK_NURSING_CARE_PLAN_NURSE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_NURSING_CARE_PLAN PRIMARY KEY (CARE_PLAN_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_NURSING_NOTES
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_NURSING_NOTES (
    NOTE_ID                NUMBER DEFAULT SEQ_NURSING_NOTES.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_NURSING_NOTES_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    NOTE_TIME              TIMESTAMP DEFAULT SYSTIMESTAMP,
    SHIFT_ID               NUMBER CONSTRAINT FK_NURSING_NOTES_SHIFT_ID REFERENCES HMS_SHIFT_MASTER(SHIFT_ID),
    NOTE_TEXT              VARCHAR2(4000) NOT NULL,
    NURSE_ID               NUMBER CONSTRAINT FK_NURSING_NOTES_NURSE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_NURSING_NOTES PRIMARY KEY (NOTE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

