/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 14_diet_tables.sql
 Purpose   : Tables - DIET / KITCHEN
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : DIET / KITCHEN

-- ----------------------------------------------------------------------------
-- HMS_DIET_MASTER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DIET_MASTER (
    DIET_ID                NUMBER DEFAULT SEQ_DIET_MASTER.NEXTVAL NOT NULL,
    DIET_CODE              VARCHAR2(30) NOT NULL,
    DIET_NAME              VARCHAR2(200) NOT NULL,
    DIET_TYPE              VARCHAR2(30) CHECK (DIET_TYPE IN ('NORMAL','DIABETIC','LIQUID','SOFT','SALT_FREE','RENAL','CARDIAC','HIGH_PROTEIN','NPO')),
    CALORIES               NUMBER,
    DIET_DESC              VARCHAR2(1000),
    RATE_PER_DAY           NUMBER(12,2) DEFAULT 0,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DIET_MASTER PRIMARY KEY (DIET_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_DIET_CODE UNIQUE (DIET_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_DIET_ORDER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DIET_ORDER (
    DIET_ORDER_ID          NUMBER DEFAULT SEQ_DIET_ORDER.NEXTVAL NOT NULL,
    ADMISSION_ID           NUMBER NOT NULL CONSTRAINT FK_DIET_ORDER_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    DIET_ID                NUMBER NOT NULL CONSTRAINT FK_DIET_ORDER_DIET_ID REFERENCES HMS_DIET_MASTER(DIET_ID),
    ORDERED_BY             NUMBER CONSTRAINT FK_DIET_ORDER_ORDERED_BY REFERENCES HMS_DOCTOR(DOCTOR_ID),
    START_DATE             DATE DEFAULT SYSDATE,
    END_DATE               DATE,
    SPECIAL_INSTRUCTIONS   VARCHAR2(1000),
    ORDER_STATUS           VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (ORDER_STATUS IN ('ACTIVE','STOPPED','COMPLETED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DIET_ORDER PRIMARY KEY (DIET_ORDER_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_DIET_SERVING
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DIET_SERVING (
    SERVING_ID             NUMBER DEFAULT SEQ_DIET_SERVING.NEXTVAL NOT NULL,
    DIET_ORDER_ID          NUMBER NOT NULL CONSTRAINT FK_DIET_SERVING_DIET_ORDER_ID REFERENCES HMS_DIET_ORDER(DIET_ORDER_ID),
    SERVING_DATE           DATE DEFAULT TRUNC(SYSDATE),
    MEAL_TYPE              VARCHAR2(20) CHECK (MEAL_TYPE IN ('BREAKFAST','LUNCH','SNACKS','DINNER')),
    SERVED_TIME            TIMESTAMP,
    SERVED_BY              NUMBER CONSTRAINT FK_DIET_SERVING_SERVED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    SERVING_STATUS         VARCHAR2(20) DEFAULT 'PENDING' CHECK (SERVING_STATUS IN ('PENDING','SERVED','REFUSED','SKIPPED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DIET_SERVING PRIMARY KEY (SERVING_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

