/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 15_insurance_tables.sql
 Purpose   : Tables - INSURANCE / TPA / CORPORATE
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : INSURANCE / TPA / CORPORATE

-- ----------------------------------------------------------------------------
-- HMS_INSURANCE_COMPANY
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INSURANCE_COMPANY (
    INS_COMPANY_ID         NUMBER DEFAULT SEQ_INSURANCE_COMPANY.NEXTVAL NOT NULL,
    COMPANY_CODE           VARCHAR2(30) NOT NULL,
    COMPANY_NAME           VARCHAR2(300) NOT NULL,
    COMPANY_TYPE           VARCHAR2(20) CHECK (COMPANY_TYPE IN ('INSURANCE','TPA','CORPORATE','GOVT')),
    CONTACT_PERSON         VARCHAR2(200),
    PHONE                  VARCHAR2(50),
    EMAIL                  VARCHAR2(150),
    ADDRESS                VARCHAR2(500),
    CREDIT_LIMIT           NUMBER(14,2),
    DISCOUNT_PERCENT       NUMBER(5,2) DEFAULT 0,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INSURANCE_COMPANY PRIMARY KEY (INS_COMPANY_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_INS_COMPANY UNIQUE (COMPANY_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_INSURANCE_PLAN
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INSURANCE_PLAN (
    PLAN_ID                NUMBER DEFAULT SEQ_INSURANCE_PLAN.NEXTVAL NOT NULL,
    INS_COMPANY_ID         NUMBER NOT NULL CONSTRAINT FK_INSPLA_INS_COMPANY_ID REFERENCES HMS_INSURANCE_COMPANY(INS_COMPANY_ID),
    PLAN_NAME              VARCHAR2(200) NOT NULL,
    COVERAGE_LIMIT         NUMBER(14,2),
    ROOM_RENT_LIMIT        NUMBER(12,2),
    CO_PAY_PERCENT         NUMBER(5,2) DEFAULT 0,
    COVERAGE_DETAILS       VARCHAR2(4000),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INSURANCE_PLAN PRIMARY KEY (PLAN_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PATIENT_INSURANCE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PATIENT_INSURANCE (
    POLICY_ID              NUMBER DEFAULT SEQ_PATIENT_INSURANCE.NEXTVAL NOT NULL,
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_PATINS_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    PLAN_ID                NUMBER NOT NULL CONSTRAINT FK_PATIENT_INSURANCE_PLAN_ID REFERENCES HMS_INSURANCE_PLAN(PLAN_ID),
    POLICY_NO              VARCHAR2(100) NOT NULL,
    MEMBER_ID              VARCHAR2(100),
    POLICY_HOLDER_NAME     VARCHAR2(200),
    RELATION_TO_HOLDER     VARCHAR2(50),
    VALID_FROM             DATE,
    VALID_TO               DATE,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PATIENT_INSURANCE PRIMARY KEY (POLICY_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_INSURANCE_PREAUTH
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INSURANCE_PREAUTH (
    PREAUTH_ID             NUMBER DEFAULT SEQ_INSURANCE_PREAUTH.NEXTVAL NOT NULL,
    POLICY_ID              NUMBER NOT NULL CONSTRAINT FK_INSURANCE_PREAUTH_POLICY_ID REFERENCES HMS_PATIENT_INSURANCE(POLICY_ID),
    ADMISSION_ID           NUMBER CONSTRAINT FK_INSPRE_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    REQUEST_DATE           DATE DEFAULT SYSDATE,
    REQUESTED_AMOUNT       NUMBER(14,2),
    APPROVED_AMOUNT        NUMBER(14,2),
    APPROVAL_REF_NO        VARCHAR2(100),
    PREAUTH_STATUS         VARCHAR2(20) DEFAULT 'PENDING' CHECK (PREAUTH_STATUS IN ('PENDING','APPROVED','PARTIAL','REJECTED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INSURANCE_PREAUTH PRIMARY KEY (PREAUTH_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

