/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 16_billing_accounts_tables.sql
 Purpose   : Tables - ACCOUNT & BILLING
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : ACCOUNT & BILLING

-- ----------------------------------------------------------------------------
-- HMS_BILLING
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BILLING (
    BILL_ID                NUMBER DEFAULT SEQ_BILLING.NEXTVAL NOT NULL,
    BILL_NO                VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_BILLING_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_BILLING_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    BILL_TYPE              VARCHAR2(20) NOT NULL CHECK (BILL_TYPE IN ('OPD','IPD','LAB','PHARMACY','EMERGENCY','OT','PACKAGE','MISC')),
    OPD_VISIT_ID           NUMBER CONSTRAINT FK_BILLING_OPD_VISIT_ID REFERENCES HMS_OPD_VISIT(VISIT_ID),
    ADMISSION_ID           NUMBER CONSTRAINT FK_BILLING_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    POLICY_ID              NUMBER CONSTRAINT FK_BILLING_POLICY_ID REFERENCES HMS_PATIENT_INSURANCE(POLICY_ID),
    BILL_DATE              TIMESTAMP DEFAULT SYSTIMESTAMP,
    GROSS_AMOUNT           NUMBER(14,2) DEFAULT 0,
    HEADER_DISCOUNT        NUMBER(14,2) DEFAULT 0,
    DISCOUNT_AMOUNT        NUMBER(14,2) DEFAULT 0,
    DISCOUNT_REASON        VARCHAR2(500),
    DISCOUNT_APPROVED_BY   NUMBER CONSTRAINT FK_BIL_DISCOUNT_APPROVED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    VAT_AMOUNT             NUMBER(14,2) DEFAULT 0,
    NET_AMOUNT             NUMBER(14,2) DEFAULT 0,
    INSURANCE_AMOUNT       NUMBER(14,2) DEFAULT 0,
    PATIENT_PAYABLE        NUMBER(14,2) DEFAULT 0,
    PAID_AMOUNT            NUMBER(14,2) DEFAULT 0,
    DUE_AMOUNT             NUMBER(14,2) DEFAULT 0,
    BILL_STATUS            VARCHAR2(20) DEFAULT 'OPEN' CHECK (BILL_STATUS IN ('DRAFT','OPEN','PARTIAL','PAID','CANCELLED','REFUNDED')),
    CANCEL_REASON          VARCHAR2(500),
    REMARKS                VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BILLING PRIMARY KEY (BILL_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_BILL_NO UNIQUE (BILL_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_BILLING_DTL  : REF_TYPE = LAB_ORDER_DTL / PHARMA_SALE / BED / OT_BOOKING ...
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_BILLING_DTL (
    BILL_DTL_ID            NUMBER DEFAULT SEQ_BILLING_DTL.NEXTVAL NOT NULL,
    BILL_ID                NUMBER NOT NULL CONSTRAINT FK_BILLING_DTL_BILL_ID REFERENCES HMS_BILLING(BILL_ID),
    SERVICE_ID             NUMBER CONSTRAINT FK_BILLING_DTL_SERVICE_ID REFERENCES HMS_SERVICE_MASTER(SERVICE_ID),
    ITEM_DESC              VARCHAR2(300) NOT NULL,
    REF_TYPE               VARCHAR2(30),
    REF_ID                 NUMBER,
    SERVICE_DATE           DATE DEFAULT SYSDATE,
    DOCTOR_ID              NUMBER CONSTRAINT FK_BILLING_DTL_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    QUANTITY               NUMBER DEFAULT 1,
    UNIT_PRICE             NUMBER(12,2) DEFAULT 0,
    GROSS_AMOUNT           NUMBER(14,2) DEFAULT 0,
    DISCOUNT_AMOUNT        NUMBER(14,2) DEFAULT 0,
    VAT_AMOUNT             NUMBER(14,2) DEFAULT 0,
    NET_AMOUNT             NUMBER(14,2) DEFAULT 0,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_BILLING_DTL PRIMARY KEY (BILL_DTL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_BILLING_DTL IS 'REF_TYPE = LAB_ORDER_DTL / PHARMA_SALE / BED / OT_BOOKING ...';

-- ----------------------------------------------------------------------------
-- HMS_PATIENT_ADVANCE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PATIENT_ADVANCE (
    ADVANCE_ID             NUMBER DEFAULT SEQ_PATIENT_ADVANCE.NEXTVAL NOT NULL,
    ADVANCE_NO             VARCHAR2(30) NOT NULL,
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_PATIENT_ADVANCE_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    ADMISSION_ID           NUMBER CONSTRAINT FK_PATADV_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    ADVANCE_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP,
    AMOUNT                 NUMBER(14,2) NOT NULL CHECK (AMOUNT > 0),
    ADJUSTED_AMOUNT        NUMBER(14,2) DEFAULT 0,
    REFUNDED_AMOUNT        NUMBER(14,2) DEFAULT 0,
    PAYMENT_MODE           VARCHAR2(20) CHECK (PAYMENT_MODE IN ('CASH','CARD','BKASH','NAGAD','ROCKET','BANK','CHEQUE')),
    TRANSACTION_REF        VARCHAR2(100),
    ADVANCE_STATUS         VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (ADVANCE_STATUS IN ('ACTIVE','ADJUSTED','REFUNDED','CANCELLED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PATIENT_ADVANCE PRIMARY KEY (ADVANCE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_ADVANCE_NO UNIQUE (ADVANCE_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PAYMENT_RECEIPT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PAYMENT_RECEIPT (
    RECEIPT_ID             NUMBER DEFAULT SEQ_PAYMENT_RECEIPT.NEXTVAL NOT NULL,
    RECEIPT_NO             VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_PAYMENT_RECEIPT_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    BILL_ID                NUMBER CONSTRAINT FK_PAYMENT_RECEIPT_BILL_ID REFERENCES HMS_BILLING(BILL_ID),
    PATIENT_ID             NUMBER NOT NULL CONSTRAINT FK_PAYMENT_RECEIPT_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    RECEIPT_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP,
    RECEIPT_TYPE           VARCHAR2(20) DEFAULT 'PAYMENT' CHECK (RECEIPT_TYPE IN ('PAYMENT','ADVANCE','REFUND','ADJUSTMENT')),
    AMOUNT                 NUMBER(14,2) NOT NULL,
    PAYMENT_MODE           VARCHAR2(20) CHECK (PAYMENT_MODE IN ('CASH','CARD','BKASH','NAGAD','ROCKET','BANK','CHEQUE','ADVANCE','INSURANCE')),
    TRANSACTION_REF        VARCHAR2(100),
    CARD_LAST4             VARCHAR2(4),
    BANK_NAME              VARCHAR2(150),
    CASHIER_ID             NUMBER CONSTRAINT FK_PAYMENT_RECEIPT_CASHIER_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    RECEIPT_STATUS         VARCHAR2(20) DEFAULT 'VALID' CHECK (RECEIPT_STATUS IN ('VALID','CANCELLED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PAYMENT_RECEIPT PRIMARY KEY (RECEIPT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_RECEIPT_NO UNIQUE (RECEIPT_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_INSURANCE_CLAIM
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INSURANCE_CLAIM (
    CLAIM_ID               NUMBER DEFAULT SEQ_INSURANCE_CLAIM.NEXTVAL NOT NULL,
    CLAIM_NO               VARCHAR2(30) NOT NULL,
    POLICY_ID              NUMBER NOT NULL CONSTRAINT FK_INSURANCE_CLAIM_POLICY_ID REFERENCES HMS_PATIENT_INSURANCE(POLICY_ID),
    BILL_ID                NUMBER NOT NULL CONSTRAINT FK_INSURANCE_CLAIM_BILL_ID REFERENCES HMS_BILLING(BILL_ID),
    CLAIM_DATE             DATE DEFAULT SYSDATE,
    CLAIM_AMOUNT           NUMBER(14,2),
    APPROVED_AMOUNT        NUMBER(14,2),
    SETTLED_AMOUNT         NUMBER(14,2),
    SETTLEMENT_DATE        DATE,
    CLAIM_STATUS           VARCHAR2(20) DEFAULT 'SUBMITTED' CHECK (CLAIM_STATUS IN ('SUBMITTED','UNDER_REVIEW','APPROVED','PARTIAL','REJECTED','SETTLED')),
    REJECTION_REASON       VARCHAR2(1000),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INSURANCE_CLAIM PRIMARY KEY (CLAIM_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_CLAIM_NO UNIQUE (CLAIM_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_DOCTOR_EARNING
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DOCTOR_EARNING (
    EARNING_ID             NUMBER DEFAULT SEQ_DOCTOR_EARNING.NEXTVAL NOT NULL,
    DOCTOR_ID              NUMBER NOT NULL CONSTRAINT FK_DOCTOR_EARNING_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    BILL_DTL_ID            NUMBER CONSTRAINT FK_DOCTOR_EARNING_BILL_DTL_ID REFERENCES HMS_BILLING_DTL(BILL_DTL_ID),
    EARNING_DATE           DATE DEFAULT SYSDATE,
    EARNING_TYPE           VARCHAR2(20) CHECK (EARNING_TYPE IN ('CONSULTATION','REFERRAL','SURGERY','VISIT','PROCEDURE')),
    BASE_AMOUNT            NUMBER(12,2),
    EARNING_AMOUNT         NUMBER(12,2) NOT NULL,
    PAYOUT_STATUS          VARCHAR2(20) DEFAULT 'PENDING' CHECK (PAYOUT_STATUS IN ('PENDING','PAID','HOLD')),
    PAID_DATE              DATE,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DOCTOR_EARNING PRIMARY KEY (EARNING_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_CHART_OF_ACCOUNTS
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_CHART_OF_ACCOUNTS (
    COA_ID                 NUMBER DEFAULT SEQ_CHART_OF_ACCOUNTS.NEXTVAL NOT NULL,
    ACCOUNT_CODE           VARCHAR2(30) NOT NULL,
    ACCOUNT_NAME           VARCHAR2(200) NOT NULL,
    ACCOUNT_TYPE           VARCHAR2(20) NOT NULL CHECK (ACCOUNT_TYPE IN ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE')),
    PARENT_COA_ID          NUMBER CONSTRAINT FK_CHAOFACC_PARENT_COA_ID REFERENCES HMS_CHART_OF_ACCOUNTS(COA_ID),
    ACCOUNT_LEVEL          NUMBER DEFAULT 1,
    IS_POSTING             CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_POSTING IN ('Y','N')),
    OPENING_BALANCE        NUMBER(16,2) DEFAULT 0,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_CHART_OF_ACCOUNTS PRIMARY KEY (COA_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_COA_CODE UNIQUE (ACCOUNT_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_JOURNAL_VOUCHER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_JOURNAL_VOUCHER (
    VOUCHER_ID             NUMBER DEFAULT SEQ_JOURNAL_VOUCHER.NEXTVAL NOT NULL,
    VOUCHER_NO             VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_JOURNAL_VOUCHER_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    VOUCHER_DATE           DATE DEFAULT SYSDATE NOT NULL,
    VOUCHER_TYPE           VARCHAR2(20) CHECK (VOUCHER_TYPE IN ('JOURNAL','RECEIPT','PAYMENT','CONTRA')),
    NARRATION              VARCHAR2(1000),
    REF_TYPE               VARCHAR2(30),
    REF_ID                 NUMBER,
    TOTAL_DEBIT            NUMBER(16,2) DEFAULT 0,
    TOTAL_CREDIT           NUMBER(16,2) DEFAULT 0,
    VOUCHER_STATUS         VARCHAR2(20) DEFAULT 'DRAFT' CHECK (VOUCHER_STATUS IN ('DRAFT','POSTED','CANCELLED')),
    APPROVED_BY            NUMBER CONSTRAINT FK_JOURNAL_VOUCHER_APPROVED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_JOURNAL_VOUCHER PRIMARY KEY (VOUCHER_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_VOUCHER_NO UNIQUE (VOUCHER_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_JOURNAL_VOUCHER_DTL
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_JOURNAL_VOUCHER_DTL (
    VOUCHER_DTL_ID         NUMBER DEFAULT SEQ_JOURNAL_VOUCHER_DTL.NEXTVAL NOT NULL,
    VOUCHER_ID             NUMBER NOT NULL CONSTRAINT FK_JOUVOUDTL_VOUCHER_ID REFERENCES HMS_JOURNAL_VOUCHER(VOUCHER_ID),
    COA_ID                 NUMBER NOT NULL CONSTRAINT FK_JOURNAL_VOUCHER_DTL_COA_ID REFERENCES HMS_CHART_OF_ACCOUNTS(COA_ID),
    DEBIT_AMOUNT           NUMBER(16,2) DEFAULT 0,
    CREDIT_AMOUNT          NUMBER(16,2) DEFAULT 0,
    LINE_NARRATION         VARCHAR2(500),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_JOURNAL_VOUCHER_DTL PRIMARY KEY (VOUCHER_DTL_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT CK_JV_DR_CR CHECK (DEBIT_AMOUNT >= 0 AND CREDIT_AMOUNT >= 0)
)
TABLESPACE HMS_DATA;

