/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 17_inventory_tables.sql
 Purpose   : Tables - INVENTORY & STORE (General items + Asset)
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : INVENTORY & STORE (General items + Asset)

-- ----------------------------------------------------------------------------
-- HMS_INV_STORE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INV_STORE (
    INV_STORE_ID           NUMBER DEFAULT SEQ_INV_STORE.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_INV_STORE_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    STORE_CODE             VARCHAR2(30) NOT NULL,
    STORE_NAME             VARCHAR2(200) NOT NULL,
    STORE_INCHARGE_ID      NUMBER CONSTRAINT FK_INV_STORE_STORE_INCHARGE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INV_STORE PRIMARY KEY (INV_STORE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_INV_STORE UNIQUE (STORE_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_INV_ITEM
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INV_ITEM (
    INV_ITEM_ID            NUMBER DEFAULT SEQ_INV_ITEM.NEXTVAL NOT NULL,
    ITEM_CODE              VARCHAR2(30) NOT NULL,
    ITEM_NAME              VARCHAR2(300) NOT NULL,
    ITEM_GROUP             VARCHAR2(50) CHECK (ITEM_GROUP IN ('SURGICAL','LINEN','STATIONERY','HOUSEKEEPING','LAB_REAGENT','EQUIPMENT','FOOD','OTHER')),
    UNIT_OF_MEASURE        VARCHAR2(30),
    REORDER_LEVEL          NUMBER DEFAULT 0,
    LAST_PURCHASE_RATE     NUMBER(12,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INV_ITEM PRIMARY KEY (INV_ITEM_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_INV_ITEM UNIQUE (ITEM_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_INV_STOCK
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INV_STOCK (
    INV_STOCK_ID           NUMBER DEFAULT SEQ_INV_STOCK.NEXTVAL NOT NULL,
    INV_STORE_ID           NUMBER NOT NULL CONSTRAINT FK_INV_STOCK_INV_STORE_ID REFERENCES HMS_INV_STORE(INV_STORE_ID),
    INV_ITEM_ID            NUMBER NOT NULL CONSTRAINT FK_INV_STOCK_INV_ITEM_ID REFERENCES HMS_INV_ITEM(INV_ITEM_ID),
    QTY_AVAILABLE          NUMBER DEFAULT 0 NOT NULL,
    AVG_COST               NUMBER(12,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INV_STOCK PRIMARY KEY (INV_STOCK_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_INV_STOCK UNIQUE (INV_STORE_ID, INV_ITEM_ID)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_INDENT  : Department requisition
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INDENT (
    INDENT_ID              NUMBER DEFAULT SEQ_INDENT.NEXTVAL NOT NULL,
    INDENT_NO              VARCHAR2(30) NOT NULL,
    FROM_DEPT_ID           NUMBER NOT NULL CONSTRAINT FK_INDENT_FROM_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    INV_STORE_ID           NUMBER NOT NULL CONSTRAINT FK_INDENT_INV_STORE_ID REFERENCES HMS_INV_STORE(INV_STORE_ID),
    INDENT_DATE            DATE DEFAULT SYSDATE,
    REQUESTED_BY           NUMBER CONSTRAINT FK_INDENT_REQUESTED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    APPROVED_BY            NUMBER CONSTRAINT FK_INDENT_APPROVED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    INDENT_STATUS          VARCHAR2(20) DEFAULT 'PENDING' CHECK (INDENT_STATUS IN ('PENDING','APPROVED','PARTIAL','ISSUED','REJECTED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INDENT PRIMARY KEY (INDENT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_INDENT_NO UNIQUE (INDENT_NO)
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_INDENT IS 'Department requisition';

-- ----------------------------------------------------------------------------
-- HMS_INDENT_DTL
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_INDENT_DTL (
    INDENT_DTL_ID          NUMBER DEFAULT SEQ_INDENT_DTL.NEXTVAL NOT NULL,
    INDENT_ID              NUMBER NOT NULL CONSTRAINT FK_INDENT_DTL_INDENT_ID REFERENCES HMS_INDENT(INDENT_ID),
    INV_ITEM_ID            NUMBER NOT NULL CONSTRAINT FK_INDENT_DTL_INV_ITEM_ID REFERENCES HMS_INV_ITEM(INV_ITEM_ID),
    REQUESTED_QTY          NUMBER NOT NULL,
    APPROVED_QTY           NUMBER,
    ISSUED_QTY             NUMBER DEFAULT 0,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_INDENT_DTL PRIMARY KEY (INDENT_DTL_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_ASSET
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_ASSET (
    ASSET_ID               NUMBER DEFAULT SEQ_ASSET.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_ASSET_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    DEPT_ID                NUMBER CONSTRAINT FK_ASSET_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    ASSET_CODE             VARCHAR2(30) NOT NULL,
    ASSET_NAME             VARCHAR2(300) NOT NULL,
    ASSET_CATEGORY         VARCHAR2(50),
    SERIAL_NO              VARCHAR2(100),
    PURCHASE_DATE          DATE,
    PURCHASE_COST          NUMBER(14,2),
    WARRANTY_UPTO          DATE,
    AMC_UPTO               DATE,
    DEPRECIATION_RATE      NUMBER(5,2),
    ASSET_STATUS           VARCHAR2(20) DEFAULT 'IN_USE' CHECK (ASSET_STATUS IN ('IN_USE','IN_STORE','UNDER_REPAIR','CONDEMNED','DISPOSED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_ASSET PRIMARY KEY (ASSET_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_ASSET_CODE UNIQUE (ASSET_CODE)
)
TABLESPACE HMS_DATA;

