/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 18_hr_tables.sql
 Purpose   : Tables - ADMIN / HR / PAYROLL
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : ADMIN / HR / PAYROLL

-- ----------------------------------------------------------------------------
-- HMS_DUTY_ROSTER
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_DUTY_ROSTER (
    ROSTER_ID              NUMBER DEFAULT SEQ_DUTY_ROSTER.NEXTVAL NOT NULL,
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_DUTY_ROSTER_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    SHIFT_ID               NUMBER NOT NULL CONSTRAINT FK_DUTY_ROSTER_SHIFT_ID REFERENCES HMS_SHIFT_MASTER(SHIFT_ID),
    DEPT_ID                NUMBER CONSTRAINT FK_DUTY_ROSTER_DEPT_ID REFERENCES HMS_DEPARTMENT(DEPT_ID),
    WARD_ID                NUMBER CONSTRAINT FK_DUTY_ROSTER_WARD_ID REFERENCES HMS_WARD(WARD_ID),
    DUTY_DATE              DATE NOT NULL,
    ROSTER_STATUS          VARCHAR2(20) DEFAULT 'SCHEDULED' CHECK (ROSTER_STATUS IN ('SCHEDULED','PRESENT','ABSENT','LEAVE','SWAPPED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_DUTY_ROSTER PRIMARY KEY (ROSTER_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_ROSTER UNIQUE (EMPLOYEE_ID, DUTY_DATE, SHIFT_ID)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_ATTENDANCE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_ATTENDANCE (
    ATTENDANCE_ID          NUMBER DEFAULT SEQ_ATTENDANCE.NEXTVAL NOT NULL,
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_ATTENDANCE_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    ATTENDANCE_DATE        DATE NOT NULL,
    CHECK_IN               TIMESTAMP,
    CHECK_OUT              TIMESTAMP,
    ATTENDANCE_STATUS      VARCHAR2(20) CHECK (ATTENDANCE_STATUS IN ('PRESENT','ABSENT','LATE','HALF_DAY','LEAVE','HOLIDAY','WEEKEND')),
    LATE_MINUTES           NUMBER DEFAULT 0,
    OVERTIME_MINUTES       NUMBER DEFAULT 0,
    SOURCE_DEVICE          VARCHAR2(50),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (ATTENDANCE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_ATTENDANCE UNIQUE (EMPLOYEE_ID, ATTENDANCE_DATE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_LEAVE_TYPE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LEAVE_TYPE (
    LEAVE_TYPE_ID          NUMBER DEFAULT SEQ_LEAVE_TYPE.NEXTVAL NOT NULL,
    LEAVE_CODE             VARCHAR2(20) NOT NULL,
    LEAVE_NAME             VARCHAR2(100) NOT NULL,
    DAYS_PER_YEAR          NUMBER,
    IS_PAID                CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_PAID IN ('Y','N')),
    CARRY_FORWARD          CHAR(1) DEFAULT 'N' NOT NULL CHECK (CARRY_FORWARD IN ('Y','N')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LEAVE_TYPE PRIMARY KEY (LEAVE_TYPE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_LEAVE_CODE UNIQUE (LEAVE_CODE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_LEAVE_APPLICATION
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_LEAVE_APPLICATION (
    LEAVE_ID               NUMBER DEFAULT SEQ_LEAVE_APPLICATION.NEXTVAL NOT NULL,
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_LEAAPP_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    LEAVE_TYPE_ID          NUMBER NOT NULL CONSTRAINT FK_LEAAPP_LEAVE_TYPE_ID REFERENCES HMS_LEAVE_TYPE(LEAVE_TYPE_ID),
    START_DATE             DATE NOT NULL,
    END_DATE               DATE NOT NULL,
    TOTAL_DAYS             NUMBER,
    REASON                 VARCHAR2(1000),
    APPROVED_BY            NUMBER CONSTRAINT FK_LEAAPP_APPROVED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    LEAVE_STATUS           VARCHAR2(20) DEFAULT 'PENDING' CHECK (LEAVE_STATUS IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_LEAVE_APPLICATION PRIMARY KEY (LEAVE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT CK_LEAVE_DATES CHECK (END_DATE >= START_DATE)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_SALARY_STRUCTURE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_SALARY_STRUCTURE (
    SALARY_ID              NUMBER DEFAULT SEQ_SALARY_STRUCTURE.NEXTVAL NOT NULL,
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_SALSTR_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    EFFECTIVE_FROM         DATE NOT NULL,
    BASIC_SALARY           NUMBER(12,2) NOT NULL,
    HOUSE_RENT             NUMBER(12,2) DEFAULT 0,
    MEDICAL_ALLOWANCE      NUMBER(12,2) DEFAULT 0,
    CONVEYANCE             NUMBER(12,2) DEFAULT 0,
    OTHER_ALLOWANCE        NUMBER(12,2) DEFAULT 0,
    PF_PERCENT             NUMBER(5,2) DEFAULT 0,
    TAX_DEDUCTION          NUMBER(12,2) DEFAULT 0,
    GROSS_SALARY           NUMBER(12,2),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_SALARY_STRUCTURE PRIMARY KEY (SALARY_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_SALARY UNIQUE (EMPLOYEE_ID, EFFECTIVE_FROM)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_PAYROLL  : SALARY_MONTH format YYYY-MM
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_PAYROLL (
    PAYROLL_ID             NUMBER DEFAULT SEQ_PAYROLL.NEXTVAL NOT NULL,
    EMPLOYEE_ID            NUMBER NOT NULL CONSTRAINT FK_PAYROLL_EMPLOYEE_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    SALARY_MONTH           VARCHAR2(7) NOT NULL,
    WORKING_DAYS           NUMBER,
    PRESENT_DAYS           NUMBER,
    GROSS_SALARY           NUMBER(12,2),
    OVERTIME_AMOUNT        NUMBER(12,2) DEFAULT 0,
    BONUS_AMOUNT           NUMBER(12,2) DEFAULT 0,
    TOTAL_DEDUCTION        NUMBER(12,2) DEFAULT 0,
    NET_SALARY             NUMBER(12,2),
    PAYMENT_DATE           DATE,
    PAYROLL_STATUS         VARCHAR2(20) DEFAULT 'DRAFT' CHECK (PAYROLL_STATUS IN ('DRAFT','APPROVED','PAID')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_PAYROLL PRIMARY KEY (PAYROLL_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_PAYROLL UNIQUE (EMPLOYEE_ID, SALARY_MONTH)
)
TABLESPACE HMS_DATA;
COMMENT ON TABLE HMS_PAYROLL IS 'SALARY_MONTH format YYYY-MM';

