/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 19_emergency_tables.sql
 Purpose   : Tables - EMERGENCY & AMBULANCE
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating tables : EMERGENCY & AMBULANCE

-- ----------------------------------------------------------------------------
-- HMS_EMERGENCY_VISIT
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_EMERGENCY_VISIT (
    ER_VISIT_ID            NUMBER DEFAULT SEQ_EMERGENCY_VISIT.NEXTVAL NOT NULL,
    ER_NO                  VARCHAR2(30) NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_EMERGENCY_VISIT_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    PATIENT_ID             NUMBER CONSTRAINT FK_EMERGENCY_VISIT_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    UNKNOWN_PATIENT_DESC   VARCHAR2(500),
    ARRIVAL_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP,
    ARRIVAL_MODE           VARCHAR2(20) CHECK (ARRIVAL_MODE IN ('WALK_IN','AMBULANCE','POLICE','REFERRED','OTHER')),
    BROUGHT_BY             VARCHAR2(200),
    IS_MLC                 CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_MLC IN ('Y','N')),
    ATTENDING_DOCTOR_ID    NUMBER CONSTRAINT FK_EMEVIS_ATTENDING_DOCTOR_ID REFERENCES HMS_DOCTOR(DOCTOR_ID),
    ER_OUTCOME             VARCHAR2(20) CHECK (ER_OUTCOME IN ('DISCHARGED','ADMITTED','REFERRED','LAMA','DEATH','BROUGHT_DEAD')),
    ADMISSION_ID           NUMBER CONSTRAINT FK_EMEVIS_ADMISSION_ID REFERENCES HMS_IPD_ADMISSION(ADMISSION_ID),
    DEPARTURE_TIME         TIMESTAMP,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_EMERGENCY_VISIT PRIMARY KEY (ER_VISIT_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_ER_NO UNIQUE (ER_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_EMERGENCY_TRIAGE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_EMERGENCY_TRIAGE (
    TRIAGE_ID              NUMBER DEFAULT SEQ_EMERGENCY_TRIAGE.NEXTVAL NOT NULL,
    ER_VISIT_ID            NUMBER NOT NULL CONSTRAINT FK_EMETRI_ER_VISIT_ID REFERENCES HMS_EMERGENCY_VISIT(ER_VISIT_ID),
    TRIAGE_LEVEL           VARCHAR2(10) CHECK (TRIAGE_LEVEL IN ('RED','ORANGE','YELLOW','GREEN','BLACK')),
    CHIEF_COMPLAINT        VARCHAR2(1000),
    BP_SYSTOLIC            NUMBER(3),
    BP_DIASTOLIC           NUMBER(3),
    PULSE_RATE             NUMBER(3),
    SPO2                   NUMBER(3),
    GCS_SCORE              NUMBER(2),
    TRIAGE_TIME            TIMESTAMP DEFAULT SYSTIMESTAMP,
    TRIAGED_BY             NUMBER CONSTRAINT FK_EMERGENCY_TRIAGE_TRIAGED_BY REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_EMERGENCY_TRIAGE PRIMARY KEY (TRIAGE_ID) USING INDEX TABLESPACE HMS_INDEX
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_AMBULANCE
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_AMBULANCE (
    AMBULANCE_ID           NUMBER DEFAULT SEQ_AMBULANCE.NEXTVAL NOT NULL,
    BRANCH_ID              NUMBER NOT NULL CONSTRAINT FK_AMBULANCE_BRANCH_ID REFERENCES HMS_BRANCH(BRANCH_ID),
    VEHICLE_NO             VARCHAR2(30) NOT NULL,
    AMBULANCE_TYPE         VARCHAR2(20) CHECK (AMBULANCE_TYPE IN ('BASIC','ACLS','ICU','NICU','FREEZER')),
    DRIVER_ID              NUMBER CONSTRAINT FK_AMBULANCE_DRIVER_ID REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID),
    DRIVER_PHONE           VARCHAR2(50),
    PER_KM_RATE            NUMBER(10,2),
    BASE_FARE              NUMBER(10,2),
    AMB_STATUS             VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (AMB_STATUS IN ('AVAILABLE','ON_TRIP','MAINTENANCE')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_AMBULANCE PRIMARY KEY (AMBULANCE_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_VEHICLE_NO UNIQUE (VEHICLE_NO)
)
TABLESPACE HMS_DATA;

-- ----------------------------------------------------------------------------
-- HMS_AMBULANCE_TRIP
-- ----------------------------------------------------------------------------
CREATE TABLE HMS_AMBULANCE_TRIP (
    TRIP_ID                NUMBER DEFAULT SEQ_AMBULANCE_TRIP.NEXTVAL NOT NULL,
    TRIP_NO                VARCHAR2(30) NOT NULL,
    AMBULANCE_ID           NUMBER NOT NULL CONSTRAINT FK_AMBULANCE_TRIP_AMBULANCE_ID REFERENCES HMS_AMBULANCE(AMBULANCE_ID),
    PATIENT_ID             NUMBER CONSTRAINT FK_AMBULANCE_TRIP_PATIENT_ID REFERENCES HMS_PATIENT(PATIENT_ID),
    CALLER_NAME            VARCHAR2(200),
    CALLER_PHONE           VARCHAR2(50),
    PICKUP_ADDRESS         VARCHAR2(500),
    DROP_ADDRESS           VARCHAR2(500),
    DISPATCH_TIME          TIMESTAMP,
    RETURN_TIME            TIMESTAMP,
    DISTANCE_KM            NUMBER(8,2),
    CHARGE_AMOUNT          NUMBER(12,2),
    TRIP_STATUS            VARCHAR2(20) DEFAULT 'REQUESTED' CHECK (TRIP_STATUS IN ('REQUESTED','DISPATCHED','COMPLETED','CANCELLED')),
    IS_ACTIVE              CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_BY             VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    CREATED_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_AMBULANCE_TRIP PRIMARY KEY (TRIP_ID) USING INDEX TABLESPACE HMS_INDEX,
    CONSTRAINT UK_TRIP_NO UNIQUE (TRIP_NO)
)
TABLESPACE HMS_DATA;

