/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : 99_late_foreign_keys.sql
 Purpose   : Late foreign keys (circular / forward reference)
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Adding late foreign keys ...
ALTER TABLE HMS_DEPARTMENT ADD CONSTRAINT FK_DEPT_HOD FOREIGN KEY (HOD_EMPLOYEE_ID) REFERENCES HMS_EMPLOYEE(EMPLOYEE_ID);
CREATE INDEX IX_DEPARTMENT_HOD_EMPLOYEE_ID ON HMS_DEPARTMENT(HOD_EMPLOYEE_ID) TABLESPACE HMS_INDEX;
ALTER TABLE HMS_APPOINTMENT ADD CONSTRAINT FK_APPT_OPD_VISIT FOREIGN KEY (OPD_VISIT_ID) REFERENCES HMS_OPD_VISIT(VISIT_ID);
CREATE INDEX IX_APPOINTMENT_OPD_VISIT_ID ON HMS_APPOINTMENT(OPD_VISIT_ID) TABLESPACE HMS_INDEX;
ALTER TABLE HMS_OPD_PRESCRIPTION_DTL ADD CONSTRAINT FK_PRESC_DTL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES HMS_PHARMA_ITEM(ITEM_ID);
CREATE INDEX IX_OPD_PRESCRIPTION_DTL_ITEM_I ON HMS_OPD_PRESCRIPTION_DTL(ITEM_ID) TABLESPACE HMS_INDEX;
ALTER TABLE HMS_IPD_MEDICATION ADD CONSTRAINT FK_IPD_MED_ITEM FOREIGN KEY (ITEM_ID) REFERENCES HMS_PHARMA_ITEM(ITEM_ID);
CREATE INDEX IX_IPD_MEDICATION_ITEM_ID ON HMS_IPD_MEDICATION(ITEM_ID) TABLESPACE HMS_INDEX;
ALTER TABLE HMS_IPD_ADMISSION ADD CONSTRAINT FK_ADM_POLICY FOREIGN KEY (INSURANCE_POLICY_ID) REFERENCES HMS_PATIENT_INSURANCE(POLICY_ID);
CREATE INDEX IX_IPD_ADMISSION_INSURANCE_POL ON HMS_IPD_ADMISSION(INSURANCE_POLICY_ID) TABLESPACE HMS_INDEX;
