/*
================================================================================
 File    : database/VERIFY.sql
 Run As  : HMS_APP
 Purpose : Install thik hoyeche kina check (object count + INVALID objects)
================================================================================
*/
SET PAGESIZE 100
SET LINESIZE 200
COLUMN OBJECT_TYPE FORMAT A20
COLUMN OBJECT_NAME FORMAT A40
PROMPT
PROMPT ---------- Object count ----------
SELECT OBJECT_TYPE, COUNT(*) AS TOTAL,
       SUM(CASE WHEN STATUS = 'VALID' THEN 1 ELSE 0 END) AS VALID
  FROM USER_OBJECTS
 WHERE OBJECT_TYPE IN ('TABLE','SEQUENCE','INDEX','VIEW','PACKAGE','PACKAGE BODY','FUNCTION','PROCEDURE','TRIGGER')
 GROUP BY OBJECT_TYPE ORDER BY OBJECT_TYPE;

PROMPT ---------- INVALID objects (khali thaka uchit) ----------
SELECT OBJECT_TYPE, OBJECT_NAME FROM USER_OBJECTS WHERE STATUS <> 'VALID' ORDER BY 1, 2;

PROMPT ---------- Compile errors (jodi thake) ----------
SELECT NAME, TYPE, LINE, SUBSTR(TEXT, 1, 120) AS ERROR_TEXT FROM USER_ERRORS ORDER BY NAME, SEQUENCE;

PROMPT ---------- Master data ----------
SELECT 'BRANCH' T, COUNT(*) C FROM HMS_BRANCH UNION ALL
SELECT 'DEPARTMENT', COUNT(*) FROM HMS_DEPARTMENT UNION ALL
SELECT 'SERVICE', COUNT(*) FROM HMS_SERVICE_MASTER UNION ALL
SELECT 'WARD', COUNT(*) FROM HMS_WARD UNION ALL
SELECT 'BED', COUNT(*) FROM HMS_BED UNION ALL
SELECT 'LOOKUP', COUNT(*) FROM HMS_LOOKUP_MASTER UNION ALL
SELECT 'USER', COUNT(*) FROM HMS_USER;
