/*
================================================================================
 File    : database/11_apex_support/03_apex_views.sql
 Run As  : HMS_APP
 Purpose : APEX page er report/LOV source view (Sprint 3-9)
================================================================================
*/
SET DEFINE OFF
PROMPT >>> APEX page views ...

-- Service LOV (lab/radiology/procedure)
CREATE OR REPLACE VIEW VW_LOV_SERVICE AS
SELECT s.SERVICE_NAME || ' (Tk ' || TO_CHAR(s.BASE_CHARGE, 'FM999G990') || ')' AS D,
       s.SERVICE_ID AS R, s.SERVICE_CODE, s.BASE_CHARGE, s.REPORTING_SECTION,
       c.CATEGORY_ID, s.DEPT_ID, s.SAMPLE_REQUIRED
  FROM HMS_SERVICE_MASTER s
  JOIN HMS_SERVICE_CATEGORY c ON c.CATEGORY_ID = s.CATEGORY_ID
 WHERE s.IS_ACTIVE = 'Y';

-- Medicine LOV with live stock (pharmacy sale / prescription)
CREATE OR REPLACE VIEW VW_LOV_MEDICINE AS
SELECT i.ITEM_NAME || NVL2(i.STRENGTH, ' ' || i.STRENGTH, NULL)
       || ' [' || i.DOSAGE_FORM || '] - Stock: '
       || NVL((SELECT SUM(st.QTY_AVAILABLE) FROM HMS_PHARMA_STOCK st
                WHERE st.ITEM_ID = i.ITEM_ID AND st.EXPIRY_DATE > SYSDATE AND st.IS_ACTIVE = 'Y'), 0) AS D,
       i.ITEM_ID AS R, i.ITEM_CODE, i.MRP, i.BARCODE, i.GENERIC_ID
  FROM HMS_PHARMA_ITEM i
 WHERE i.IS_ACTIVE = 'Y';

-- Bed map (Cards region: ward wise color)
CREATE OR REPLACE VIEW VW_BED_MAP AS
SELECT w.BRANCH_ID, w.WARD_ID, w.WARD_NAME, w.WARD_TYPE, w.FLOOR_NO,
       b.BED_ID, b.BED_NO, b.BED_TYPE, b.DAILY_CHARGE, b.BED_STATUS,
       CASE b.BED_STATUS WHEN 'AVAILABLE' THEN 'u-success' WHEN 'OCCUPIED' THEN 'u-danger'
                         WHEN 'RESERVED'  THEN 'u-warning' ELSE 'u-color-7' END AS STATUS_CSS,
       a.ADMISSION_ID, a.ADMISSION_NO, a.ADMISSION_DATE,
       p.MRN, TRIM(p.FIRST_NAME || ' ' || p.LAST_NAME) AS PATIENT_NAME
  FROM HMS_BED b
  JOIN HMS_WARD w ON w.WARD_ID = b.WARD_ID
  LEFT JOIN HMS_IPD_ADMISSION a ON a.BED_ID = b.BED_ID AND a.ADMISSION_STATUS = 'ADMITTED'
  LEFT JOIN HMS_PATIENT p       ON p.PATIENT_ID = a.PATIENT_ID
 WHERE b.IS_ACTIVE = 'Y' AND w.IS_ACTIVE = 'Y';

-- Bill list (Billing page 70/72)
CREATE OR REPLACE VIEW VW_BILL_LIST AS
SELECT b.BILL_ID, b.BILL_NO, b.BILL_DATE, b.BILL_TYPE, b.BRANCH_ID, b.PATIENT_ID,
       p.MRN, TRIM(p.FIRST_NAME || ' ' || p.LAST_NAME) AS PATIENT_NAME, p.PHONE_PRIMARY,
       b.GROSS_AMOUNT, b.DISCOUNT_AMOUNT, b.NET_AMOUNT, b.PAID_AMOUNT, b.DUE_AMOUNT, b.BILL_STATUS
  FROM HMS_BILLING b
  JOIN HMS_PATIENT p ON p.PATIENT_ID = b.PATIENT_ID;

-- Lab result entry grid source (page 52)
CREATE OR REPLACE VIEW VW_LAB_RESULT_ENTRY AS
SELECT d.ORDER_DTL_ID, o.ORDER_ID, o.ORDER_NO, o.BRANCH_ID, d.SERVICE_NAME, d.ITEM_STATUS,
       prm.PARAMETER_ID, prm.PARAMETER_NAME, prm.GROUP_NAME, prm.DISPLAY_ORDER, prm.UNIT, prm.RESULT_TYPE,
       r.RESULT_ID, r.RESULT_VALUE, r.RESULT_FLAG, r.REFERENCE_RANGE, r.RESULT_STATUS
  FROM HMS_INVESTIGATION_ORDER_DTL d
  JOIN HMS_INVESTIGATION_ORDER o ON o.ORDER_ID = d.ORDER_ID
  JOIN HMS_LAB_PARAMETER prm     ON prm.SERVICE_ID = d.SERVICE_ID AND prm.IS_ACTIVE = 'Y'
  LEFT JOIN HMS_LAB_RESULT r     ON r.ORDER_DTL_ID = d.ORDER_DTL_ID AND r.PARAMETER_ID = prm.PARAMETER_ID
 WHERE d.ITEM_STATUS <> 'CANCELLED';

-- Appointment calendar (page 31)
CREATE OR REPLACE VIEW VW_APPOINTMENT_CAL AS
SELECT a.APPOINTMENT_ID, a.APPOINTMENT_NO, a.BRANCH_ID, a.DOCTOR_ID,
       NVL(TRIM(p.FIRST_NAME || ' ' || p.LAST_NAME), a.PATIENT_NAME) AS PATIENT_NAME,
       NVL(p.PHONE_PRIMARY, a.MOBILE_NO) AS MOBILE,
       'Dr. ' || TRIM(e.FIRST_NAME || ' ' || e.LAST_NAME) AS DOCTOR_NAME,
       a.APPOINTMENT_DATE, a.SLOT_TIME, a.SERIAL_NO, a.APPOINTMENT_STATUS,
       TO_DATE(TO_CHAR(a.APPOINTMENT_DATE, 'YYYY-MM-DD') || ' ' || NVL(a.SLOT_TIME, '09:00'),
               'YYYY-MM-DD HH24:MI') AS START_DT
  FROM HMS_APPOINTMENT a
  JOIN HMS_DOCTOR d   ON d.DOCTOR_ID = a.DOCTOR_ID
  JOIN HMS_EMPLOYEE e ON e.EMPLOYEE_ID = d.EMPLOYEE_ID
  LEFT JOIN HMS_PATIENT p ON p.PATIENT_ID = a.PATIENT_ID;

-- Doctor er aj ker queue (Doctor Dashboard / Consultation)
CREATE OR REPLACE VIEW VW_DOCTOR_QUEUE AS
SELECT v.VISIT_ID, v.VISIT_NO, v.TOKEN_NO, v.VISIT_DATE, v.VISIT_STATUS, v.DOCTOR_ID, v.BRANCH_ID,
       v.PATIENT_ID, p.MRN, TRIM(p.FIRST_NAME || ' ' || p.LAST_NAME) AS PATIENT_NAME,
       p.GENDER, FN_CALCULATE_AGE(p.DATE_OF_BIRTH) AS AGE,
       d.EMPLOYEE_ID AS DOCTOR_EMPLOYEE_ID
  FROM HMS_OPD_VISIT v
  JOIN HMS_PATIENT p ON p.PATIENT_ID = v.PATIENT_ID
  JOIN HMS_DOCTOR  d ON d.DOCTOR_ID = v.DOCTOR_ID
 WHERE v.VISIT_DATE = TRUNC(SYSDATE) AND v.VISIT_STATUS IN ('WAITING','IN_CONSULTATION');

SELECT OBJECT_NAME, STATUS FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('VW_LOV_SERVICE','VW_LOV_MEDICINE','VW_BED_MAP','VW_BILL_LIST',
                       'VW_LAB_RESULT_ENTRY','VW_APPOINTMENT_CAL','VW_DOCTOR_QUEUE','PKG_LAB');
