/*
 File   : database/11_apex_support/05_fix_lookup_data.sql
 Run As : HMS_APP   (barbar run kora safe - ja ache ta abar dhukbe na)
 Purpose: Dropdown (Gender, Blood Group, Religion...) er data HMS_LOOKUP_MASTER e dhukano
*/
SET DEFINE OFF
INSERT INTO HMS_LOOKUP_MASTER (LOOKUP_TYPE, LOOKUP_CODE, LOOKUP_VALUE, DISPLAY_ORDER)
SELECT x.t, x.c, x.v, x.o FROM (
SELECT 'BLOOD_GROUP' t,'A+' c,'A+' v,1 o FROM DUAL UNION ALL
SELECT 'BLOOD_GROUP','A-','A-',2 FROM DUAL UNION ALL
SELECT 'BLOOD_GROUP','B+','B+',3 FROM DUAL UNION ALL
SELECT 'BLOOD_GROUP','B-','B-',4 FROM DUAL UNION ALL
SELECT 'BLOOD_GROUP','AB+','AB+',5 FROM DUAL UNION ALL
SELECT 'BLOOD_GROUP','AB-','AB-',6 FROM DUAL UNION ALL
SELECT 'BLOOD_GROUP','O+','O+',7 FROM DUAL UNION ALL
SELECT 'BLOOD_GROUP','O-','O-',8 FROM DUAL UNION ALL
SELECT 'GENDER','MALE','Male',1 FROM DUAL UNION ALL
SELECT 'GENDER','FEMALE','Female',2 FROM DUAL UNION ALL
SELECT 'GENDER','OTHER','Other',3 FROM DUAL UNION ALL
SELECT 'TITLE','MR','Mr.',1 FROM DUAL UNION ALL
SELECT 'TITLE','MRS','Mrs.',2 FROM DUAL UNION ALL
SELECT 'TITLE','MS','Ms.',3 FROM DUAL UNION ALL
SELECT 'TITLE','MASTER','Master',4 FROM DUAL UNION ALL
SELECT 'TITLE','BABY','Baby',5 FROM DUAL UNION ALL
SELECT 'TITLE','DR','Dr.',6 FROM DUAL UNION ALL
SELECT 'MARITAL_STATUS','SINGLE','Single',1 FROM DUAL UNION ALL
SELECT 'MARITAL_STATUS','MARRIED','Married',2 FROM DUAL UNION ALL
SELECT 'MARITAL_STATUS','DIVORCED','Divorced',3 FROM DUAL UNION ALL
SELECT 'MARITAL_STATUS','WIDOWED','Widowed',4 FROM DUAL UNION ALL
SELECT 'RELIGION','ISLAM','Islam',1 FROM DUAL UNION ALL
SELECT 'RELIGION','HINDU','Hinduism',2 FROM DUAL UNION ALL
SELECT 'RELIGION','BUDDHIST','Buddhism',3 FROM DUAL UNION ALL
SELECT 'RELIGION','CHRISTIAN','Christianity',4 FROM DUAL UNION ALL
SELECT 'RELIGION','OTHER','Other',5 FROM DUAL UNION ALL
SELECT 'RELATION','FATHER','Father',1 FROM DUAL UNION ALL
SELECT 'RELATION','MOTHER','Mother',2 FROM DUAL UNION ALL
SELECT 'RELATION','HUSBAND','Husband',3 FROM DUAL UNION ALL
SELECT 'RELATION','WIFE','Wife',4 FROM DUAL UNION ALL
SELECT 'RELATION','SON','Son',5 FROM DUAL UNION ALL
SELECT 'RELATION','DAUGHTER','Daughter',6 FROM DUAL UNION ALL
SELECT 'RELATION','BROTHER','Brother',7 FROM DUAL UNION ALL
SELECT 'RELATION','SISTER','Sister',8 FROM DUAL UNION ALL
SELECT 'RELATION','OTHER','Other',9 FROM DUAL UNION ALL
SELECT 'PAYMENT_MODE','CASH','Cash',1 FROM DUAL UNION ALL
SELECT 'PAYMENT_MODE','CARD','Card',2 FROM DUAL UNION ALL
SELECT 'PAYMENT_MODE','BKASH','bKash',3 FROM DUAL UNION ALL
SELECT 'PAYMENT_MODE','NAGAD','Nagad',4 FROM DUAL UNION ALL
SELECT 'PAYMENT_MODE','ROCKET','Rocket',5 FROM DUAL UNION ALL
SELECT 'PAYMENT_MODE','BANK','Bank Transfer',6 FROM DUAL UNION ALL
SELECT 'PAYMENT_MODE','CHEQUE','Cheque',7 FROM DUAL UNION ALL
SELECT 'DIVISION','DHAKA','Dhaka',1 FROM DUAL UNION ALL
SELECT 'DIVISION','CHATTOGRAM','Chattogram',2 FROM DUAL UNION ALL
SELECT 'DIVISION','RAJSHAHI','Rajshahi',3 FROM DUAL UNION ALL
SELECT 'DIVISION','KHULNA','Khulna',4 FROM DUAL UNION ALL
SELECT 'DIVISION','BARISHAL','Barishal',5 FROM DUAL UNION ALL
SELECT 'DIVISION','SYLHET','Sylhet',6 FROM DUAL UNION ALL
SELECT 'DIVISION','RANGPUR','Rangpur',7 FROM DUAL UNION ALL
SELECT 'DIVISION','MYMENSINGH','Mymensingh',8 FROM DUAL UNION ALL
SELECT 'FREQUENCY','1+0+0','1+0+0 (Morning)',1 FROM DUAL UNION ALL
SELECT 'FREQUENCY','0+0+1','0+0+1 (Night)',2 FROM DUAL UNION ALL
SELECT 'FREQUENCY','1+0+1','1+0+1',3 FROM DUAL UNION ALL
SELECT 'FREQUENCY','1+1+1','1+1+1',4 FROM DUAL UNION ALL
SELECT 'FREQUENCY','1+1+1+1','1+1+1+1',5 FROM DUAL UNION ALL
SELECT 'FREQUENCY','SOS','SOS (when needed)',6 FROM DUAL UNION ALL
SELECT 'ROUTE','ORAL','Oral',1 FROM DUAL UNION ALL
SELECT 'ROUTE','IV','IV',2 FROM DUAL UNION ALL
SELECT 'ROUTE','IM','IM',3 FROM DUAL UNION ALL
SELECT 'ROUTE','SC','SC',4 FROM DUAL UNION ALL
SELECT 'ROUTE','TOPICAL','Topical',5 FROM DUAL UNION ALL
SELECT 'ROUTE','INHALATION','Inhalation',6 FROM DUAL UNION ALL
SELECT 'ROUTE','PR','Per Rectal',7 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','TAB','Tablet',1 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','CAP','Capsule',2 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','SYP','Syrup',3 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','INJ','Injection',4 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','INF','Infusion',5 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','OINT','Ointment',6 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','DROP','Drops',7 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','SUPP','Suppository',8 FROM DUAL UNION ALL
SELECT 'DOSAGE_FORM','INH','Inhaler',9 FROM DUAL UNION ALL
SELECT 'DOCUMENT_TYPE','NID','NID Copy',1 FROM DUAL UNION ALL
SELECT 'DOCUMENT_TYPE','PRESCRIPTION','Old Prescription',2 FROM DUAL UNION ALL
SELECT 'DOCUMENT_TYPE','REPORT','Investigation Report',3 FROM DUAL UNION ALL
SELECT 'DOCUMENT_TYPE','CONSENT','Consent Form',4 FROM DUAL UNION ALL
SELECT 'DOCUMENT_TYPE','INSURANCE','Insurance Card',5 FROM DUAL
) x
WHERE NOT EXISTS (SELECT 1 FROM HMS_LOOKUP_MASTER m WHERE m.LOOKUP_TYPE = x.t AND m.LOOKUP_CODE = x.c);

COMMIT;

SELECT LOOKUP_TYPE, COUNT(*) CNT FROM HMS_LOOKUP_MASTER GROUP BY LOOKUP_TYPE ORDER BY 1;
