/*
================================================================================
 File    : database/07_views/create_all_views.sql
 Run As  : HMS_APP
 Purpose : Reporting / APEX dashboard views
================================================================================
*/
SET DEFINE OFF
PROMPT >>> Creating views ...

-- 1. Patient summary (APEX patient search page er jonno)
CREATE OR REPLACE VIEW VW_PATIENT_SUMMARY AS
SELECT p.PATIENT_ID,
       p.MRN,
       REGEXP_REPLACE(TRIM(p.FIRST_NAME || ' ' || p.MIDDLE_NAME || ' ' || p.LAST_NAME), ' +', ' ') AS PATIENT_NAME,
       p.GENDER,
       p.DATE_OF_BIRTH,
       FN_CALCULATE_AGE(p.DATE_OF_BIRTH) AS AGE,
       p.BLOOD_GROUP,
       p.PHONE_PRIMARY,
       p.PATIENT_CATEGORY,
       p.REGISTRATION_DATE,
       b.BRANCH_NAME,
       (SELECT COUNT(*) FROM HMS_OPD_VISIT v WHERE v.PATIENT_ID = p.PATIENT_ID)       AS TOTAL_OPD_VISITS,
       (SELECT MAX(v.VISIT_DATE) FROM HMS_OPD_VISIT v WHERE v.PATIENT_ID = p.PATIENT_ID) AS LAST_OPD_VISIT,
       (SELECT COUNT(*) FROM HMS_IPD_ADMISSION a WHERE a.PATIENT_ID = p.PATIENT_ID)   AS TOTAL_ADMISSIONS,
       (SELECT MAX(a.ADMISSION_NO) KEEP (DENSE_RANK LAST ORDER BY a.ADMISSION_DATE)
          FROM HMS_IPD_ADMISSION a
         WHERE a.PATIENT_ID = p.PATIENT_ID AND a.ADMISSION_STATUS = 'ADMITTED')          AS CURRENT_ADMISSION_NO,
       (SELECT NVL(SUM(bl.DUE_AMOUNT), 0) FROM HMS_BILLING bl
         WHERE bl.PATIENT_ID = p.PATIENT_ID AND bl.BILL_STATUS IN ('OPEN','PARTIAL'))   AS TOTAL_DUE,
       (SELECT LISTAGG(al.ALLERGY_NAME, ', ') WITHIN GROUP (ORDER BY al.ALLERGY_NAME)
          FROM HMS_PATIENT_ALLERGY al
         WHERE al.PATIENT_ID = p.PATIENT_ID AND al.IS_ACTIVE = 'Y')                     AS ALLERGIES,
       p.IS_ACTIVE
  FROM HMS_PATIENT p
  JOIN HMS_BRANCH  b ON b.BRANCH_ID = p.BRANCH_ID;

-- 2. OPD dashboard (aj ke kon doctor er kache wait korche)
CREATE OR REPLACE VIEW VW_OPD_DASHBOARD AS
SELECT v.VISIT_ID,
       v.VISIT_NO,
       v.VISIT_DATE,
       v.TOKEN_NO,
       v.VISIT_TYPE,
       v.VISIT_STATUS,
       v.PAYMENT_STATUS,
       p.MRN,
       p.FIRST_NAME || ' ' || p.LAST_NAME        AS PATIENT_NAME,
       p.GENDER,
       FN_CALCULATE_AGE(p.DATE_OF_BIRTH)         AS AGE,
       p.PHONE_PRIMARY,
       v.DOCTOR_ID,
       e.FIRST_NAME || ' ' || e.LAST_NAME        AS DOCTOR_NAME,
       d.DEPT_NAME,
       v.NET_FEE,
       v.VISIT_TIME,
       ROUND((CAST(SYSTIMESTAMP AS DATE) - CAST(v.VISIT_TIME AS DATE)) * 24 * 60) AS WAITING_MIN,
       v.BRANCH_ID
  FROM HMS_OPD_VISIT v
  JOIN HMS_PATIENT   p  ON p.PATIENT_ID = v.PATIENT_ID
  JOIN HMS_DOCTOR    dr ON dr.DOCTOR_ID = v.DOCTOR_ID
  JOIN HMS_EMPLOYEE  e  ON e.EMPLOYEE_ID = dr.EMPLOYEE_ID
  JOIN HMS_DEPARTMENT d ON d.DEPT_ID = v.DEPT_ID;

-- 3. Bed occupancy (ward wise)
CREATE OR REPLACE VIEW VW_BED_OCCUPANCY AS
SELECT w.BRANCH_ID,
       w.WARD_ID,
       w.WARD_CODE,
       w.WARD_NAME,
       w.WARD_TYPE,
       COUNT(b.BED_ID)                                              AS TOTAL_BEDS,
       SUM(CASE WHEN b.BED_STATUS = 'OCCUPIED'    THEN 1 ELSE 0 END) AS OCCUPIED,
       SUM(CASE WHEN b.BED_STATUS = 'AVAILABLE'   THEN 1 ELSE 0 END) AS AVAILABLE,
       SUM(CASE WHEN b.BED_STATUS = 'RESERVED'    THEN 1 ELSE 0 END) AS RESERVED,
       SUM(CASE WHEN b.BED_STATUS IN ('CLEANING','MAINTENANCE') THEN 1 ELSE 0 END) AS NOT_READY,
       ROUND(100 * SUM(CASE WHEN b.BED_STATUS = 'OCCUPIED' THEN 1 ELSE 0 END)
                 / NULLIF(COUNT(b.BED_ID), 0), 1)                    AS OCCUPANCY_PCT
  FROM HMS_WARD w
  LEFT JOIN HMS_BED b ON b.WARD_ID = w.WARD_ID AND b.IS_ACTIVE = 'Y'
 WHERE w.IS_ACTIVE = 'Y'
 GROUP BY w.BRANCH_ID, w.WARD_ID, w.WARD_CODE, w.WARD_NAME, w.WARD_TYPE;

-- 4. Current IPD patients
CREATE OR REPLACE VIEW VW_IPD_CURRENT_PATIENTS AS
SELECT a.ADMISSION_ID,
       a.ADMISSION_NO,
       a.ADMISSION_DATE,
       TRUNC(SYSDATE - CAST(a.ADMISSION_DATE AS DATE)) + 1 AS STAY_DAYS,
       p.MRN,
       p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
       p.GENDER,
       w.WARD_NAME,
       b.BED_NO,
       e.FIRST_NAME || ' ' || e.LAST_NAME AS DOCTOR_NAME,
       a.ADMISSION_STATUS,
       bl.NET_AMOUNT  AS BILL_AMOUNT,
       bl.PAID_AMOUNT,
       bl.DUE_AMOUNT,
       (SELECT NVL(SUM(ad.AMOUNT - ad.ADJUSTED_AMOUNT - ad.REFUNDED_AMOUNT), 0)
          FROM HMS_PATIENT_ADVANCE ad
         WHERE ad.ADMISSION_ID = a.ADMISSION_ID AND ad.ADVANCE_STATUS = 'ACTIVE') AS ADVANCE_BALANCE,
       a.BRANCH_ID
  FROM HMS_IPD_ADMISSION a
  JOIN HMS_PATIENT  p  ON p.PATIENT_ID = a.PATIENT_ID
  JOIN HMS_WARD     w  ON w.WARD_ID = a.WARD_ID
  JOIN HMS_BED      b  ON b.BED_ID = a.BED_ID
  JOIN HMS_DOCTOR   dr ON dr.DOCTOR_ID = a.ADMITTING_DOCTOR_ID
  JOIN HMS_EMPLOYEE e  ON e.EMPLOYEE_ID = dr.EMPLOYEE_ID
  LEFT JOIN HMS_BILLING bl ON bl.ADMISSION_ID = a.ADMISSION_ID AND bl.BILL_TYPE = 'IPD' AND bl.BILL_STATUS <> 'CANCELLED'
 WHERE a.ADMISSION_STATUS IN ('ADMITTED','DISCHARGE_INITIATED');

-- 5. Daily revenue (collection) - date + bill type + payment mode
CREATE OR REPLACE VIEW VW_DAILY_REVENUE AS
SELECT r.BRANCH_ID,
       TRUNC(r.RECEIPT_DATE)  AS COLLECTION_DATE,
       NVL(b.BILL_TYPE, 'ADVANCE') AS BILL_TYPE,
       r.PAYMENT_MODE,
       COUNT(*)               AS RECEIPT_COUNT,
       SUM(CASE WHEN r.RECEIPT_TYPE = 'REFUND' THEN -r.AMOUNT ELSE r.AMOUNT END) AS NET_COLLECTION
  FROM HMS_PAYMENT_RECEIPT r
  LEFT JOIN HMS_BILLING b ON b.BILL_ID = r.BILL_ID
 WHERE r.RECEIPT_STATUS = 'VALID'
   AND r.RECEIPT_TYPE <> 'ADJUSTMENT'
 GROUP BY r.BRANCH_ID, TRUNC(r.RECEIPT_DATE), NVL(b.BILL_TYPE, 'ADVANCE'), r.PAYMENT_MODE;

-- 6. Pharmacy stock status (low stock + expiry alert)
CREATE OR REPLACE VIEW VW_PHARMA_STOCK_STATUS AS
SELECT s.STORE_ID,
       st.STORE_NAME,
       i.ITEM_ID,
       i.ITEM_CODE,
       i.ITEM_NAME,
       g.GENERIC_NAME,
       SUM(s.QTY_AVAILABLE)                                         AS TOTAL_QTY,
       i.REORDER_LEVEL,
       MIN(CASE WHEN s.QTY_AVAILABLE > 0 THEN s.EXPIRY_DATE END)    AS NEAREST_EXPIRY,
       CASE WHEN SUM(s.QTY_AVAILABLE) = 0 THEN 'OUT_OF_STOCK'
            WHEN SUM(s.QTY_AVAILABLE) <= i.REORDER_LEVEL THEN 'LOW_STOCK'
            ELSE 'OK' END                                            AS STOCK_FLAG,
       CASE WHEN MIN(CASE WHEN s.QTY_AVAILABLE > 0 THEN s.EXPIRY_DATE END) <= TRUNC(SYSDATE) THEN 'EXPIRED'
            WHEN MIN(CASE WHEN s.QTY_AVAILABLE > 0 THEN s.EXPIRY_DATE END) <= TRUNC(SYSDATE) + 90 THEN 'EXPIRING_90D'
            ELSE 'OK' END                                            AS EXPIRY_FLAG
  FROM HMS_PHARMA_STOCK s
  JOIN HMS_PHARMA_ITEM  i  ON i.ITEM_ID = s.ITEM_ID
  JOIN HMS_PHARMA_STORE st ON st.STORE_ID = s.STORE_ID
  LEFT JOIN HMS_PHARMA_GENERIC g ON g.GENERIC_ID = i.GENERIC_ID
 GROUP BY s.STORE_ID, st.STORE_NAME, i.ITEM_ID, i.ITEM_CODE, i.ITEM_NAME, g.GENERIC_NAME, i.REORDER_LEVEL;

-- 7. Lab pending work list
CREATE OR REPLACE VIEW VW_LAB_PENDING AS
SELECT o.ORDER_ID,
       o.ORDER_NO,
       o.ORDER_DATE,
       o.PRIORITY,
       o.ORDER_SOURCE,
       p.MRN,
       p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
       d.ORDER_DTL_ID,
       d.SERVICE_NAME,
       d.ITEM_STATUS,
       sm.REPORTING_SECTION,
       ROUND((CAST(SYSTIMESTAMP AS DATE) - CAST(o.ORDER_DATE AS DATE)) * 24, 1) AS PENDING_HOURS,
       o.BRANCH_ID
  FROM HMS_INVESTIGATION_ORDER o
  JOIN HMS_INVESTIGATION_ORDER_DTL d ON d.ORDER_ID = o.ORDER_ID
  JOIN HMS_SERVICE_MASTER sm         ON sm.SERVICE_ID = d.SERVICE_ID
  JOIN HMS_PATIENT p                 ON p.PATIENT_ID = o.PATIENT_ID
 WHERE d.ITEM_STATUS NOT IN ('VERIFIED','DELIVERED','CANCELLED');

-- 8. Doctor wise daily OPD count + income
CREATE OR REPLACE VIEW VW_DOCTOR_DAILY_OPD AS
SELECT v.VISIT_DATE,
       v.DOCTOR_ID,
       e.FIRST_NAME || ' ' || e.LAST_NAME AS DOCTOR_NAME,
       COUNT(*)                                                   AS TOTAL_PATIENTS,
       SUM(CASE WHEN v.VISIT_TYPE = 'NEW' THEN 1 ELSE 0 END)      AS NEW_PATIENTS,
       SUM(CASE WHEN v.IS_FOLLOWUP = 'Y' THEN 1 ELSE 0 END)       AS FOLLOWUP_PATIENTS,
       SUM(v.NET_FEE)                                             AS TOTAL_FEE
  FROM HMS_OPD_VISIT v
  JOIN HMS_DOCTOR dr  ON dr.DOCTOR_ID = v.DOCTOR_ID
  JOIN HMS_EMPLOYEE e ON e.EMPLOYEE_ID = dr.EMPLOYEE_ID
 WHERE v.VISIT_STATUS <> 'CANCELLED'
 GROUP BY v.VISIT_DATE, v.DOCTOR_ID, e.FIRST_NAME || ' ' || e.LAST_NAME;
