/*
================================================================================
 Project   : Hospital Management System (HMS)
 Database  : Oracle 19c
 File      : TRG_AUDIT_COLUMNS.sql
 Purpose   : UPDATED_BY / UPDATED_DATE auto set (every table, BEFORE UPDATE)
 Run As    : HMS_APP
 Generated : 2026-09-26
================================================================================
*/
SET DEFINE OFF

PROMPT >>> Creating audit-column triggers ...
CREATE OR REPLACE TRIGGER TRG_BRANCH_BU
BEFORE UPDATE ON HMS_BRANCH FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DEPARTMENT_BU
BEFORE UPDATE ON HMS_DEPARTMENT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DESIGNATION_BU
BEFORE UPDATE ON HMS_DESIGNATION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_EMPLOYEE_BU
BEFORE UPDATE ON HMS_EMPLOYEE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_EMPLOYEE_QUALIFICATION_BU
BEFORE UPDATE ON HMS_EMPLOYEE_QUALIFICATION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_EMPLOYEE_EXPERIENCE_BU
BEFORE UPDATE ON HMS_EMPLOYEE_EXPERIENCE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DOCTOR_BU
BEFORE UPDATE ON HMS_DOCTOR FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DOCTOR_DEPT_MAP_BU
BEFORE UPDATE ON HMS_DOCTOR_DEPT_MAP FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DOCTOR_SCHEDULE_BU
BEFORE UPDATE ON HMS_DOCTOR_SCHEDULE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LOOKUP_MASTER_BU
BEFORE UPDATE ON HMS_LOOKUP_MASTER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_SYSTEM_CONFIG_BU
BEFORE UPDATE ON HMS_SYSTEM_CONFIG FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_NUMBER_SERIES_BU
BEFORE UPDATE ON HMS_NUMBER_SERIES FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_ICD_MASTER_BU
BEFORE UPDATE ON HMS_ICD_MASTER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_SHIFT_MASTER_BU
BEFORE UPDATE ON HMS_SHIFT_MASTER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_ROLE_BU
BEFORE UPDATE ON HMS_ROLE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_APP_MODULE_BU
BEFORE UPDATE ON HMS_APP_MODULE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_ROLE_PERMISSION_BU
BEFORE UPDATE ON HMS_ROLE_PERMISSION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_USER_BU
BEFORE UPDATE ON HMS_USER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_USER_ROLE_BU
BEFORE UPDATE ON HMS_USER_ROLE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LOGIN_HISTORY_BU
BEFORE UPDATE ON HMS_LOGIN_HISTORY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PATIENT_BU
BEFORE UPDATE ON HMS_PATIENT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PATIENT_ALLERGY_BU
BEFORE UPDATE ON HMS_PATIENT_ALLERGY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PATIENT_MEDICAL_HISTORY_BU
BEFORE UPDATE ON HMS_PATIENT_MEDICAL_HISTORY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PATIENT_DOCUMENT_BU
BEFORE UPDATE ON HMS_PATIENT_DOCUMENT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_SERVICE_CATEGORY_BU
BEFORE UPDATE ON HMS_SERVICE_CATEGORY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_SERVICE_MASTER_BU
BEFORE UPDATE ON HMS_SERVICE_MASTER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_SERVICE_CHARGE_BU
BEFORE UPDATE ON HMS_SERVICE_CHARGE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_SERVICE_PACKAGE_DTL_BU
BEFORE UPDATE ON HMS_SERVICE_PACKAGE_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DOCTOR_COMMISSION_BU
BEFORE UPDATE ON HMS_DOCTOR_COMMISSION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_APPOINTMENT_BU
BEFORE UPDATE ON HMS_APPOINTMENT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_COMMUNICATION_LOG_BU
BEFORE UPDATE ON HMS_COMMUNICATION_LOG FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OPD_VISIT_BU
BEFORE UPDATE ON HMS_OPD_VISIT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OPD_VITALS_BU
BEFORE UPDATE ON HMS_OPD_VITALS FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OPD_CONSULTATION_BU
BEFORE UPDATE ON HMS_OPD_CONSULTATION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OPD_PRESCRIPTION_BU
BEFORE UPDATE ON HMS_OPD_PRESCRIPTION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OPD_PRESCRIPTION_DTL_BU
BEFORE UPDATE ON HMS_OPD_PRESCRIPTION_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OPD_PROCEDURE_BU
BEFORE UPDATE ON HMS_OPD_PROCEDURE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_WARD_BU
BEFORE UPDATE ON HMS_WARD FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BED_BU
BEFORE UPDATE ON HMS_BED FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_IPD_ADMISSION_BU
BEFORE UPDATE ON HMS_IPD_ADMISSION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BED_TRANSFER_BU
BEFORE UPDATE ON HMS_BED_TRANSFER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_IPD_DOCTOR_VISIT_BU
BEFORE UPDATE ON HMS_IPD_DOCTOR_VISIT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_IPD_MEDICATION_BU
BEFORE UPDATE ON HMS_IPD_MEDICATION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_IPD_MED_ADMINISTRATION_BU
BEFORE UPDATE ON HMS_IPD_MED_ADMINISTRATION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DISCHARGE_SUMMARY_BU
BEFORE UPDATE ON HMS_DISCHARGE_SUMMARY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INVESTIGATION_ORDER_BU
BEFORE UPDATE ON HMS_INVESTIGATION_ORDER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INVESTIGATION_ORDER_DTL_BU
BEFORE UPDATE ON HMS_INVESTIGATION_ORDER_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LAB_PARAMETER_BU
BEFORE UPDATE ON HMS_LAB_PARAMETER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LAB_REFERENCE_RANGE_BU
BEFORE UPDATE ON HMS_LAB_REFERENCE_RANGE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LAB_SAMPLE_BU
BEFORE UPDATE ON HMS_LAB_SAMPLE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LAB_EQUIPMENT_BU
BEFORE UPDATE ON HMS_LAB_EQUIPMENT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LAB_RESULT_BU
BEFORE UPDATE ON HMS_LAB_RESULT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LAB_RESULT_AMENDMENT_BU
BEFORE UPDATE ON HMS_LAB_RESULT_AMENDMENT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_RADIOLOGY_ORDER_BU
BEFORE UPDATE ON HMS_RADIOLOGY_ORDER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_RADIOLOGY_IMAGE_BU
BEFORE UPDATE ON HMS_RADIOLOGY_IMAGE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_REPORT_TEMPLATE_BU
BEFORE UPDATE ON HMS_REPORT_TEMPLATE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_CATEGORY_BU
BEFORE UPDATE ON HMS_PHARMA_CATEGORY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_GENERIC_BU
BEFORE UPDATE ON HMS_PHARMA_GENERIC FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_MANUFACTURER_BU
BEFORE UPDATE ON HMS_PHARMA_MANUFACTURER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_ITEM_BU
BEFORE UPDATE ON HMS_PHARMA_ITEM FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_SUPPLIER_BU
BEFORE UPDATE ON HMS_PHARMA_SUPPLIER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_STORE_BU
BEFORE UPDATE ON HMS_PHARMA_STORE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_PURCHASE_ORDER_BU
BEFORE UPDATE ON HMS_PHARMA_PURCHASE_ORDER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_PO_DTL_BU
BEFORE UPDATE ON HMS_PHARMA_PO_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_GRN_BU
BEFORE UPDATE ON HMS_PHARMA_GRN FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_GRN_DTL_BU
BEFORE UPDATE ON HMS_PHARMA_GRN_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_STOCK_BU
BEFORE UPDATE ON HMS_PHARMA_STOCK FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_SALE_BU
BEFORE UPDATE ON HMS_PHARMA_SALE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_SALE_DTL_BU
BEFORE UPDATE ON HMS_PHARMA_SALE_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_SALE_RETURN_BU
BEFORE UPDATE ON HMS_PHARMA_SALE_RETURN FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PHARMA_TRANSACTION_BU
BEFORE UPDATE ON HMS_PHARMA_TRANSACTION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OT_MASTER_BU
BEFORE UPDATE ON HMS_OT_MASTER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_SURGERY_MASTER_BU
BEFORE UPDATE ON HMS_SURGERY_MASTER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OT_BOOKING_BU
BEFORE UPDATE ON HMS_OT_BOOKING FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OT_TEAM_BU
BEFORE UPDATE ON HMS_OT_TEAM FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OT_NOTES_BU
BEFORE UPDATE ON HMS_OT_NOTES FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_OT_CONSUMABLE_BU
BEFORE UPDATE ON HMS_OT_CONSUMABLE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BLOOD_DONOR_BU
BEFORE UPDATE ON HMS_BLOOD_DONOR FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BLOOD_COLLECTION_BU
BEFORE UPDATE ON HMS_BLOOD_COLLECTION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BLOOD_INVENTORY_BU
BEFORE UPDATE ON HMS_BLOOD_INVENTORY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BLOOD_REQUISITION_BU
BEFORE UPDATE ON HMS_BLOOD_REQUISITION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BLOOD_CROSSMATCH_BU
BEFORE UPDATE ON HMS_BLOOD_CROSSMATCH FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BLOOD_ISSUE_BU
BEFORE UPDATE ON HMS_BLOOD_ISSUE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_NURSING_ASSESSMENT_BU
BEFORE UPDATE ON HMS_NURSING_ASSESSMENT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_IPD_VITALS_BU
BEFORE UPDATE ON HMS_IPD_VITALS FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_NURSING_CARE_PLAN_BU
BEFORE UPDATE ON HMS_NURSING_CARE_PLAN FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_NURSING_NOTES_BU
BEFORE UPDATE ON HMS_NURSING_NOTES FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DIET_MASTER_BU
BEFORE UPDATE ON HMS_DIET_MASTER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DIET_ORDER_BU
BEFORE UPDATE ON HMS_DIET_ORDER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DIET_SERVING_BU
BEFORE UPDATE ON HMS_DIET_SERVING FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INSURANCE_COMPANY_BU
BEFORE UPDATE ON HMS_INSURANCE_COMPANY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INSURANCE_PLAN_BU
BEFORE UPDATE ON HMS_INSURANCE_PLAN FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PATIENT_INSURANCE_BU
BEFORE UPDATE ON HMS_PATIENT_INSURANCE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INSURANCE_PREAUTH_BU
BEFORE UPDATE ON HMS_INSURANCE_PREAUTH FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BILLING_BU
BEFORE UPDATE ON HMS_BILLING FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_BILLING_DTL_BU
BEFORE UPDATE ON HMS_BILLING_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PATIENT_ADVANCE_BU
BEFORE UPDATE ON HMS_PATIENT_ADVANCE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PAYMENT_RECEIPT_BU
BEFORE UPDATE ON HMS_PAYMENT_RECEIPT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INSURANCE_CLAIM_BU
BEFORE UPDATE ON HMS_INSURANCE_CLAIM FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DOCTOR_EARNING_BU
BEFORE UPDATE ON HMS_DOCTOR_EARNING FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_CHART_OF_ACCOUNTS_BU
BEFORE UPDATE ON HMS_CHART_OF_ACCOUNTS FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_JOURNAL_VOUCHER_BU
BEFORE UPDATE ON HMS_JOURNAL_VOUCHER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_JOURNAL_VOUCHER_DTL_BU
BEFORE UPDATE ON HMS_JOURNAL_VOUCHER_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INV_STORE_BU
BEFORE UPDATE ON HMS_INV_STORE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INV_ITEM_BU
BEFORE UPDATE ON HMS_INV_ITEM FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INV_STOCK_BU
BEFORE UPDATE ON HMS_INV_STOCK FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INDENT_BU
BEFORE UPDATE ON HMS_INDENT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_INDENT_DTL_BU
BEFORE UPDATE ON HMS_INDENT_DTL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_ASSET_BU
BEFORE UPDATE ON HMS_ASSET FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_DUTY_ROSTER_BU
BEFORE UPDATE ON HMS_DUTY_ROSTER FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_ATTENDANCE_BU
BEFORE UPDATE ON HMS_ATTENDANCE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LEAVE_TYPE_BU
BEFORE UPDATE ON HMS_LEAVE_TYPE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_LEAVE_APPLICATION_BU
BEFORE UPDATE ON HMS_LEAVE_APPLICATION FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_SALARY_STRUCTURE_BU
BEFORE UPDATE ON HMS_SALARY_STRUCTURE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_PAYROLL_BU
BEFORE UPDATE ON HMS_PAYROLL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_EMERGENCY_VISIT_BU
BEFORE UPDATE ON HMS_EMERGENCY_VISIT FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_EMERGENCY_TRIAGE_BU
BEFORE UPDATE ON HMS_EMERGENCY_TRIAGE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_AMBULANCE_BU
BEFORE UPDATE ON HMS_AMBULANCE FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_AMBULANCE_TRIP_BU
BEFORE UPDATE ON HMS_AMBULANCE_TRIP FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_MORTUARY_BU
BEFORE UPDATE ON HMS_MORTUARY FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_AUDIT_TRAIL_BU
BEFORE UPDATE ON HMS_AUDIT_TRAIL FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER TRG_ERROR_LOG_BU
BEFORE UPDATE ON HMS_ERROR_LOG FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY   := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER);
    :NEW.UPDATED_DATE := SYSTIMESTAMP;
END;
/
