/*
================================================================================
 File    : database/06_triggers/TRG_ADMISSION_BED_STATUS.sql
 Run As  : HMS_APP
 Purpose : Admission hole bed OCCUPIED, transfer/discharge hole CLEANING
================================================================================
*/
PROMPT >>> Creating TRG_ADMISSION_BED_STATUS ...
CREATE OR REPLACE TRIGGER TRG_ADMISSION_BED_STATUS
AFTER INSERT OR UPDATE OF BED_ID, ADMISSION_STATUS ON HMS_IPD_ADMISSION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE HMS_BED SET BED_STATUS = 'OCCUPIED' WHERE BED_ID = :NEW.BED_ID;

    ELSIF UPDATING('BED_ID') AND :OLD.BED_ID <> :NEW.BED_ID THEN
        UPDATE HMS_BED SET BED_STATUS = 'CLEANING' WHERE BED_ID = :OLD.BED_ID;
        UPDATE HMS_BED SET BED_STATUS = 'OCCUPIED' WHERE BED_ID = :NEW.BED_ID;
    END IF;

    IF UPDATING('ADMISSION_STATUS')
       AND :NEW.ADMISSION_STATUS IN ('DISCHARGED','LAMA','ABSCONDED','DEATH','REFERRED','CANCELLED')
       AND :OLD.ADMISSION_STATUS IN ('ADMITTED','DISCHARGE_INITIATED') THEN
        UPDATE HMS_BED SET BED_STATUS = 'CLEANING' WHERE BED_ID = :NEW.BED_ID;
    END IF;
END;
/
SHOW ERRORS
